### ISSUE TITLE
Wrong use of some abilities

### ISSUE THREAD

**Issue by Iztooi** [doxxx/ffxiv-craft-opt-web#100]
Hello,
I noticed that some abilities that can be used only on particular conditions are used wrongly by the solver or not at all.
OT: I know that trick of the trade, Byregot's Brow and Precise Touch are used on Good or Excellent condition, but those abilities should be used by humans and cannot really be predicted with an algorythm since the combinations would be too much.

I'm referring to:
Muscle Memory (it should be casted only on the 1st step, but the solver cast it even in other positions or not at all) (Anyway it recognizes the 1/3 progress)
Maker's Mark/Flawless Synthesis combo (same as before it doesn't cast Maker's Mark at the start making impossible combos with the Flawless Synthesis)
Whistle specialist actions (Whistle While You Work, Satisfaction, Trained Hand and Nymeia's Wheel). Whistles are not recorded, Satisfaction is used too often while it should be used only when the whistle stack is a multiple of three, Trained hand is used randomly because there are not whistle stacks and Nymeia's Wheel for the same reason since the stacks are not recorded.)

I know that the tool should be used with awareness of what the skills do, but the solver is a great part of the tool and is supposed to be used to create rotations.
I know also that the variables of Whistles and 1st actions are too much precise to be put in an algorythm but i wanted to report this "issue"

Hope i was of help.

**Comment by doxxx** [comment]
The solver is an evolutionary algorithm and it doesn't really understand how to "play the game", so it's going to make mistakes. Try running the solver again to see if it comes up with a better solution.
