### ISSUE TITLE
New items of 3.2

### ISSUE THREAD

**Issue by Ley21** [doxxx/ffxiv-craft-opt-web#107]
Hello,

there a new recipes in 3.2 and I hope you can update your database.
It would be nice if you can upgrade the website also.

Thank you ^^

**Comment by Pr0num** [comment]
3.15 stuff still hasn't been added either. At this point this looks abandoned.

**Comment by doxxx** [comment]
I've updated the recipe database for the beta website to include the latest data from lodestone.
