### ISSUE TITLE
Reminder to update for 3.3 recipes.

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#111]
Basically what's in the title. Katrisa in our FC mentioned something the other day about one of the two star recipes having changed in difficulty.

**Comment by katrisashe** [comment]
After my brain woke up.  The change is in the new three star recipes at the least which have a higher difficulty level and requirements.

**Comment by doxxx** [comment]
The Lodestone web page structure has changed, so I need to update the scraper tool first.

**Comment by doxxx** [comment]
Can you give me an example of a recipe that has changed so I can double-check the data?

**Comment by doxxx** [comment]
I've uploaded the latest recipes to the beta site. Let me know if there's still stuff missing.
