### ISSUE TITLE
Recipe links

### ISSUE THREAD

**Issue by ufx** [doxxx/ffxiv-craft-opt-web#112]
I'd love to directly link a class and recipe in your simulator from my site (www.garlandtools.org).  Since we probably don't share item or recipe IDs, perhaps something that fills the search box from the URL hash would work?

Clorifex

**Comment by doxxx** [comment]
Nice idea, I think somebody has suggested it before, but I am unable to look into this right now.

**Comment by doxxx** [comment]
Not deployed to the beta site yet, please try it with a local instance of the site and let me know how it works.

**Comment by ufx** [comment]
Looks great, thank you!  I'll test it out soon.
