### ISSUE TITLE
Obligitory Reminder

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#114]
It's that time again. Just a reminder to pull in the data for the 3.4 recipes.

Sweet jesus. 1968 difficulty, 995 Crafts, 955 Control minimum.

**Comment by doxxx** [comment]
I'm assuming an effective recipe level of 190 for the 4-star recipes. No idea if that's actually correct. :)

**Comment by doxxx** [comment]
Beta website should be updated.
