### ISSUE TITLE
4star Progress wrong, even more wrong with Ingenuity II 

### ISSUE THREAD

**Issue by Saberawr** [doxxx/ffxiv-craft-opt-web#115]
Here are some correct values
![firefox_2016-09-29_13-39-02](https://cloud.githubusercontent.com/assets/7264361/18967304/417cd20c-864a-11e6-9b28-8cc3cbf61009.png)

**Comment by doxxx** [comment]
Unfortunately, we don't have the time or resources to investigate and resolve issues like these.

**Comment by katx** [comment]
Added a pull request with updated tables. tested it on my VM.

**Comment by doxxx** [comment]
@Saberawr Ing/Ing2+RS should be improved for 2-4 star recipes, thanks to @Igor-Yavych.

**Comment by doxxx** [comment]
These formulas have changed significant in patch 4.0 and the beta site has been updated accordingly. Please let me know if you're still having problems.
