### ISSUE TITLE
the macro page do not show

### ISSUE THREAD

**Issue by hbq0449** [doxxx/ffxiv-craft-opt-web#117]
serve the app dir on my server. 
resolve function works fine. But can not output the macro. Checkout the firefox console, it says macros.html response 404.

**Comment by hbq0449** [comment]
update with call stack：
angular.js:9503 Error: [$compile:tpload] http://errors.angularjs.org/1.2.13/$compile/tpload?p0=..%2F..%2Fcomponents%2Fmacros.html
    at angular.js:36
    at angular.js:6498
    at angular.js:7651
    at I (angular.js:11042)
    at I (angular.js:11042)
    at I (angular.js:11042)
    at angular.js:11174
    at h.$eval (angular.js:12045)
    at h.$digest (angular.js:11871)
    at h.$apply (angular.js:12151)

**Comment by hbq0449** [comment]
plz close the issue. I solved it by move the app content direct under the root of the server.

**Comment by doxxx** [comment]
Yes, the app folder must be served as the root of the web server.
