### ISSUE TITLE
When a craft can be completed in one macro, it is split into two. 

### ISSUE THREAD

**Issue by TheTweets** [doxxx/ffxiv-craft-opt-web#118]
If a craft uses 15 actions, it will create a 14-line macro followed the by macro-completion notice, and a second single-line macro with a second macro-completion notice. 

This could be condensed at the cost of the completion notice - rather than alerting the user that a single action is required, it could finish the craft immediately so they don't need to be alerted in the first place.

**Comment by Ninjistix** [comment]
I've also noticed this, it will have 14 actions on first macro with the 15th line as an echo macro1 complete, and 1 action on the second macro with the 2nd line being macro complete.

**Comment by doxxx** [comment]
Deployed to beta site.

**Comment by Ninjistix** [comment]
thanks 👍
