### ISSUE TITLE
Unable to Import Char data

### ISSUE THREAD

**Issue by Ninjistix** [doxxx/ffxiv-craft-opt-web#122]
Not sure if this has been reported or not, tried to check open/closed issues.

`{"data":"","status":404,"config":{"transformRequest":[null],"transformResponse":[null],"params":{"name":"xiao xun","server":"Excalibur"},"method":"GET","url":"http://xivsync.com/search/character","headers":{"Accept":"application/json, text/plain, */*"}}}`

get that error when trying to import char skills on beta site, tried multiple chars.

**Comment by doxxx** [comment]
Looks like the xivsync.com API is gone :(

However, it looks like the xivdb.com API by @viion is functional for character search and info...

**Comment by viion** [comment]
Hello!

For now those routes have gone until I redo them in PHP to fit the new framework, for now I've been using:  https://xivsync.com:8443/characters/search?name=xiao+xu - This is a nodeJS app that needs converting.

You can use XIVDB as well, but not all characters are on there.

**Comment by Ninjistix** [comment]
my char info XIVDB is outdated trying to see if it can pull the new info.

**Comment by viion** [comment]
I've sorted it, for some reason the system thought your character was deleted, must be a bug (unless you requested me to delete it a long time ago?)

**Comment by Ninjistix** [comment]
nope never requested for it to be deleted. :D but thanks, its updated and working now. (on XIVDB)

**Comment by doxxx** [comment]
I'm working on adapting the code to the alternate xivsync api, and I'll see about adding support for xivdb later.

**Comment by Ninjistix** [comment]
thanks a lot @doxxx , recently came back to the game, and this website is helping leveling crafting soooo much easier.

**Comment by doxxx** [comment]
That's why we made it! :)

**Comment by Ninjistix** [comment]
and chance they'll be support for gathering 🍡  (i'm super lazy lol... )

**Comment by doxxx** [comment]
No support for gathering unfortunately. We don't play the game anymore, so can't really add new features (or even fix bugs) that require in-game testing.

**Comment by Ninjistix** [comment]
okay, thanks anyways... yeah I just came back to the game... myself.. but this site is very helpful not only for leveling crafts but when trying to HQ something or get a higher grade collectable :D

**Comment by doxxx** [comment]
Ahhhh, the alternate xivsync api doesn't show the last gear equipped for different jobs, just what the character is currently wearing. The most I can get out of this is the level of each crafting class. :P

**Comment by viion** [comment]
Yeah that is all on XIVDB now, for example: https://api.xivdb.com/character/730968?data=gearsets

**Comment by Ninjistix** [comment]
I say lets jump to XIVDB 🥇

**Comment by doxxx** [comment]
@Ninjistix could you try to get xivdb updated with a gearset for one of your crafting jobs?

**Comment by Ninjistix** [comment]
okay let me try, i'm currently crafting on carpenter

**Comment by viion** [comment]
I have some notes here: https://github.com/viion/XIVDB-API/blob/master/notes.md

You'd essentially have:
- Searching: https://api.xivdb.com/search?one=characters&server|et=<server>&string=<character
  - eg: https://api.xivdb.com/search?one=characters&server|et=Phoenix&string=Premium+Virtue
- Get profile: https://api.xivdb.com/character/730968
- Get gearsets: https://api.xivdb.com/character/730968?data=gearsets

If you need another language, provide `language=value`.

**Comment by Ninjistix** [comment]
just logged out to see if XIVDB/Lodestone updates gear set to crafting profile.. will check while on my way home from work, 

if anything here's my friends char and it has gearsets from XIVDB

http://xivdb.com/character/491173/peppermint+chocolate/excalibur

**Comment by doxxx** [comment]
Yeah, that'll work. Thanks!

**Comment by doxxx** [comment]
@viion Why does https://api.xivdb.com/character/12607753?data=gearsets return an object but https://api.xivdb.com/character/491173?data=gearsets returns an array?

**Comment by viion** [comment]
In my API they all come back as object to avoid duplication, but I sort them by level which returns array, the object one you see has only one entry do it doesn't get sorted, I need to fix my logic. I'll do it tomorrow and it will always be an array.

**Comment by doxxx** [comment]
@viion The last_updated timestamps for the gearsets -- are those in UTC?

**Comment by viion** [comment]
Yes

**Comment by doxxx** [comment]
Should be fixed now. You'll need to force a refresh in your browser to get the new files.

**Comment by Ninjistix** [comment]
okay ill clear cache, and try again thanks 👯

**Comment by Ninjistix** [comment]
the char shows up but says 

![capture](https://cloud.githubusercontent.com/assets/12572974/21790677/fc7549fc-d6ab-11e6-9303-7830e37877d0.PNG)

**Comment by doxxx** [comment]
Yeah, that means that there is no usable information about crafter classes to import. You'll need to log out of FFXIV with your crafter class active and the right gear equipped, and then click the Update button on your XIVDB character page. If you see your crafter class in the Gearsets section on XIVDB then the import should work.

**Comment by Ninjistix** [comment]
let me try, does the lodestone need to be updated too or just xivdb?

**Comment by doxxx** [comment]
I think xivdb scrapes the data from lodestone.
