### ISSUE TITLE
Feature Request: Sign in options?

### ISSUE THREAD

**Issue by Ninjistix** [doxxx/ffxiv-craft-opt-web#123]
Would it be possible to have sign in options like Facebook/Google/Xivdb so I wouldn't need to re-import or change settings every time I change computers/browsers?

**Comment by Ninjistix** [comment]
with also the possibility to save or remember recent solutions for specific crafts? I craft at work and home, and I need to remote to both computers to remember what I was last crafting or what macro order I need to do

**Comment by doxxx** [comment]
This is already filed under #20 but is rather non-trivial and would require backend server resources which complicates deployment.

**Comment by Ninjistix** [comment]
derp did not see that, but essentially this would be ideal
