### ISSUE TITLE
Sorry for posting again...

### ISSUE THREAD

**Issue by LunaAmell** [doxxx/ffxiv-craft-opt-web#126]
Both specialist and some skills are not available, when I tried to use the solver it was unclickable. The beta site isn't working either.  Edit add: It looks like skills from level 50 to 60 are not available. 

http://puu.sh/trku0/af988d6f27.png 

I'm trying to make Emerald Soup. 

For the other beta site this is how it looks. 
http://puu.sh/trkBM/a4ca78a4ac.png 

And the skills are unclickable.

**Comment by doxxx** [comment]
ffxiv.lokyst.net site is very out of date, only the ffxiv-beta site is up-to-date. Please clear your browser's cache and reload the website.

**Comment by LunaAmell** [comment]
I tried that it didn't work. x.x

**Comment by doxxx** [comment]
Can you press F12 in your browser and see if there's an error in the console?

**Comment by LunaAmell** [comment]
It doesn't look like it. I even tried it on Microsoft Edge and I mainly use Firefox.

**Comment by doxxx** [comment]
Okay, I can see the problem in Edge. I'll investigate.

**Comment by LunaAmell** [comment]
I even tried updating my flash player. I asked my friend to check the site and it works on their end. So I'm not sure whats wrong on my end.

**Comment by doxxx** [comment]
It was a bug in the code for loading the saved synths on startup. Please force reload and try again.

**Comment by LunaAmell** [comment]
Yay thank you! It works now. This is the only crafting help I've been able to find since I'm not very good at stringing together a rotation. ^^ Thank you so much!
