### ISSUE TITLE
Maker's Mark macro wait is too short

### ISSUE THREAD

**Issue by coredumperror** [doxxx/ffxiv-craft-opt-web#127]
I don't know why, but <wait.2> after a Maker's Mark does not give enough time for the next action to fire, and I get an error. Upping it in my macro to <wait.3> fixed the problem, though, so that seems like the best solution.

**Comment by doxxx** [comment]
You can adjust the wait time for buffs in the Options.

**Comment by coredumperror** [comment]
2 seconds is fine for every other buff, though. It's *just* Maker's Mark that has that odd bit of delay before the buff comes up, requiring 3 seconds instead of 2.
