### ISSUE TITLE
Byregot's Miracle cannot be used at 1 stack of Inner quite

### ISSUE THREAD

**Issue by Hinalover** [doxxx/ffxiv-craft-opt-web#128]
This is the second time this has happened to be but the specialist ability Byregot's Miracle cannot be used at 1 stack of Inner Quite. A recent macro I got for Amphiptere Leather had me use Inner Quiet at 1 stack. however the ability is greyed out when the ability is trying to be cast.

/ac "Steady Hand II" <me> <wait.2>
/ac "Inner Quiet" <me> <wait.2>
/ac "Manipulation" <me> <wait.2>
/ac "Byregot's Miracle" <me> <wait.3>
/ac "Hasty Touch" <me> <wait.3>
/ac "Innovative Touch" <me> <wait.3>
/ac "Great Strides" <me> <wait.2>
/ac "Advanced Touch" <me> <wait.3>
/ac "Steady Hand II" <me> <wait.2>
/ac "Innovative Touch" <me> <wait.3>
/ac "Great Strides" <me> <wait.2>
/ac "Byregot's Blessing" <me> <wait.3>
/ac "Name of Earth" <me> <wait.2>
/ac "Brand of Earth" <me> <wait.3>
/echo Macro #1 complete <se.14>
![ffxiv_02112017_172244_crop](https://cloud.githubusercontent.com/assets/10355909/22857973/17318d4a-f07f-11e6-9b8a-9de719677759.png)

**Comment by doxxx** [comment]
Thanks for letting us know. We'll take a look.

**Comment by doxxx** [comment]
@Hinalover When using Byregot's Miracle, does the Inner Quiet stack go from N to N/2 or to N/2 + 1? I.e. if you have Inner Quiet stacked to 4 and you use Byregot's Miracle, does the Inner Quiet stack go down to 2 or 3?

**Comment by Hinalover** [comment]
looks like it rounds up
Inner Quite 2 -> Inner Quite 1
Inner Quite 3 -> Inner Quite 2
Inner Quite 4 -> Inner Quite 2
Inner Quite 5 -> Inner Quite 3
