### ISSUE TITLE
uses deselected skills

### ISSUE THREAD

**Issue by xeno002** [doxxx/ffxiv-craft-opt-web#132]
GSM Innovative Touch (Specialist Skill) has been deselected in the Available Actions, but it keeps coming up in the solver result.

**Comment by bobsponsler** [comment]
I am having the same problem as is my friend, I made a new post with a debug file attached hopefully they can figure it out because it is killing some big crafts for me.  :(

**Comment by bobsponsler** [comment]
Xeno - Are you using Chrome?  We were both having this problem using Chrome.  I just reentered everything in internet explorer and ran the solver there and it works fine.  I hate IE but if this is a usable workaround I'll take it! :)

**Comment by doxxx** [comment]
Is this still a problem?

**Comment by Battler624** [comment]
@doxxx I never used this site before stormblood but I've been able to deselect skills and it wouldn't use them within the past 3 weeks.

I think it is solved.

**Comment by doxxx** [comment]
Thanks.
