### ISSUE TITLE
Add option to use Precise+Basic touch

### ISSUE THREAD

**Issue by AUTOMATIC1111** [doxxx/ffxiv-craft-opt-web#134]
I am manually replacing

/ac "Basic Touch" <me> <wait.3>

with

/ac "Precise Touch" <me>
/ac "Basic Touch" <me> <wait.3>

In all scripts I use. This lets me use Precise Touch if it's available and Basic Touch otherwise.
It would help if there was an option to have the site make those modifications for me. Thanks!

**Comment by doxxx** [comment]
Superceded by #174
