### ISSUE TITLE
Maker's Mark waittime needs to be 3 seconds instead of 2

### ISSUE THREAD

**Issue by shentschel** [doxxx/ffxiv-craft-opt-web#135]
Well I think the topic says what is happening.

When you add makers mark to your skills in the simulator the macro tab adds a wait time of 2 seconds.
Ingame the skill is finished after 3 seconds so if you want to use another skill via macro after 2 seconds it fails.

**Comment by doxxx** [comment]
You can increase the wait time for buffs in the settings.

**Comment by shentschel** [comment]
Sounds nice but why should I increase the wait time of _all_ buffs when only one needs more time?
