### ISSUE TITLE
How to add a new language

### ISSUE THREAD

**Issue by billxc** [doxxx/ffxiv-craft-opt-web#136]
Hi Doxxx,

First thank you for your great work for this wonderful tool. It helps me a lot with my FFIV crafting.

I am a Chinese FFIV pleayer, and I would like to export the macro in Chinese, because our Chinese client only support macro in Chinese. 

So I want to add a new language for Chinese, and I did find how to do it.

Regards,
Bill

**Comment by doxxx** [comment]
The translation files are here: https://github.com/doxxx/ffxiv-craft-opt-web/tree/master/app/locale

And you will also have to add the language here: https://github.com/doxxx/ffxiv-craft-opt-web/blob/master/app/js/services/locale.js

**Comment by billxc** [comment]
Thanks, it works. 
But I also find that I need to add translation for files in this folder.
https://github.com/doxxx/ffxiv-craft-opt-web/tree/master/app/data/recipedb
In my case, I just copied the names from English

**Comment by doxxx** [comment]
Yes. I got those names from the Lodestone website. Do they have a Chinese Lodestone website?

**Comment by billxc** [comment]
I'm afraid not.

**Comment by doxxx** [comment]
If you can provide a pull request with the changes, I can get it onto the main site. Although if you have trouble accessing our website from China I guess there's not much point in doing that.

**Comment by billxc** [comment]
Thanks, Translation is huge work, but it seems that someone already finished that work. 
I will try to negotiate with the guy.

**Comment by doxxx** [comment]
This has been merged into master from #138 and uploaded to the beta site (ffxiv-beta.lokyst.net).
