### ISSUE TITLE
Updating for 4.0?

### ISSUE THREAD

**Issue by LunaAmell** [doxxx/ffxiv-craft-opt-web#137]
Is this going to be updated for the expansion?

**Comment by doxxx** [comment]
All we can commit to is updating the recipe lists.

**Comment by crossedxd** [comment]
Can the level cap be increased from 60-70 in the Options window in the meantime?  Or is that dependent on the formulas that may or may not need to be updated as well?

**Comment by Caazel** [comment]
Doxxx,  what are the main barriers preventing you and team from fully updating the project to incorporate 4.0?

I am an avid user of the site and a big fan. You've all done a remarkable job.  Is there anything I (or we as the community) can do that would help facilitate a larger commitment? 

Personally, I am willing to donate my time and resources if it means bringing it up to date.  I will happily record data, test code, help program, and, within reason, I will even donate funds (or help fundraise) to the endeavor.  (Though as for personal donations, I'm  cash poor.)   I'd be happy to donate subscription funds or help pay for server maintenance.

Anything we can do to change your assessment from "all we can commit to"  to something more definite?

**Comment by coredumperror** [comment]
I have an extra long weekend coming up, and I am almost done leveling my crafters to 70. Once I do, I'd be happy to commit some PRs to update this awesome tool. At the very least, I intend to add the new actions, to make it easier to craft macros.

**Comment by doxxx** [comment]
There is some work being done on this in #139.

**Comment by doxxx** [comment]
Ermad's changes have been merged and published to the beta site. If you find any remaining problems, please file a new issue!
