### ISSUE TITLE
Feature Request: Stat Display Changes

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#143]
Could a display of the post food stats be shown in addition to the current stats, for the purposes of easier entry when a food buff is in use?

That or alternatively a list of common crafter foods to automatically make the calculations, if it's possible to do so.

**Comment by Battler624** [comment]
you mean this part here @Diskmaster http://i.imgur.com/0YtWdfr.png

**Comment by Diskmaster** [comment]
@Battler624 Yeah, for clarification, that's the stats block I'm talking about. Maybe a second set of boxes to enter or the drop down as I mentioned in the earlier comment.

**Comment by doxxx** [comment]
Deployed to beta site. Please force reload.

**Comment by Battler624** [comment]
holy shit this looks beautiful.

**Comment by doxxx** [comment]
Glad you like it!
