### ISSUE TITLE
Careful Synthesis and Careful Synthesis II have incorrect French translation

### ISSUE THREAD

**Issue by HimeragiTsume** [doxxx/ffxiv-craft-opt-web#148]
Hi there !
There's a mistake in macro generation in French, tooltip is showing fine "Travail Prudent II" (Careful Synthesis II) but the skill name in macro tab is the pre 4.0 name "Synthèse Prudente II" (Don't know why they changed it but well...)
Thanks !

**Comment by doxxx** [comment]
Deployed to beta site.

**Comment by HimeragiTsume** [comment]
Awesome thanks
