### ISSUE TITLE
XIVDB Character Import pulls outdated data

### ISSUE THREAD

**Issue by belazor** [doxxx/ffxiv-craft-opt-web#151]
If I hit Import on my character so it pulls data from XIVDB, the data is wrong. Literally every crafter level is incorrect, in fact. 

My character is on Omega, called Ilyxia Britannia

Here’s the XIVDB link: http://xivdb.com/character/2188312/ilyxia+britannia/omega

If you try importing it here, you’ll see all the levels are wrong.

**Comment by doxxx** [comment]
Are the levels in XIVDB wrong or are the levels in our app wrong after an import from XIVDB?

**Comment by belazor** [comment]
Levels in your app.

Your app: https://i.imgur.com/vVjYVLt.png
XIVDB: https://i.imgur.com/HFUh1kb.png

**Comment by doxxx** [comment]
Thanks. I'll take a look later.

**Comment by doxxx** [comment]
So our character import pulls the class level from the gearset data. However, that appears to be the character level at which that particular gearset was last captured, whereas it seems that XIVDB may update the character level without capturing a new gearset to go with it.

We could get a more accurate class level by looking at the classj/job data but the attributes from the gearset data would still be outdated. I think this would still be an improvement. Do you agree?

**Comment by doxxx** [comment]
I've deployed a fix to the beta site which should make it pick up the most recent class levels.

**Comment by belazor** [comment]
Confirmed it pulls the correct levels when I search for my character now, so assuming there's not going to be any caching nonsense going on in the future, I'd say this is fixed :)

Thanks!
