### ISSUE TITLE
UI issue when selecting crafter class on mobile

### ISSUE THREAD

**Issue by belazor** [doxxx/ffxiv-craft-opt-web#152]
iOS 11 Public Beta 1 (Safari):

![u3cn0dgut9myn5fqgv97dg_thumb_3fd](https://user-images.githubusercontent.com/9424286/28069116-297cba7e-6640-11e7-8c6e-71be663520a1.jpg)

**Comment by doxxx** [comment]
Yeah the layout is not great on an iPhone class display. It's pretty hard to get it right across multiple display classes. I've got a branch where I've been upgrading the site to the latest Bootstrap etc which I think lets me pick different component sizes according to the size of the display. 

Honestly though, the primary target for this site is desktop or at least iPad sized devices. I doubt it will ever work very well on phones.

**Comment by belazor** [comment]
You can also add the following code to app.css:

```@media (max-width: 480px) {
  .my-dropdown {
    display: block;
  }
}

@media (min-width: 600px) {
  .my-dropdown {
	  margin-left: 35px;
  }
}

@media (min-width: 800px) {
  .my-dropdown {
	  margin-left: 0;
  }
}
```

That will push the recipe drop-down to a second line on mobile devices, for landscape mobile devices it will correct the overlap as the viewport is big enough, and on desktop devices (800x600 or higher) it will stay as-is :)

**Comment by doxxx** [comment]
Deployed to beta.
