### ISSUE TITLE
Additional Action Macro request

### ISSUE THREAD

**Issue by Vuzrak** [doxxx/ffxiv-craft-opt-web#153]
Is it possible to have it generate a macro for the additional actions that are needed, something like:

/aaction clear
/aaction "Byregot's Blessing" on
/aaction "Innovation" on
/aaction "Waste Not II" on
/aaction "Careful Synthesis II" on

**Comment by lokyst** [comment]
@doxxx these are the cross class actions that we identify with the little
icons in the top right corner of the action. If I understand the patch
notes correctly you can now enable/disable them with a macro instead of
having to manually select and activate.

**Comment by doxxx** [comment]
Oh that's nice. Yeah we could easily generate a macro to enable the set of cross class actions needed by a sequence.

**Comment by doxxx** [comment]
@Vuzrak Is there any delay needed on those or before actual crafting actions are executed?

**Comment by Vuzrak** [comment]
No delays needed, but it might be best to make it a separate macro from the crafting itself since you only need it at the start once.

**Comment by doxxx** [comment]
Deployed to beta site. Please use a hard refresh to get the latest files.
