### ISSUE TITLE
Manipulation bug

### ISSUE THREAD

**Issue by Mygrn** [doxxx/ffxiv-craft-opt-web#154]
With the new change to manipulation, in that "Each step overwrites all durability-restoring actions." due to manipulation 2 being added, the tool can sometimes recommend that manipulation be used while manipulation is up and thus counts a tick of durability that didn't happen.

IE I was suggested a macro that did manipulation, hasty touch, hasty touch, manipulation, hasty touch, hasty touch, careful synthesis 2. According to the tool the durability is restored, from the first Manipulation, when you hit the second Manipulation. However, due to the change. That third tick is negated by activating Manipulation and thus I am short 10 durability the tool thought I had and thus the macro fails.

**Comment by Ermad** [comment]
I have submitted a change with this fixed.

**Comment by doxxx** [comment]
Deployed to beta.
