### ISSUE TITLE
Standard Synthesis mistaken probability

### ISSUE THREAD

**Issue by Mygrn** [doxxx/ffxiv-craft-opt-web#155]
I tend to think that the tool now thinks standard synthesis has careful synthesis 3's probably of success. A couple times the tool has recommended standard synthesis for a macro and assumes 100% completion rate. However, standard synthesis has a 10% chance to fail.

**Comment by doxxx** [comment]
The tool still considers Standard Synthesis to have a 90% chance of succeeding. Can you elaborate on the problem you're seeing?

**Comment by Mygrn** [comment]
Found the issue. In short I'm an idiot and it's entirely user error.

Longer story is when I was testing things earlier I lowed reliability% to 90% and forgot to reset it to 100% after the test. So it recommended standard synthesis as per my settings.

Sorry for the bogus report.

**Comment by doxxx** [comment]
No worries! Thanks for getting back to us. :)
