### ISSUE TITLE
Byregot's Brow

### ISSUE THREAD

**Issue by chase411** [doxxx/ffxiv-craft-opt-web#156]
The simulator wants to use Byregot's Brow constantly, even without setting up Inner Quiet. I initially thought BB had changed in game but the macro's definitely don't work. Really excited to see that the optimizer was updated and hoping this issue can be fixed soon!

Cheers,
Garr

**Comment by doxxx** [comment]
@ermad I think you changed that recently? Could you take a look?

**Comment by chase411** [comment]
Hmm, suddenly not doing it now. Could different seeds be responsible for when it does / does not appear?

**Comment by chase411** [comment]
And now it is back. How odd.

**Comment by Ermad** [comment]
I don't think any new bug was introduced, just that Byregot's Brow was buffed enough that if you were able to cast it without Inner Quiet it might be a reasonable thing to do.

I'll put some additional checks on the action so it doesn't work without Inner Quiet active.

**Comment by lokyst** [comment]
@ermad I try to avoid putting in restrictions that are artificial. If
Byregot's truly works irl without inner quiet, I would leave it like that
and not put an artificial restriction that might close off a non-standard
approach.

As you say there are some circumstances where it might be beneficial to use
without IQ.

**Comment by Ermad** [comment]
It doesn't, you can't even cast any of the Byregot's actions until you have 2 stacks of Inner Quiet. Previously this was modelled for Byregot's Miracle, but not Brow or Blessing.

**Comment by doxxx** [comment]
Should be fixed in c7cc30ae.

**Comment by doxxx** [comment]
Deployed to beta.

**Comment by chase411** [comment]
Thanks for the fix, however I don't think it is reflected on the beta: http://ffxiv-beta.lokyst.net/#/solver (in case I have the wrong url). Here's what I got for Twinthread on my level 70 wvr, specialist, all others 70, 1273/1134/478 stats:

/ac "Innovation" <wait.2>
/ac "Great Strides" <wait.2>
/ac "Comfort Zone" <wait.2>
/ac "Byregot's Brow" <wait.3>
/ac "Careful Synthesis III" <wait.3>
/ac "Manipulation II" <wait.2>
/ac "Careful Synthesis III" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Steady Hand II" <wait.2>
/ac "Innovation" <wait.2>
/ac "Byregot's Brow" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Byregot's Brow" <wait.3>
/ac "Innovation" <wait.2>
/echo Macro #1 complete <se.1>

/ac "Steady Hand II" <wait.2>
/ac "Great Strides" <wait.2>
/ac "Byregot's Brow" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Innovation" <wait.2>
/ac "Byregot's Brow" <wait.3>
/ac "Careful Synthesis III" <wait.3>
/echo Macro #2 complete <se.14>

**Comment by doxxx** [comment]
Could you try forcing a refresh of the site by holding Ctrl+Shift and clicking the Reload button in your browser? You'll have to rerun the solver to get a fresh result.

**Comment by chase411** [comment]
OK, I have a cached version, it worked when I brought it up in incognito. Sorry for being stupid! By the way this site has completely changed how I viewed crafting in this game. You both do amazing work.

**Comment by doxxx** [comment]
No worries. I think our webhost does some aggressive caching, which we unfortunately don't have control over. 

And thanks!
