### ISSUE TITLE
"No data available!" on Character Import

### ISSUE THREAD

**Issue by AlexanderReichart** [doxxx/ffxiv-craft-opt-web#157]
When trying to use the Character Import it finds the character, Displays the profile pic and name but for the stats it says "No data available"
Server : Cactuar
Character : Grey Thirteen
![grafik](https://user-images.githubusercontent.com/14053466/28239931-4fc1af8e-6977-11e7-8ce4-fbc5fb03e999.png)

The data does seem to be publically accessible on xivdb though.
![grafik](https://user-images.githubusercontent.com/14053466/28239952-d76aa6d4-6977-11e7-983c-54f240d0c51f.png)

**Comment by doxxx** [comment]
The character import relies on the Gearset data from XIVDB. Your character only has Paladin and White mage gearset data on XIVDB, so there's no information on crafting classes for us to import.

I have a TODO to improve the character import to at least grab character levels even if there is no gearset data.

**Comment by AlexanderReichart** [comment]
Ooooh That makes sense. Thank you!

**Comment by doxxx** [comment]
I've deployed a fix to the beta site which should make it pick up class levels even if there is no gearset data for those classes.
