### ISSUE TITLE
Wrong application of initial preparations and bug with high level skills.

### ISSUE THREAD

**Issue by Euphir** [doxxx/ffxiv-craft-opt-web#159]
There seems to be an issue with initial preparations and that is making macros that fail due to not having those extra CP. Here's one of the logs.

```
Seed: 1500280768436, Use Conditions: true


Crafter Actions:
  0: advancedTouch
  1: basicSynth
  2: basicTouch
  3: byregotsBlessing
  4: carefulSynthesis2
  5: carefulSynthesis3
  6: focusedSynthesis
  7: focusedTouch
  8: greatStrides
  9: ingenuity
  10: ingenuity2
  11: initialPreparations    <---- ??????
  12: innerQuiet
  13: innovation
  14: observe
  15: specialtyReflect
  16: specialtyRefurbish
  17: specialtyReinforce
  18: standardSynthesis
  19: standardTouch
  20: steadyHand
  21: wasteNot
  22: wasteNot2

No initial sequence provided; seeding with the following heuristic sequence:

Inner Quiet | Steady Hand | Great Strides | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II

 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   80   408        0        0     0     0  1087     0     0     0     0     Normal     0
 1 Inner Quiet                       80   405        0        0     0     0  1087     0     0     0     0     Normal     1
 2 Steady Hand                       80   383        0        0     0     0  1087     0     0     0     0       Good     1
 3 Great Strides                     80   351        0        0     0     0  1087     0     0     0     0     Normal     1
 4 Careful Synthesis II              70   351        0      291     0     0  1087     0   291     0     0       Good     1
 5 Careful Synthesis II              60   351        0      582     0     0  1087     0   291     0     0     Normal     1
 6 Careful Synthesis II              50   351        0      873     0     0  1087     0   291     0     0     Normal     1
 7 Careful Synthesis II              40   351        0     1164     0     0  1087     0   291     0     0       Good     1
 8 Careful Synthesis II              30   351        0     1455     0     0  1087     0   291     0     0     Normal     1
 9 Careful Synthesis II              20   351        0     1746     0     0  1087     0   291     0     0     Normal     1
10 Careful Synthesis II              10   351        0     2037     0     0  1087     0   291     0     0  Excellent     1
11 Careful Synthesis II               0   351        0     2328     0     0  1087     0   291     0     0       Poor     1
Progress Check: false, Durability Check: false, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 1, Wasted Actions: 0
Heuristic sequence feasibility:
Progress: false, Durability: false, CP: true, Tricks: true, Reliability: true
```

As you can see, Initial Preparations is appearing on but it's not applied as it should on step one of the synth.

Also, the simulator isn't applying the new skills properly to the macros. They're on the log as selected but they don't appear anywhere on the macro thus making the macros dangerous to use. 

I've failed more than one craft due to these issues and resorted to removing the tick from "Specialist" and removed the new actions from my list.

[Another log example](http://i.imgur.com/yaHDmLj.png)
[How the macro looks](http://i.imgur.com/0C38fIQ.png)

**Comment by doxxx** [comment]
That list, entitled Crafter Actions, is simply the list of actions that are enabled for the solver's use.

As for why the actual sequence that the solver arrives at (the icons above the execution log) does not include any new Stormblood actions -- the solver simply may not have tried the right combinations. You can try switching the solver algorithm to eaComplex in the Options, and also try Continuing the solver a few more times after it finishes each run.

**Comment by Euphir** [comment]
I tried several options, always ended up with this kind of results. The fact is that the macros are not being generated with the new actions and this makes the synth fail. 

Also,  the extra CP for Initial Preparations is being added without the action appearing anywhere.

I'm sorry but there's no way this is working properly.

**Comment by doxxx** [comment]
Could you provide the craftsmanship, control and CP? Also, which class and recipe? Are you entering anything in the Bonus Attributes box on the Simulator page?

**Comment by Euphir** [comment]
Sure: 

[My Blacksmith with my most commonly used skills + the new specialist skills](http://i.imgur.com/gyIZ6ZY.png)

[Stats pre-simulation. Please note there's nothing on bonus and my CP is 408](http://i.imgur.com/f0VSWww.png)

[After simulation. CP was added but I.P was NOT used. All new specialist skills ignored. This synth macro if used, will fail due to not having enough CP.](http://i.imgur.com/17GOZRe.png)

**Comment by Ermad** [comment]
I am confused about what you are talking about. You are mentioning the extra CP from Initial Preparations, but that does not give extra CP. It gives a random proc to reduce CP cost, but that isn't modelled at all currently. At the moment it only enables the use of the "Specialty: X" actions.

The extra 15 CP is from Stroke of Genius, which has a 100% proc rate if you are a specialist, and is only modeled if your class is marked as a specialist. What it looks like to me is that your are marking Specialist on the crafter stats page, and then trying to use the rotation on a non-Specialist.

**Comment by Euphir** [comment]
[Ah, so I'm not a level 70, Non-Specialist, Blacksmith and I don't have my traits now.](http://i.imgur.com/5tGRUZs.png)

So, the only explanation is the trait being broken because I can assure you that I'm not getting those CP in-game.

Also, none of the new observe+skill combos are being pulled into the equation or the new specialist skills.

**Comment by Ermad** [comment]
It's not broken. When you are a specialist it has a 100% proc rate, you have ticked the specialist box and are then trying to use it a non-specialist.

**Comment by Euphir** [comment]
Are you joking with me or missing out my specialist stone on purpose?

**Comment by Ermad** [comment]
You post said "non-specialist" before you edited it. If you are a level 70 specialist it procs on every craft in game. If it doesn't then its a bug in game.

**Comment by Euphir** [comment]
Yeah, typos happen but you should have looked at the screenshot I linked before making that comment, don't you think?

That's my character there, and you can see stats, specialist stone and traits. All there. I don't get those CP and failed more than one synth because of it which is why I ticked out specialist.

Something is broken either in-game or with the simulator.

**Comment by Ermad** [comment]
What I am saying is the trait "Stroke of Genius" that gives 15 bonus CP, procs 100% of the time in-game for specalists.

If you believe the trait isn't acting as described by the game, please post a screenshot of a craft past step 2 with no proc and your character sheet open.

**Comment by doxxx** [comment]
@euphir We're not saying the simulator is perfect but your observations don't match up with our current understanding of the game and the way the simulator is implemented, so we're trying to pinpoint where the disconnect is.
