### ISSUE TITLE
Add feature to solve within space of one macro

### ISSUE THREAD

**Issue by danielshawnds** [doxxx/ffxiv-craft-opt-web#161]
User Story:  As a crafter, I want to use a single macro to craft, to save time and effort, even if it comes at the cost of craft quality.

**Comment by doxxx** [comment]
Deployed to beta site.

A new Max Length option has been added to the Options dialog (cog icon in top right or Options button on Solver page). When the Max Length option has been enabled, the solver will now try to limit the length of the sequence.

Something to bear in mind is that the limit is merely another constraint on the fitness of a sequence that is being evaluated by the solver. Reliability is still a primary constraint, so if your Reliability setting is 100%, the solver may not be able to find a sequence that is 100% reliable and doesn't exceed the Max Length limit. However, in that scenario, the solver will still try to get as close to the Max Length limit while maintaining the reliability.

**Comment by danielshawnds** [comment]
It's already working well for me.  Incredible response speed.  Thank you so much!
