### ISSUE TITLE
Keeps treating Stroke of Genius as an action

### ISSUE THREAD

**Issue by roswell67** [doxxx/ffxiv-craft-opt-web#164]
It's a trait.. and it keeps trying to activate as an action it, making calculation wrong which breaks the sequence

**Comment by doxxx** [comment]
Stroke of Genius is not an action that can be added to a sequence. It's automatically activated on the second step of the sequence if you have checked the Specialist box for the class.

**Comment by roswell67** [comment]
Yes I understand that, but the solver keeps adding it as a step. I'll post log when it happens again

**Comment by doxxx** [comment]
Thanks that will help a lot.

**Comment by doxxx** [comment]
I think I've found the problem. When setting up the enabled actions for a class, if you use the By Level for a level 70 Specialist or use the All button, it's mistakenly adding Stroke of Genius as an enabled action.

**Comment by doxxx** [comment]
Deployed to beta site. Please force reload and click the By Level button for each of your classes.
