### ISSUE TITLE
Cross-class Action Setup Macro Issue

### ISSUE THREAD

**Issue by Tzevaot** [doxxx/ffxiv-craft-opt-web#167]
This appears to be recent that is happening when creating the Cross-class Action Setup Macros.

The word "on" is added at the end of each skill. Putting this in a macro will not activate the abilities, making us have to remove the word "on" manually for each line.

![capture](https://user-images.githubusercontent.com/30368183/28651041-0cdddc52-7245-11e7-863b-9d48a17de421.JPG)

**Comment by lockheartmac** [comment]
I don't understand this comment. It works for me. My issue is that the cross-class macro doesn't include abilities the class naturally knows which makes these only suited for the currently selected class; instead of suitable for all crafting classes.

**Comment by doxxx** [comment]
When I was informed of the feature in the game, the example I was given had "on" at the end of each action. Does that not work?

**Comment by doxxx** [comment]
The macro is generated for the sequence that you've created, which is for a specific class and recipe, thus it doesn't include those abilities as you mentioned.

**Comment by Tzevaot** [comment]
It appears it works now... My bad. Earlier today it was not assigning the class abilities, I may have just been doing something wrong. 👍 

Sorry. :)

**Comment by lockheartmac** [comment]
@doxxx OIC. I have been using it to create cross-class macros for recipes of the same level/difficulty. I ended up just finding the unique abilities for the sequence and wrote my own ability macro. Still a great tool, thanks!
