### ISSUE TITLE
Macro generation

### ISSUE THREAD

**Issue by landseapants** [doxxx/ffxiv-craft-opt-web#170]
Macro generation not working on -beta

**Comment by csvcrime** [comment]
I am getting the same problem. Macro generation no longer working since July 29, 2017 (roughly).

**Comment by roswell67** [comment]
same problem.

![image](https://user-images.githubusercontent.com/10183897/28748250-a3abfec0-74bb-11e7-9b6f-ca001e08ccac.png)

**Comment by doxxx** [comment]
Please try force reload.
