### ISSUE TITLE
Great Strides is used when no more touches are being lined up.

### ISSUE THREAD

**Issue by Battler624** [doxxx/ffxiv-craft-opt-web#171]
Great Strides only affects the next "touch" ability.

http://i.imgur.com/ZBvJMlM.png

Seed: 1501839863076

Crafter:
  Class: Leatherworker
  Level: 62
  Craftsmanship: 677
  Control: 645
  CP: 382
  Specialist: false

Recipe:
  Level: 260
  Difficulty: 1400
  Durability: 80
  Start Quality: 0
  Max Quality: 9065
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: true
  Algorithm: eaComplex
  Population: 1000
  Generations: 200
  Penalty Weight: 500

No initial sequence provided; seeding with the following heuristic sequence:

Comfort Zone | Inner Quiet | Steady Hand | Basic Touch | Basic Touch | Basic Touch | Basic Touch | Basic Touch | Great Strides | Byregot's Blessing | Master's Mend II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II

Heuristic sequence feasibility:
Progress: true, Durability: true, CP: true, Tricks: true, Reliability: true

**Comment by doxxx** [comment]
Could you be more specific about what the problem is?

**Comment by doxxx** [comment]
@ermad Could you verify whether Great Strides affects only "touch"-named abilities or does it affect all quality increasing abilities, e.g. Byregot's Brow/Blessing/Miracle?

**Comment by Ermad** [comment]
I don't think thats what this issue is reporting. The ability description of Great Sides reads "Doubles efficiency of next Touch action.", and this issue says its being used after all the "Touches" are done being used.

Despite what the ability text says, Great Sides doubles the efficiency of next quality increasing action, not just the next Touch action. Such as Byregot's Brow in the screenshot.

**Comment by doxxx** [comment]
In that case, I think the Solver has determined that using Great Strides before Byregot's Brow is of more benefit than before the earlier touches, especially since Byregot's Brow is powered up by the Inner Quiet stacks from the earlier touches.

**Comment by Battler624** [comment]
Oh, I thought it only affect abilities with touch in the name thus the brow won't work, my bad.
