### ISSUE TITLE
Being able to select food and medicine buffs

### ISSUE THREAD

**Issue by jeanrmarques** [doxxx/ffxiv-craft-opt-web#172]
This is more like a feature request ^^; I know theres the bonus fields for that, but would be nice to have a couple selects for us to be able to choose a medicine and a food buff :)

I wish i was more versed with angular, otherwise i would gladly try to implement that :)

**Comment by doxxx** [comment]
The main issue with this is determining and maintaining a list of the buff items and their values.

**Comment by Ermad** [comment]
The list of buffs should be able be mostly maintained with a lodestone scrapper. Just check all the Culinarian recipes item stats, and add the ones with crafting stats. The few other foods/medicine/buffs can be manually maintained, think are only ~10 atm that aren't from Culinarian.

This is something I was thinking of tackling as well, but I haven't thought of a good way to do the UI for it. Since you would want a dropdown for Food, Medicine, and Misc Buffs (e.g. FC buffs), retain the ability to manually adjust the stats, and be able to see final/initial stats still. The current element for this is quite small for all of that.

**Comment by doxxx** [comment]
One option for the UI is a smaller button that opens a modal (like the Options) which can show a more complex UI for picking buffs. It's unlikely to be changed very frequently so a modal would be acceptable.

**Comment by doxxx** [comment]
We could probably build the freeform bonus fields into the modal as well, simplifying or even removing that whole block from the main UI.

**Comment by Ermad** [comment]
One issue with a modal dialog is that you don't get a benefit off seeing what buffs are active when switching between sequences. Say I have two saved sequences one with Food A and one with Food B, it would be nice when switching between them you can easily see what food is selected for each in the stats element (w/o having to remember the stats for each food).

**Comment by doxxx** [comment]
XIVDB might be an option as well for maintaining the list. For example, Meals with +Control:

http://xivdb.com/?filters=b3JkZXJfZmllbGQ9aWQmb3JkZXJfZGlyZWN0aW9uPWRlc2Mmb25lPWl0ZW1zJmxpbWl0PTYwJnN0cmljdD1vZmYmaXRlbV91aV9jYXRlZ29yeSU3Q2V0PTQ2JnBhZ2U9MSZhdHRyaWJ1dGVzPTcxJTdDZ3QlN0MxJTdDMA==

**Comment by doxxx** [comment]
I've been working (slowly) on a new layout for the status widget, which looks like this:

![image](https://user-images.githubusercontent.com/677940/28982332-6bf5ad48-7923-11e7-91df-2eb4b74a7097.png)

The Durability/Condition block on the left has been removed entirely and the Durability has been added to the bottom line of the middle block. Condition is left out because it changes with each random seed and step-to-step, so showing it is pretty much meaningless.

This leaves the Bonus Stats block floating around aimlessly on the right, which I don't like. I haven't been able to wrangle the CSS to align/flow the two blocks at different viewport sizes decently. Maybe I could replace it with another line at the bottom of the main status block with info about the selected buff(s) and a small edit button?

**Comment by jeanrmarques** [comment]
Ah, yes... didnt think of that... giving it food and medicine includes them all, and not just the ones used for crafting.. you would need to use a full list of both, and somehow filter the ones appropriate for crafting.
Plus, determining how much of the buff would actually apply could be a pain, as its percentage based with a max value it can give

Thanks for the reply tho! I love your tool! :)

**Comment by jeanrmarques** [comment]
Ah, as for UI, my thoughts would be 2 select boxes (one for medicine, which is a new thing since SB, and one for food, since you can have both active)

And it could be something that worked basically instead of that bonus box that is currently there

**Comment by doxxx** [comment]
It does look like XIVDB's API provides the percentage information, so it's not impossible... For example: https://api.xivdb.com/item/19837

**Comment by jeanrmarques** [comment]
would have to check the usere's stats and see if the increase would surpass the max value

for example: user has 100 CP, food gives 10% cp, max 3 cp

and also find a way to filter out all the non craft related food... i guess... based on ""name":"Craftsmanship"," (control and cp too)

**Comment by doxxx** [comment]
The XIVDB API has this section in the Warrior's Stew data:

```json
{
      "id": 70,
      "is_food": 1,
      "is_relative": 70,
      "name": "Craftsmanship",
      "param_patch": 0,
      "percent": 4,
      "percent_hq": 5,
      "stat_patch": 0,
      "value": 42,
      "value_hq": 53
    }
```

That looks like it tells us the percent and max value for both normal and HQ items. Although only relative to level 70, but maybe it can be extrapolated linearly for lower levels?

**Comment by jeanrmarques** [comment]
I think, most food will give the most it can, regardless of the level... since what basically limits the ammount you get is how much you have (because its a % gain)

**Comment by doxxx** [comment]
Cool, that makes life much simpler. :)

**Comment by jeanrmarques** [comment]
As for the simplified UI, i think i had an idea...

Doing the main set up with a modal can save a lot of space, and then on the main UI, then it can have a one liner inside the main box, with a list of active buffs maybe their names

Altho i think the starting progress should still be something on the main UI

**Comment by doxxx** [comment]
The starting quality is determine by the quality of the ingredients, so it's something that has to be entered by hand, right?

**Comment by jeanrmarques** [comment]
Yup! thats why i think it should still be on the main window, as its something you may fiddle with a little more while building your sequence

**Comment by doxxx** [comment]
Current prototype:

![image](https://user-images.githubusercontent.com/677940/28986660-e5ea44b2-7935-11e7-9af2-b97be9d907f0.png)

**Comment by jeanrmarques** [comment]
hah! that looks awesome! nice work! 👍

**Comment by doxxx** [comment]
I'm not happy with the spacing of the bonus status lines on the right but it's proving rather difficult to wrangle the CSS for that particular situation.

I still need to get the actual lists of food and medicine into the app somehow.

**Comment by jeanrmarques** [comment]
you mean the css to have those = signs on that exact spot? I would use some :before magic and absolute position them :F

**Comment by Ermad** [comment]
I can work on making a XIVDB parser to get a list of the food. There is only 3 Medicines (6 with NQ/HQ) so probably can have that just be manual for now.

**Comment by doxxx** [comment]
Sure. You're in a better position to double-check the correctness of that data.

**Comment by doxxx** [comment]
I've got the data for foods and medicines extracted from XIVDB using Ermad's scraper, so I'll be working on integrating that with the new layout today.

**Comment by doxxx** [comment]
Current prototype:

![image](https://user-images.githubusercontent.com/677940/28998850-00d94d04-7a03-11e7-840e-39402a8adc29.png)

You can select food and medicine independently of manually entered bonuses. Both buffs and manually entered bonuses are saved with the synth.

**Comment by doxxx** [comment]
Finally got the sizing to work like I wanted -- handles different window sizes better too:

![image](https://user-images.githubusercontent.com/677940/28999395-1d76ace4-7a13-11e7-9029-0685e4998b87.png)

**Comment by doxxx** [comment]
Deployed to beta site. Please force reload.

**Comment by Ermad** [comment]
Selecting the food/medicine doesn't seem to be using the stats properly.

For instance with CP increasing food, it will increase the the max CP, and the CP shown when you have an empty sequence. But as shown as you add an action to the sequence, it also removes the extra CP given from the food.

**Comment by doxxx** [comment]
Ah, yeah, you're right. I forgot to add the bonuses from the buffs in the simulator and solver.

**Comment by doxxx** [comment]
I've deployed a fix for that to the beta site.

**Comment by jeanrmarques** [comment]
It looks amazing! great job guys! ^^ thank you so much!
