### ISSUE TITLE
Specialty: Reinforce action shows Rapid Synthesis II Tooltip

### ISSUE THREAD

**Issue by h-e-c** [doxxx/ffxiv-craft-opt-web#173]
In some situations withing the Simulator the Specialty: Reinforce action shows Rapid Synthesis II Tooltip
(seem to be doing so only on CRP)

**Comment by doxxx** [comment]
Thanks for spotting that! Fixed on beta site. Please force reload.

**Comment by h-e-c** [comment]
All good now. Thanks for a prompt fix :)
