### ISSUE TITLE
cross-class skills macros not showing 

### ISSUE THREAD

**Issue by clerise** [doxxx/ffxiv-craft-opt-web#176]
When creating macros, the option to see cross-class skill macros sometimes does not show. SS and settings attached.

![untitled](https://user-images.githubusercontent.com/155172/29092958-f5594d6c-7c3c-11e7-9730-2bbcc6c7c279.png)
[settings (1).zip](https://github.com/doxxx/ffxiv-craft-opt-web/files/1209453/settings.1.zip)

**Comment by doxxx** [comment]
Please make sure that you are using http://ffxiv-beta.lokyst.net until we update the main site.

**Comment by clerise** [comment]
Omg! My apologies! Thank you <3
