### ISSUE TITLE
Maker's Mark need to change waiting time from 2 to 3 sec. in macro

### ISSUE THREAD

**Issue by vitamilkyo** [doxxx/ffxiv-craft-opt-web#177]
The buff effect in game finish at 3 sec. If the waiting time is 2 sec., the next action will fail.

**Comment by doxxx** [comment]
Have you tried adjusting the buff wait time in the Options?

**Comment by vitamilkyo** [comment]
I mean, all the buff finish at 2 sec. except this one. There seem to don't have the buff timer to adjust for Maker's Mark.

**Comment by Akurosia** [comment]
Same happaned to me and is only reproduceable on the mentioned skill.
And it has nothing to do with internet delay or slow pc power.
