### ISSUE TITLE
Using difficulty as durability in progress

### ISSUE THREAD

**Issue by DarkNek0** [doxxx/ffxiv-craft-opt-web#183]
Was using the site few days ago just fine, but when I tried yesterday and today, the simulator started to use the crafts difficulty as the progress instead of using durability causing it to want to use really off the wall rotations. Thought it might have been something on my end so tried different computers, all had the same issue on the site.

**Comment by doxxx** [comment]
The site hasn't changed in a few weeks... Was it a specific recipe that caused the problem?

**Comment by DarkNek0** [comment]
Well the last recipe I did that worked fine was Ishgardian Muffin. Went to use it the next day and for some reason it wasn't using the durability value anymore for the progress. Instead it was using the difficulty.

**Comment by doxxx** [comment]
I'm not able to reproduce the issue. Can you post the output from the Execution Log?
