### ISSUE TITLE
Hq 100% fail when solver says reliability 100% and quality 100%

### ISSUE THREAD

**Issue by Melionka** [doxxx/ffxiv-craft-opt-web#184]
As the title says, stats are set, skills too, but it fails despite saying 100% reliability, am i doing something wrong or is it a bug?

thanks

**Comment by doxxx** [comment]
Our modeling of the progress and quality gains is not perfect unfortunately. Could you check the values you get for each action in game and compare them to the simulator log?

**Comment by Melionka** [comment]
I'm not sure how to do this but for example with : 
carpenter LV40
Craftsmanship 183
Control 180
CP268
+ bouilabaisse buff makes my CP 294

To craft Hq walnut lumber and with start quality to 432

Hasty touch failed twice making it 98% hq and thus failed, and sometimes quality is even at like 60-70 when it says reliability 100%

If yu need more infos I'll try to give you

thanks

**Comment by doxxx** [comment]
The Reliability % is the probability that the sequence will complete without running out of durability. The solver tries to maximize this up to the setting in the Options. The HQ % is the probability that a high quality result will be obtained. The solver also tries to maximize this (after reliability).

**Comment by Melionka** [comment]
I understand this, it says 100% HQ and 100% reliability, and I ran the solver multiple times to see if it was the best solve

**Comment by doxxx** [comment]
Could you post the contents of the tabs at the bottom of the Solver screen?

**Comment by Melionka** [comment]
It changed a bit since a did it and i dont recall the rotation completely, as of right now it gives this : 

Seed: 68071, Use Conditions: true

Monte Carlo Example
===================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   40   294      432        0     0     0   180     0     0     0     0     Normal     0
 1 Great Strides                     40   262      432        0     0     0   180     0     0     0     0     Normal     1
 2 Inner Quiet                       40   244      432        0     0     0   180     0     0     0     0     Normal     1
 3 Steady Hand II                    40   219      432        0     0     0   180     0     0     0     0     Normal     1
 4 Standard Touch                    30   187      679        0     1     0   180   247     0   247     0     Normal     1
 5 Hasty Touch                       20   187      791        0     2     0   216   112     0   112     0     Normal     1
 6 Great Strides                     20   155      791        0     2     0   252     0     0     0     0     Normal     1
 7 Waste Not                         20    99      791        0     2     0   252     0     0     0     0       Good     1
 8 Standard Touch                    15    67     1261        0     3     0   252   470     0   313     0     Normal     1
 9 Hasty Touch                       10    67     1261        0     3     0   288     0     0   138     0       Good     0
10 Great Strides                     10    35     1261        0     3     0   288     0     0     0     0     Normal     1
11 Standard Touch                     5     3     1607        0     4     0   288   346     0   346     0     Normal     1
12 Careful Synthesis                  0     3     1607       53     4     0   324     0    53     0     0     Normal     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 4, Wasted Actions: 0

Monte Carlo Result of 1000 runs
===============================
                          DUR    CP      QUA   PRG   HQ%
##     Expected Value:      0     3   1543.6  53.0  96.5
##       Median Value:      0     3   1570.0  53.0 100.0
##          Min Value:      0     3    959.0  53.0  37.0

##       Success Rate:  100.0 %

**Comment by Melionka** [comment]
But since i use this, when it says 100% to both hq and reliability, when it fails (not all the time) it fails because hasty touch fails

**Comment by doxxx** [comment]
When you say “it fails” what do you mean exactly?

**Comment by Melionka** [comment]
The craft it self succeed and is complete, but HQ is not 100% i would say 5 out of 10 crafts, and it happened when hasty touch failed

**Comment by doxxx** [comment]
I think there is a misunderstanding of probabilities here, possibly because there are two “layers” as it were. The first layer is the quality result that the sequence can achieve. This varies quite a lot across multiple runs of the sequence. You can tell by the low value for Monte Carlo minimum result.

The second layer is that the quality value achieved by the sequence is itself a probability of HQ. 

So, according to the Monte Carlo results, the most frequently occurring result is 100% probability of HQ. But on average it will only have a 97% probability of HQ. And the HQ probability can be as low as 37%. 

This is most likely due to the use of Hasty Touch which has a high failure rate.

**Comment by Melionka** [comment]
I see it now, there is a high chance that this is why the differents crafts I tried failed to HQ sometimes !

I'm quite new to crafting, I can I setup the solver to give me a 100% steady hq rate ? Should I remove hasty touch from the available skills ?

**Comment by Melionka** [comment]
I changed a bit my equipment because I lvled up since, without Hasty Touch the sim gives me this now : 

Monte Carlo Result of 1000 runs
===============================
                          DUR    CP      QUA   PRG   HQ%
##     Expected Value:      0     1   1400.2  91.0  99.8
##       Median Value:      0     1   1302.0  91.0 100.0
##          Min Value:      0     1   1139.0  91.0  84.0

##       Success Rate:  100.0 %

How is the median value higher than the expected one ?  Is that a typo of round the 99.8 ?

**Comment by doxxx** [comment]
Expected value is the statistics term more commonly known as average or mean. It is the sum of the quality results divided by the number of Monte Carlo runs. 

Median is the quality result that occurs most frequently.

So there are more 100% quality results than any other result but the sub-100% results pull the average down to 99.8%.

**Comment by Melionka** [comment]
Thanks for clarifying and for this very good tool, especially for beginers, nice work

**Comment by doxxx** [comment]
You’re welcome!
