### ISSUE TITLE
Simulator created a failing macro

### ISSUE THREAD

**Issue by matteo-mosca** [doxxx/ffxiv-craft-opt-web#186]
I was using the simulator to create Enchanted Hardsilver Ink as Alchemist and it created a macro where it uses, at the end of the macro, in this order:

1: Byregot's Blessing (brings durability at 10)
2: Manipulation
3: Rumination (not usable since inner quiet has been removed by BB so durability remains at 10)
4: Careful Synthesis 2 (destroying my recipe since durability is at 10)

The problem here is the usage of Rumination without Inner Quiet active. I think the simulator is missing a check so it doesn't try to use an ability that consumes Inner Quiet if it has already been removed by another ability.

**Comment by doxxx** [comment]
Thanks for the report. I just double-checked the simulation model and it appears to be correct. Byregot's Blessing removes the Inner Quiet effect, and Rumination is only effective if there is one or more stack of Inner Quiet, and also removes Inner Quiet.

There is a random aspect to the way in which the solver generates sequences, so it's possible that the first sequence it comes up with may not be 100% "sane". You should definitely run the solver a few more times to see if it can improve on it.

If you still have the sequence saved, could you load it up in the simulator and then post the contents of the tabs at the bottom of the page?

**Comment by matteo-mosca** [comment]
Hi, sorry I don't have that sequence anymore, but if it happens again I will post it here.

Thanks.
