### ISSUE TITLE
Missing "Heart of the Goldsmith"

### ISSUE THREAD

**Issue by Cptbirdseye** [doxxx/ffxiv-craft-opt-web#187]
Noticed you're missing the level 60 Goldsmithing specialist ability Heart of the Goldsmith which uses 45 CP and increases the chance of material condition becoming Good for 7 steps.

**Comment by doxxx** [comment]
We don't have any of the Heart of the X actions implemented. Their effects are hard to model in a reliable and useful way. Sorry!
