### ISSUE TITLE
Missing recipe

### ISSUE THREAD

**Issue by Amaergen** [doxxx/ffxiv-craft-opt-web#190]
Maybe I'm missing something here, but you seem to be missing the Clothcraft recipe 'Steppe Serge'.

This is what I'm seeing. 
![image](https://user-images.githubusercontent.com/32445924/31064348-863cf8de-a6f8-11e7-97ae-a53da3ec7f98.png)

In the meantime, I've been working around the issue by just using another recipe with the same difficulty/durability

**Comment by Tubben** [comment]
Several Housing recipes are also missing. 
(Lv 61+ Hingan* recipes - all of them).

I did not found an way to add own recipes - which would the easiest way to overcome this. I did not found other recipes with that difficulty/durability (7715/80).

**Comment by AzariahAeroborn** [comment]
@Amaergen When 4.0 was initially released, Steppe Serge was localized as "Dawn Serge" in many places in the English client.  They fixed it in game in 4.06, but it looks like the simulator is still referring to it as Dawn Serge

@Tubben It looks like none of the recipes added with 4.1 are online with the simulator at this time.

**Comment by doxxx** [comment]
Deployed to beta site.
