### ISSUE TITLE
Manipulation II on lvl 62 Leatherworker

### ISSUE THREAD

**Issue by cynicalbaby** [doxxx/ffxiv-craft-opt-web#193]
Optimizer wants me to use Manipulation II (lvl 65 skill) even though I am still lvl 62 and the skill is disabled in the Crafter Attributes. See screenshots:
![ffxiv_manii0](https://user-images.githubusercontent.com/33527691/32626118-b7bf238c-c58e-11e7-960b-6a02d356bc73.jpg)
![ffxiv_manii1](https://user-images.githubusercontent.com/33527691/32626123-bc367172-c58e-11e7-8268-22c3a1cbad75.jpg)

**Comment by doxxx** [comment]
Could you post the contents of execution log in the bottom tabs of the solver?

**Comment by cynicalbaby** [comment]
Hi, sure:
-------------------
Seed: 19483 (220750 on another try)

Crafter:
  Class: Leatherworker
  Level: 62
  Craftsmanship: 964
  Control: 883
  CP: 423
  Specialist: true

Recipe:
  Level: 255
  Difficulty: 558
  Durability: 40
  Start Quality: 0
  Max Quality: 8377
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: true
  Algorithm: eaSimple
  Population: 2500
  Generations: 220
  Penalty Weight: 10000
---------------------

Note: If I don't use Tempura plate food, it gives me Manipulation instead of Manipulation II, but i guess thats due to "not enough CP"!?

**Comment by doxxx** [comment]
Sorry, could you turn on Debug in the Options and post the execution log from the solver again?

**Comment by cynicalbaby** [comment]
yeah, sure ^^

######
Seed: 176876

Crafter:
  Class: Leatherworker
  Level: 62
  Craftsmanship: 964
  Control: 883
  CP: 423
  Specialist: true

Recipe:
  Level: 255
  Difficulty: 558
  Durability: 40
  Start Quality: 0
  Max Quality: 8377
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: true
  Algorithm: eaSimple
  Population: 2500
  Generations: 220
  Penalty Weight: 10000

Crafter Actions:
  0: advancedTouch
  1: basicSynth
  2: basicTouch
  3: brandOfEarth
  4: brandOfFire
  5: brandOfIce
  6: brandOfLightning
  7: brandOfWater
  8: brandOfWind
  9: byregotsBlessing
  10: byregotsBrow
  11: byregotsMiracle
  12: carefulSynthesis
  13: carefulSynthesis2
  14: carefulSynthesis3
  15: comfortZone
  16: flawlessSynthesis
  17: greatStrides
  18: hastyTouch
  19: hastyTouch2
  20: ingenuity
  21: ingenuity2
  22: innerQuiet
  23: innovation
  24: innovativeTouch
  25: makersMark
  26: manipulation
  27: mastersMend
  28: mastersMend2
  29: muscleMemory
  30: nameOfEarth
  31: nameOfFire
  32: nameOfIce
  33: nameOfLightning
  34: nameOfWater
  35: nameOfWind
  36: nymeiasWheel
  37: observe
  38: pieceByPiece
  39: preciseTouch
  40: rapidSynthesis
  41: rumination
  42: satisfaction
  43: standardSynthesis
  44: standardTouch
  45: steadyHand
  46: steadyHand2
  47: trainedHand
  48: tricksOfTheTrade
  49: wasteNot
  50: wasteNot2
  51: whistle

1: best fitness=[8249.0, 818.0, 37.0, 17.0]  pop diversity=[790535.7, 139.9, 109.7, 11.6]
2: best fitness=[8249.0, 818.0, 37.0, 17.0]  pop diversity=[1146910.7, 175.3, 109.9, 7.1]
3: best fitness=[8599.0, 818.0, 5.0, 19.0]  pop diversity=[1085694.9, 173.6, 115.7, 5.2]
4: best fitness=[10156.0, 818.0, 5.0, 18.0]  pop diversity=[1401078.0, 209.8, 119.3, 4.0]
5: best fitness=[10207.6, 818.0, 11.0, 19.0]  pop diversity=[1767605.3, 256.0, 67.8, 2.0]
6: best fitness=[11418.5, 818.0, 6.0, 18.0]  pop diversity=[1986451.7, 282.9, 56.9, 1.6]
7: best fitness=[11832.0, 736.0, 2.0, 20.0]  pop diversity=[2177246.1, 308.8, 58.7, 1.7]
8: best fitness=[11832.0, 736.0, 2.0, 20.0]  pop diversity=[2209967.8, 313.2, 62.6, 1.5]
9: best fitness=[12291.2, 818.0, 0.0, 19.0]  pop diversity=[2314846.8, 327.5, 65.8, 1.4]
10: best fitness=[12558.7, 736.0, 3.0, 20.0]  pop diversity=[2340382.2, 333.3, 70.5, 1.4]
11: best fitness=[12558.7, 736.0, 3.0, 20.0]  pop diversity=[2325757.6, 331.4, 73.2, 1.5]
12: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[2255793.4, 319.7, 72.3, 1.5]
13: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[1994249.0, 281.0, 71.5, 1.5]
14: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[1882206.2, 262.8, 68.8, 1.4]
15: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[1909301.8, 266.5, 65.9, 1.4]
16: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[1898786.5, 265.2, 67.7, 1.4]
17: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[1901550.4, 266.0, 75.1, 1.4]
18: best fitness=[13398.9, 818.0, 11.0, 20.0]  pop diversity=[2149955.8, 303.4, 86.6, 1.4]
19: best fitness=[13398.9, 818.0, 17.0, 21.0]  pop diversity=[2346763.5, 338.2, 95.4, 1.3]
20: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2473861.2, 356.4, 98.6, 1.3]
21: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2393270.0, 346.6, 94.3, 1.3]
22: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2455985.8, 353.8, 97.4, 1.3]
23: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2460773.0, 354.9, 96.9, 1.3]
24: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2493055.3, 357.9, 96.7, 1.3]
25: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2556776.5, 365.1, 93.3, 1.4]
26: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2586291.1, 368.5, 92.3, 1.4]
27: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2610884.0, 370.5, 88.9, 1.3]
28: best fitness=[13611.3, 818.0, 6.0, 20.0]  pop diversity=[2592401.5, 369.0, 90.7, 1.3]
29: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2621241.7, 371.6, 92.5, 1.3]
30: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2566687.5, 364.9, 88.0, 1.3]
31: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2620854.0, 371.7, 89.9, 1.3]
32: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2599852.5, 369.6, 91.1, 1.2]
33: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2610686.0, 370.2, 91.4, 1.3]
34: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2605377.6, 369.5, 90.6, 1.3]
35: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2590729.8, 368.3, 90.0, 1.3]
36: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2615026.2, 370.4, 88.4, 1.2]
37: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2641687.7, 374.0, 90.4, 1.3]
38: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2656580.3, 375.3, 89.8, 1.4]
39: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2630519.8, 372.3, 88.9, 1.3]
40: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2652072.4, 375.2, 89.9, 1.3]
41: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2627994.6, 372.7, 91.2, 1.3]
42: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2652851.4, 375.8, 93.0, 1.3]
43: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2627669.7, 371.8, 90.6, 1.3]
44: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2587330.6, 367.0, 89.3, 1.3]
45: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2645289.6, 374.2, 89.3, 1.2]
46: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2659771.2, 376.1, 90.9, 1.3]
47: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2658594.4, 375.8, 90.2, 1.3]
48: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2643263.4, 373.8, 88.7, 1.3]
49: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2645794.6, 375.2, 88.3, 1.3]
50: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2635985.3, 374.0, 90.3, 1.3]
51: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2667522.5, 377.0, 91.3, 1.3]
52: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2635062.0, 372.3, 92.3, 1.3]
53: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2624006.2, 371.5, 89.1, 1.3]
54: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2639276.2, 374.2, 92.0, 1.3]
55: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2691506.6, 380.1, 92.6, 1.3]
56: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2656000.5, 375.9, 90.1, 1.4]
57: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2648202.2, 374.4, 89.5, 1.3]
58: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2649447.1, 376.0, 89.6, 1.3]
59: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2654196.1, 376.1, 90.2, 1.2]
60: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2682008.0, 378.7, 90.5, 1.3]
61: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2608753.6, 369.3, 92.6, 1.3]
62: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2617737.1, 371.3, 89.5, 1.3]
63: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2621291.3, 371.7, 92.6, 1.3]
64: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2716152.2, 383.1, 93.0, 1.3]
65: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2662272.1, 376.3, 91.7, 1.3]
66: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2629013.2, 371.6, 90.0, 1.3]
67: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2645160.4, 375.1, 87.9, 1.3]
68: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2657046.7, 376.4, 88.8, 1.3]
69: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2680061.4, 378.0, 89.8, 1.3]
70: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2612514.2, 370.1, 91.0, 1.3]
71: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2644289.4, 374.3, 91.6, 1.3]
72: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2616097.7, 371.4, 90.6, 1.3]
73: best fitness=[13611.3, 818.0, 12.0, 21.0]  pop diversity=[2725834.3, 383.8, 92.3, 1.3]
74: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2635444.5, 373.6, 92.4, 1.4]
75: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2612782.4, 370.7, 88.9, 1.2]
76: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2641666.9, 374.5, 91.8, 1.3]
77: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2675138.0, 378.3, 92.9, 1.3]
78: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2629195.3, 372.4, 88.8, 1.3]
79: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2616805.5, 370.4, 90.0, 1.3]
80: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2654939.8, 375.4, 91.1, 1.3]
81: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2600262.4, 369.1, 89.4, 1.3]
82: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2655009.6, 375.9, 89.9, 1.4]
83: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2524655.3, 360.2, 89.9, 1.4]
84: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2481985.4, 354.6, 85.7, 1.3]
85: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2407353.9, 345.8, 87.8, 1.3]
86: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2460875.5, 351.7, 89.7, 1.3]
87: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2427074.4, 348.5, 87.1, 1.3]
88: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2386249.2, 343.5, 84.7, 1.2]
89: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2437372.6, 349.4, 87.5, 1.3]
90: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2384134.2, 343.0, 82.3, 1.3]
91: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2456490.0, 351.8, 88.0, 1.3]
92: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2428477.7, 348.5, 92.6, 1.3]
93: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2440418.6, 349.8, 84.4, 1.3]
94: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2337195.8, 337.6, 87.6, 1.2]
95: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2457792.5, 351.5, 90.0, 1.3]
96: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2401202.6, 345.5, 86.3, 1.3]
97: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2396874.7, 344.0, 83.5, 1.3]
98: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2412402.0, 346.0, 85.6, 1.3]
99: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2400433.4, 344.3, 83.2, 1.3]
100: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2422731.1, 348.6, 87.3, 1.3]
101: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2421826.2, 347.8, 89.9, 1.3]
102: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2435383.6, 349.4, 84.8, 1.3]
103: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2364714.3, 341.0, 87.7, 1.2]
104: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2465265.7, 353.0, 89.2, 1.3]
105: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2342832.9, 338.5, 84.9, 1.3]
106: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2443361.2, 349.9, 85.1, 1.3]
107: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2375270.9, 341.8, 84.7, 1.3]
108: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2453918.7, 350.8, 85.4, 1.3]
109: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2403756.4, 345.9, 86.5, 1.3]
110: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2411848.7, 346.7, 90.6, 1.3]
111: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2431140.0, 349.2, 88.3, 1.3]
112: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2401243.0, 345.5, 87.4, 1.2]
113: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2452430.4, 351.7, 88.7, 1.3]
114: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2355168.2, 339.3, 82.8, 1.3]
115: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2450040.4, 350.8, 84.9, 1.3]
116: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2408902.2, 346.0, 87.4, 1.3]
117: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2459695.5, 352.0, 86.9, 1.3]
118: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2366101.6, 340.8, 83.8, 1.3]
119: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2389561.4, 342.9, 85.0, 1.3]
120: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2427830.4, 349.0, 88.3, 1.3]
121: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2428934.7, 348.8, 88.7, 1.3]
122: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2435136.3, 349.2, 86.3, 1.3]
123: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2397484.8, 344.4, 83.4, 1.3]
124: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2467719.6, 353.5, 85.4, 1.3]
125: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2427425.1, 348.2, 86.3, 1.2]
126: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2462605.6, 352.8, 87.2, 1.3]
127: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2372797.4, 341.5, 84.6, 1.3]
128: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2378362.8, 342.5, 86.5, 1.3]
129: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2410509.1, 346.5, 86.8, 1.2]
130: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2471387.4, 353.3, 88.4, 1.3]
131: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2450549.9, 351.2, 86.4, 1.3]
132: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2419196.0, 347.1, 85.2, 1.3]
133: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2447377.6, 351.7, 85.4, 1.3]
134: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2446458.9, 350.6, 87.5, 1.3]
135: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2470788.2, 353.7, 89.7, 1.3]
136: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2352968.3, 339.2, 85.2, 1.3]
137: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2417714.7, 346.9, 85.1, 1.3]
138: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2428459.9, 348.7, 89.8, 1.2]
139: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2485672.5, 355.2, 88.2, 1.3]
140: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2453518.3, 351.6, 86.2, 1.3]
141: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2397898.4, 344.7, 86.3, 1.3]
142: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2456057.5, 352.8, 88.3, 1.3]
143: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2475316.3, 354.3, 88.5, 1.2]
144: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2450950.7, 351.2, 88.9, 1.3]
145: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2345358.3, 337.8, 83.9, 1.3]
146: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2409223.0, 345.9, 85.6, 1.3]
147: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2433879.0, 349.3, 88.4, 1.3]
148: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2523497.7, 359.7, 91.7, 1.3]
149: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2462150.9, 352.9, 85.9, 1.3]
150: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2364757.1, 341.0, 85.3, 1.3]
151: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2430678.7, 349.9, 89.5, 1.3]
152: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2471717.5, 353.6, 88.2, 1.3]
153: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2444318.8, 350.0, 86.6, 1.3]
154: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2382410.5, 342.9, 83.8, 1.3]
155: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2422035.6, 348.1, 86.9, 1.3]
156: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2385731.7, 343.6, 85.2, 1.3]
157: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2529327.2, 360.7, 89.5, 1.3]
158: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2463728.3, 353.2, 87.5, 1.3]
159: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2385580.6, 343.9, 86.4, 1.3]
160: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2450171.2, 351.9, 88.2, 1.3]
161: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2478230.4, 354.6, 89.1, 1.3]
162: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2454178.8, 351.4, 86.2, 1.3]
163: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2422533.1, 347.1, 84.7, 1.2]
164: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2447301.0, 350.7, 86.9, 1.3]
165: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2402342.9, 345.7, 85.8, 1.3]
166: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2471292.5, 353.2, 89.2, 1.3]
167: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2451080.9, 351.1, 89.6, 1.3]
168: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2398486.4, 345.2, 86.5, 1.3]
169: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2407954.2, 346.6, 88.0, 1.3]
170: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2501015.4, 357.0, 88.7, 1.3]
171: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2440399.6, 349.9, 85.5, 1.3]
172: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2387426.9, 343.0, 84.5, 1.2]
173: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2409760.1, 346.5, 86.1, 1.3]
174: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2396328.5, 344.8, 82.5, 1.3]
175: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2461686.3, 352.5, 90.7, 1.3]
176: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2441724.9, 350.0, 89.1, 1.3]
177: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2443964.8, 350.3, 87.9, 1.3]
178: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2359243.2, 340.3, 84.7, 1.3]
179: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2479202.7, 354.3, 88.9, 1.3]
180: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2379514.4, 343.0, 87.2, 1.3]
181: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2433266.7, 349.0, 84.6, 1.3]
182: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2417217.6, 346.5, 84.9, 1.3]
183: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2415475.1, 347.3, 85.5, 1.3]
184: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2406034.7, 345.4, 85.0, 1.3]
185: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2437126.8, 349.1, 88.0, 1.3]
186: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2441749.6, 350.0, 87.0, 1.3]
187: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2371365.5, 341.9, 86.4, 1.2]
188: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2454347.2, 351.4, 89.4, 1.3]
189: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2400942.3, 345.2, 86.7, 1.3]
190: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2432442.2, 349.1, 85.3, 1.2]
191: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2360166.3, 340.1, 85.3, 1.3]
192: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2460305.1, 352.7, 89.5, 1.3]
193: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2405759.6, 345.7, 85.8, 1.3]
194: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2382666.9, 342.4, 86.6, 1.3]
195: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2449868.3, 351.5, 91.2, 1.3]
196: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2410068.8, 346.3, 84.4, 1.2]
197: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2457015.1, 351.6, 87.8, 1.3]
198: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2357978.3, 339.9, 87.0, 1.3]
199: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2470772.7, 352.9, 86.3, 1.3]
200: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2383837.3, 343.5, 86.7, 1.3]
201: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2486008.3, 355.4, 90.1, 1.3]
202: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2381881.5, 342.7, 83.8, 1.3]
203: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2397916.8, 344.6, 83.3, 1.3]
204: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2415940.0, 347.1, 86.5, 1.3]
205: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2452931.7, 351.4, 85.3, 1.2]
206: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2454559.9, 351.5, 86.0, 1.3]
207: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2389202.1, 343.6, 87.1, 1.3]
208: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2435183.7, 348.9, 85.6, 1.3]
209: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2430710.1, 348.9, 85.8, 1.2]
210: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2469795.4, 354.1, 91.0, 1.4]
211: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2395431.2, 344.3, 84.0, 1.3]
212: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2430606.0, 348.4, 85.0, 1.3]
213: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2397079.2, 344.9, 86.1, 1.3]
214: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2437101.2, 349.1, 84.9, 1.3]
215: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2430036.0, 348.0, 84.8, 1.3]
216: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2395194.7, 344.5, 88.5, 1.3]
217: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2454952.3, 351.1, 85.4, 1.3]
218: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2446765.3, 351.0, 85.2, 1.3]
219: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2437447.7, 349.6, 89.2, 1.4]
220: best fitness=[13874.8, 818.0, 3.0, 20.0]  pop diversity=[2349923.4, 338.5, 81.8, 1.3]
####

The Solver Result was this time this:
![sr](https://user-images.githubusercontent.com/33527691/32689172-b3788fb4-c6df-11e7-8c83-dd8cbd396b09.jpg)

**Comment by doxxx** [comment]
I suspect the bug is that if the initial sequence contains Manipulation II like yours does, the solver retains it because it’s beneficial, even though the action is not enabled. Since it’s not enabled, it won’t add any more into the sequence but that’s not preventing it from using disabled actions that are already in the sequence when it starts. 

Could you try removing or replacing Manipulation II in the initial sequence and see if that fixes the problem?

**Comment by cynicalbaby** [comment]
Yes, you are right. After i removed Manipulation II from the "Initial Guess" i didn't get it again on the solver with the same stats. 

So maybe the solver could just use skills on the "Initial Guess" up to the classes highest level? The "Initial Guess" skills were already pre-equiped. I didn't put them in there.
Or just completely ignore the "Initial Guess" and just let it use the skills that are enabled in the crafter attributes (<-- i thought it works like that already). But ofc i don't know if thats even possible to change in the code ^^

**Comment by doxxx** [comment]
You can edit the initial guess on the Simulator page. Click the Edit button on the right and then click the Clear button to remove all the actions. You can also add actions by clicking them in the table below, or remove individual actions by clicking them in the sequence. You can also drag&drop actions. 

The initial guess is used to give the Solver a starting point from which to try modifications to improve it. If it is empty then the Solver will generate a basic sequence as a starting point. 

You may want to try editing the initial guess to use valid skills only and then see if the Solver can improve it.
