### ISSUE TITLE
Wish:  Copy Solver Result to Initial Guess.

### ISSUE THREAD

**Issue by Tubben** [doxxx/ffxiv-craft-opt-web#195]
Hello.

It's not an issue but an feature request. I am not sure if i am even allowed to write that here. If not, then please ignore that.

How do i work with that so famous Crafting Optimizer: I do an initial guess, hit solver which most of the time makes my initial guess a bit better. Then i edit my initial guess by the solver result, tweak that a bit and solve that again. After a few tweaks, tries and edits i have my combo.

It would be easier, if i could just copy the solver result to the initial guess with an click of an button.

**Comment by doxxx** [comment]
If you use the Edit Result in Simulator button the Solver page, it will copy the Solver result to the Simulator page. If you then hit Solve on the Simulator page, it will use the copied result as the new Initial Guess.
