### ISSUE TITLE
Cross-class Action Setup Macro

### ISSUE THREAD

**Issue by empyreality** [doxxx/ffxiv-craft-opt-web#196]
Could you make the setup macro take ALL cross-class actions used?

E.g. even though I'm using alchemist as the job to make the macro, I'd like the setup macro to include comfort zone inside.

Thanks

**Comment by doxxx** [comment]
I’m not sure what difference this makes? Could you elaborate?

**Comment by Ermad** [comment]
The difference would be so you could use one cross-class action macro for all classes, instead of just the one currently selected by the simulator.

**Comment by doxxx** [comment]
Are there enough cross-class action "slots" to do this?

**Comment by empyreality** [comment]
Oops. Didn't check my email. Anyways for all end game macros (even Makers mark rotations uses 9 total) you'll be using less than 10 cross class actions slots.

**Comment by arthur-conde** [comment]
I would also love this enhancement. Would updoot if possible.

The idea would be you could run a macro that unassigns all cross-role skills, then assigns whatever is needed for the macro.

```
/aaction clear
/aaction "Skill 1" on
etc...
```

**Comment by doxxx** [comment]
So I took a quick stab at this. I added a button to the Crafter Attributes page which pops up a dialog with a macro containing all the actions which are cross-class for the currently selected class. For an Alchemist with all actions enabled, this produces a macro with 27 cross-class actions, which naturally doesn't fit into one macro.

Perhaps I'm misunderstanding the request? How do you envisage this working?

**Comment by Ermad** [comment]
I don't think that was what was asked. Rather if you are doing a synth as say a Blacksmith that contained Ingenuity, it would include Ingenuity the generated cross-class action macro. So they can use the cross-class macro to execute the synth for other classes besides Blacksmith.

**Comment by doxxx** [comment]
So the cross-class macro would include all actions used by the sequence which are class-specific?

**Comment by Ermad** [comment]
Yea, so it doesn't exclude cross-class skills belonging to the currently selected class.

**Comment by doxxx** [comment]
Deployed to beta site. May need to force-reload.
