### ISSUE TITLE
Solver suggest "Name of" and "Brand of" from other classes

### ISSUE THREAD

**Issue by Zweibach** [doxxx/ffxiv-craft-opt-web#197]
Sometimes the solver will suggest the usage of "Name of" and "Brand of" from other classes even when the recipe has no element. In most cases I see it being Lightning, possibly because of WVR being my highest class.
If there's no benefit to wasting cross-class slots on them and the current class has their own unlocked then I see no reason for the solver to suggest another class' name and brand.

**Comment by doxxx** [comment]
It's pretty tricky to eliminate this scenario completely. I suggest just double-checking the Solver's results and replace actions as needed.
