### ISSUE TITLE
The Specialist craft resolver is totally broken.

### ISSUE THREAD

**Issue by hbq0449** [doxxx/ffxiv-craft-opt-web#200]
check the specialist checkbox, try to craft something using specialist skill resulted in some result like this:

Seed: 1512801670757, Use Conditions: false

Monte Carlo Example
===================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   80   378        0        0     0     0   808     0     0     0     0     Normal     0
 1 Inner Quiet                       80   360        0        0     0     0   808     0     0     0     0     Normal     1
 2 Satisfaction                      80   375        0        0     0     0   808     0     0     0     0     Normal     1
 3 Great Strides                     80   343        0        0     0     0   808     0     0     0     0     Normal     1
 4 Innovation                        80   325        0        0     0     0   808     0     0     0     0     Normal     1
 5 Steady Hand II                    80   300        0        0     0     0  1212     0     0     0     0     Normal     1
 6 Patient Touch                     70   294      934        0     2     0  1212   934     0   934     0     Normal     1
 7 Patient Touch                     60   288     1533        0     4     0  1535   599     0   599     0     Normal     1
 8 Satisfaction                      60   303     1533        0     4     0  1454     0     0     0     0     Normal     1
 9 Satisfaction                      60   318     1533        0     4     0  1454     0     0     0     0     Normal     1
10 Prudent Touch                     55   297     2098        0     5     0  1454   565     0   565     0     Normal     1
11 Satisfaction                      55   312     2098        0     5     0  1616     0     0     0     0     Normal     1
12 Satisfaction                      55   327     2098        0     5     0  1616     0     0     0     0     Normal     1
13 Satisfaction                      55   342     2098        0     5     0  1616     0     0     0     0     Normal     1
14 Satisfaction                      55   357     2098        0     5     0  1616     0     0     0     0     Normal     1
15 Satisfaction                      55   372     2098        0     5     0  1616     0     0     0     0     Normal     1
16 Satisfaction                      55   378     2098        0     5     0  1616     0     0     0     0     Normal     1
17 Great Strides                     55   346     2098        0     5     0  1616     0     0     0     0     Normal     1
18 Innovation                        55   328     2098        0     5     0  1616     0     0     0     0     Normal     1
19 Steady Hand II                    55   303     2098        0     5     0  2020     0     0     0     0     Normal     1
20 Patient Touch                     45   297     3717        0     7     0  2020  1619     0  1619     0     Normal     1
21 Prudent Touch                     40   276     4675        0     8     0  2343   958     0   958     0     Normal     1
22 Great Strides                     40   244     4675        0     8     0  2101     0     0     0     0     Normal     1
23 Innovation                        40   226     4675        0     8     0  2101     0     0     0     0     Normal     1
24 Prudent Touch                     35   205     6745        0     9     0  2505  2070     0  2070     0     Normal     1
25 Satisfaction                      35   220     6745        0     9     0  2666     0     0     0     0     Normal     1
26 Great Strides                     35   188     6745        0     9     0  2666     0     0     0     0     Normal     1
27 Satisfaction                      35   203     6745        0     9     0  2262     0     0     0     0     Normal     1
28 Innovation                        35   185     6745        0     9     0  2262     0     0     0     0     Normal     1
29 Trained Hand                      25   169    10086      407    10     0  2666  3341   407  3341     0     Normal     1
30 Satisfaction                      25   184    10086      407    10     0  2828     0     0     0     0     Normal     1
31 Satisfaction                      25   199    10086      407    10     0  2828     0     0     0     0     Normal     1
32 Manipulation                      25   111    10086      407    10     0  2424     0     0     0     0     Normal     1
33 Satisfaction                      35   126    10086      407    10     0  2424     0     0     0     0     Normal     1
34 Satisfaction                      45   141    10086      407    10     0  2424     0     0     0     0     Normal     1
35 Satisfaction                      55   156    10086      407    10     0  2424     0     0     0     0     Normal     1
36 Satisfaction                      55   171    10086      407    10     0  2424     0     0     0     0     Normal     1
37 Satisfaction                      55   186    10086      407    10     0  2424     0     0     0     0     Normal     1
38 Satisfaction                      55   201    10086      407    10     0  2424     0     0     0     0     Normal     1
39 Satisfaction                      55   216    10086      407    10     0  2424     0     0     0     0     Normal     1
40 Satisfaction                      55   231    10086      407    10     0  2424     0     0     0     0     Normal     1
41 Satisfaction                      55   246    10086      407    10     0  2424     0     0     0     0     Normal     1
42 Satisfaction                      55   261    10086      407    10     0  2424     0     0     0     0     Normal     1
43 Satisfaction                      55   276    10086      407    10     0  2424     0     0     0     0     Normal     1
44 Satisfaction                      55   291    10086      407    10     0  2424     0     0     0     0     Normal     1
45 Steady Hand II                    55   266    10086      407    10     0  2424     0     0     0     0     Normal     1
46 Satisfaction                      55   281    10086      407    10     0  2424     0     0     0     0     Normal     1
47 Great Strides                     55   249    10086      407    10     0  2424     0     0     0     0     Normal     1
48 Prudent Touch                     50   228    12079      407    10     0  2424  1993     0  1993     0     Normal     1
49 Great Strides                     50   196    12079      407    10     0  2424     0     0     0     0     Normal     1
50 Prudent Touch                     45   175    14072      407    10     0  2424  1993     0  1993     0     Normal     1
51 Satisfaction                      45   190    14072      407    10     0  2424     0     0     0     0     Normal     1
52 Satisfaction                      45   205    14072      407    10     0  2424     0     0     0     0     Normal     1
53 Satisfaction                      45   220    14072      407    10     0  2424     0     0     0     0     Normal     1
54 Satisfaction                      45   235    14072      407    10     0  2424     0     0     0     0     Normal     1
55 Satisfaction                      45   250    14072      407    10     0  2424     0     0     0     0     Normal     1
56 Great Strides                     45   218    14072      407    10     0  2424     0     0     0     0     Normal     1
57 Satisfaction                      45   233    14072      407    10     0  2424     0     0     0     0     Normal     1
58 Satisfaction                      45   248    14072      407    10     0  2424     0     0     0     0     Normal     1
59 Advanced Touch                    35   200    17062      407    10     0  2424  2990     0  2990     0     Normal     1
60 Manipulation                      35   112    17062      407    10     0  2424     0     0     0     0     Normal     1
61 Satisfaction                      45   127    17062      407    10     0  2424     0     0     0     0     Normal     1
62 Satisfaction                      55   142    17062      407    10     0  2424     0     0     0     0     Normal     1
63 Satisfaction                      65   157    17062      407    10     0  2424     0     0     0     0     Normal     1
64 Satisfaction                      65   172    17062      407    10     0  2424     0     0     0     0     Normal     1
65 Satisfaction                      65   187    17062      407    10     0  2424     0     0     0     0     Normal     1
66 Satisfaction                      65   202    17062      407    10     0  2424     0     0     0     0     Normal     1
67 Great Strides                     65   170    17062      407    10     0  2424     0     0     0     0     Normal     1
68 Steady Hand II                    65   145    17062      407    10     0  2424     0     0     0     0     Normal     1
69 Prudent Touch                     60   124    19055      407    10     0  2424  1993     0  1993     0     Normal     1
70 Satisfaction                      60   139    19055      407    10     0  2424     0     0     0     0     Normal     1
71 Satisfaction                      60   154    19055      407    10     0  2424     0     0     0     0     Normal     1
72 Satisfaction                      60   169    19055      407    10     0  2424     0     0     0     0     Normal     1
73 Satisfaction                      60   184    19055      407    10     0  2424     0     0     0     0     Normal     1
74 Satisfaction                      60   199    19055      407    10     0  2424     0     0     0     0     Normal     1
75 Satisfaction                      60   214    19055      407    10     0  2424     0     0     0     0     Normal     1
76 Satisfaction                      60   229    19055      407    10     0  2424     0     0     0     0     Normal     1
77 Satisfaction                      60   244    19055      407    10     0  2424     0     0     0     0     Normal     1
78 Satisfaction                      60   259    19055      407    10     0  2424     0     0     0     0     Normal     1
79 Great Strides                     60   227    19055      407    10     0  2424     0     0     0     0     Normal     1
80 Steady Hand II                    60   202    19055      407    10     0  2424     0     0     0     0     Normal     1
81 Prudent Touch                     55   181    21048      407    10     0  2424  1993     0  1993     0     Normal     1
82 Satisfaction                      55   196    21048      407    10     0  2424     0     0     0     0     Normal     1
83 Satisfaction                      55   211    21048      407    10     0  2424     0     0     0     0     Normal     1
84 Satisfaction                      55   226    21048      407    10     0  2424     0     0     0     0     Normal     1
85 Satisfaction                      55   241    21048      407    10     0  2424     0     0     0     0     Normal     1
86 Steady Hand II                    55   216    21048      407    10     0  2424     0     0     0     0     Normal     1
87 Satisfaction                      55   231    21048      407    10     0  2424     0     0     0     0     Normal     1
88 Innovation                        55   213    21048      407    10     0  2424     0     0     0     0     Normal     1
89 Satisfaction                      55   228    21048      407    10     0  2828     0     0     0     0     Normal     1
90 Great Strides                     55   196    21048      407    10     0  2828     0     0     0     0     Normal     1
91 Prudent Touch                     50   175    23435      407    10     0  2828  2387     0  2387     0     Normal     1
92 Great Strides                     50   143    23435      407    10     0  2424     0     0     0     0     Normal     1
93 Innovation                        50   125    23435      407    10     0  2424     0     0     0     0     Normal     1
94 Trained Hand                      40   109    27016      814    10     0  2828  3581   407  3581     0     Normal     1
95 Satisfaction                      40   124    27016      814    10     0  2828     0     0     0     0     Normal     1
96 Satisfaction                      40   139    27016      814    10     0  2828     0     0     0     0     Normal     1
97 Satisfaction                      40   154    27016      814    10     0  2424     0     0     0     0     Normal     1
98 Satisfaction                      40   169    27016      814    10     0  2424     0     0     0     0     Normal     1
99 Innovation                        40   151    27016      814    10     0  2424     0     0     0     0     Normal     1
100 Great Strides                     40   119    27016      814    10     0  2828     0     0     0     0     Normal     1
101 Trained Hand                      30   103    30597     1221    10     0  2828  3581   407  3581     0     Normal     1
102 Satisfaction                      30   118    30597     1221    10     0  2828     0     0     0     0     Normal     1
103 Satisfaction                      30   133    30597     1221    10     0  2424     0     0     0     0     Normal     1
104 Satisfaction                      30   148    30597     1221    10     0  2424     0     0     0     0     Normal     1
105 Satisfaction                      30   163    30597     1221    10     0  2424     0     0     0     0     Normal     1
106 Satisfaction                      30   178    30597     1221    10     0  2424     0     0     0     0     Normal     1
107 Satisfaction                      30   193    30597     1221    10     0  2424     0     0     0     0     Normal     1
108 Satisfaction                      30   208    30597     1221    10     0  2424     0     0     0     0     Normal     1
109 Satisfaction                      30   223    30597     1221    10     0  2424     0     0     0     0     Normal     1
110 Great Strides                     30   191    30597     1221    10     0  2424     0     0     0     0     Normal     1
111 Innovation                        30   173    30597     1221    10     0  2424     0     0     0     0     Normal     1
112 Steady Hand II                    30   148    30597     1221    10     0  2828     0     0     0     0     Normal     1
113 Prudent Touch                     25   127    32984     1221    10     0  2828  2387     0  2387     0     Normal     1
114 Satisfaction                      25   142    32984     1221    10     0  2828     0     0     0     0     Normal     1
115 Great Strides                     25   110    32984     1221    10     0  2424     0     0     0     0     Normal     1
116 Innovation                        25    92    32984     1221    10     0  2424     0     0     0     0     Normal     1
117 Byregot's Miracle                 15    82    38953     1221     5     0  2828  5969     0  5969     0     Normal     1
118 Satisfaction                      15    97    38953     1221     5     0  2020     0     0     0     0     Normal     1
119 Satisfaction                      15   112    38953     1221     5     0  2020     0     0     0     0     Normal     1
120 Satisfaction                      15   127    38953     1221     5     0  1616     0     0     0     0     Normal     1
121 Satisfaction                      15   142    38953     1221     5     0  1616     0     0     0     0     Normal     1
122 Satisfaction                      15   157    38953     1221     5     0  1616     0     0     0     0     Normal     1
123 Steady Hand II                    15   132    38953     1221     5     0  1616     0     0     0     0     Normal     1
124 Great Strides                     15   100    38953     1221     5     0  1616     0     0     0     0     Normal     1
125 Innovation                        15    82    38953     1221     5     0  1616     0     0     0     0     Normal     1
126 Prudent Touch                     10    61    40572     1221     6     0  2020  1619     0  1619     0     Normal     1
127 Satisfaction                      10    76    40572     1221     6     0  2182     0     0     0     0     Normal     1
128 Prudent Touch                      5    55    41455     1221     7     0  2182   883     0   883     0     Normal     1
129 Satisfaction                       5    70    41455     1221     7     0  1939     0     0     0     0     Normal     1
130 Satisfaction                       5    85    41455     1221     7     0  1939     0     0     0     0     Normal     1
131 Satisfaction                       5   100    41455     1221     7     0  1939     0     0     0     0     Normal     1
132 Great Strides                      5    68    41455     1221     7     0  1939     0     0     0     0     Normal     1
133 Innovation                         5    50    41455     1221     7     0  1939     0     0     0     0     Normal     1
134 Satisfaction                       5    65    41455     1221     7     0  2343     0     0     0     0     Normal     1
135 Trained Hand                       0    49    44330     1628     8     0  2343  2875   407  2875     0     Normal     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 1, Wasted Actions: 0

Monte Carlo Result of 10000 runs
================================
                          DUR    CP      QUA   PRG   HQ%
##       Success Rate:  100.0 %

Seed: 1512801671152

Crafter:
  Class: Goldsmith
  Level: 69
  Craftsmanship: 882
  Control: 808
  CP: 378
  Specialist: true

Recipe:
  Level: 270
  Difficulty: 1377
  Durability: 80
  Start Quality: 0
  Max Quality: 5741
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: false
  Algorithm: eaComplex
  Population: 10000
  Generations: 300
  Penalty Weight: 10000

No initial sequence provided; seeding with the following heuristic sequence:

Comfort Zone | Inner Quiet | Steady Hand II | Hasty Touch | Manipulation | Master's Mend II | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Hasty Touch | Great Strides | Byregot's Blessing | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II | Careful Synthesis II

Heuristic sequence feasibility:
Progress: false, Durability: false, CP: true, Tricks: true, Reliability: true

**Comment by huang-jy** [comment]
Agreed it is broken it doesn't use Whistle While You Work to get the Whistle stack.

**Comment by doxxx** [comment]
Our support for Whistle While You Work and related abilities is very poor because its very hard to model correctly. Unless somebody can come up with a good model, I don’t think this will change.

**Comment by doxxx** [comment]
Okay, I'll disable it entirely.
