### ISSUE TITLE
Specialist CP

### ISSUE THREAD

**Issue by Tsunayoshi** [doxxx/ffxiv-craft-opt-web#201]
If u are specialist, the simulation start with 15cp more. thats why recipes fail in the end. specialist only higher the max amount but not the start amount of cp.

**Comment by Ermad** [comment]
When the trait procs after the first turn it also increases your current CP by 15. In the simulation it adds 15CP to current/max CP after the first step.

**Comment by Tsunayoshi** [comment]
it dont add current cp just higher max cp ingame

**Comment by Ermad** [comment]
You are incorrect, you do gain current CP. Provide screenshot proof if you believe it doesn’t act this way.

**Comment by Tsunayoshi** [comment]
Ohhhhhh ur right, i was thinking coz the bar is not full it doesnt. but clearly u use CP for the action. omg i am so sry!!
