### ISSUE TITLE
Wrong progress calculation for new crafts

### ISSUE THREAD

**Issue by xNixillis** [doxxx/ffxiv-craft-opt-web#207]
You recently added new crafts in the selection however in terms of progress they seem to be very off in calculating correctly, and by a fairly noticeable margin. One example is a crafting rotation I made that, according to your simulator, showed 1482 craftsmanship. I was told by many people using that rotation that it does not work for the stat setup and in trial and error I manually found the correct value myself. That value ended up being 1511, which is substantially different and very concerning for other people who use your simulator. I was told from long time users of your simulator that your old calculation for progress gain was correct, or at the very least much closer to correct than it is at the moment, and was wondering if you could revert that change? Thank you.

**Comment by doxxx** [comment]
@ermad could you take a look at this?

**Comment by Ermad** [comment]
I have been working a bunch on the crafting equations the past few days in my branch. I am still doing the final testing on it, but it seems to fixed a lot of issues it previously had. 

With regards to your specific issue, I need a bit more information to try to diagnose it. Your crafter stats (level, craftsmanship, control), the recipe your crafting, what value the simulator said you would get, and what you got in game.

**Comment by xNixillis** [comment]
The items in question are mainly the new crafts released in patch 4.2, an item that would be similar would be "Silvergrace Grimoire" as an example. I've tested these crafts in multiple different stat settings to find different values and these were my findings. Unfortunately I did not record the quality gains as I was mainly focused on finding exact progress gain.

Level 70, 1562 Craftsmanship: "Focused Synthesis" - 610 progress gain under "Ingenuity". "Careful Synthesis III" - 373 progress gain under standard conditions.

Level 70, 1563 Craftsmanship: "Focused Synthesis" - 611 progress gain under "Ingenuity". "Careful Synthesis III" - 373 progress gain under standard conditions.

Level 70, 1565 Craftsmanship: "Focused Synthesis" - 611 progress gain under "Ingenuity". "Careful Synthesis III" - 374 progress gain under standard conditions.

Apologies if it's too small a sample size. I did not expect anyone to need the exact numbers so I just tested a few for myself. Apparently it looks like you've changed the calculations for progress to be more accurate, and I hope that my info further helps you in any possible way.

**Comment by doxxx** [comment]
@xNixillis Could you try the beta site again? You may need to force reload the page.

**Comment by xNixillis** [comment]
Thanks, I've tested multiple different values and they seem to be near perfect if not 100% accurate. Quite impressive honestly.

**Comment by doxxx** [comment]
Good job, @ermad! 👍
