### ISSUE TITLE
Solver doesn't like focused synth

### ISSUE THREAD

**Issue by Steven-Biro** [doxxx/ffxiv-craft-opt-web#209]
## Required Information

Class: alc
Level: 70 
Craftsmanship: 1530
Control: 1447
CP: 476
Recipe Name: Grade 3 Reisui of Mind
Recipe Level: lvl 70 3*
Solver Seed: irrelevent
## Expected Behaviour
use initial guess given

## Actual Behaviour
suggest a new rotation that is objectively worse, possible lower reliability and always lower quality

## Steps To Reproduce
the following images show that this affects focused synthesis (possibly focused touch as well), these actions need to follow an observe in order to boost success from 50% to 100%
![28d18b35aea7b0567d8ddbf407240dae](https://user-images.githubusercontent.com/14033941/35822084-1907665c-0a79-11e8-976c-1df8afba3035.png)
![dd79b4dfbba0d9c31a477b51d224c5fa](https://user-images.githubusercontent.com/14033941/35822087-1bf36a1e-0a79-11e8-8ae2-b239eccf0138.png)
![6c5cda563b2788d168da72e3104bbefa](https://user-images.githubusercontent.com/14033941/35822099-22190ac0-0a79-11e8-9f0d-9943b145a9c2.png)

the large population was chosen to illustrate that this is not seed dependent as many different possibilities will be considered with a 100,000 population. the single generation was selected to minimize 
the solver trying to improve on the result, which would mask the bug I am trying to show here.

**Comment by doxxx** [comment]
It looks like the model wasn't tracking the last action correctly, but only for the probabilistic simulation used in the solver. The Monte Carlo simulation was correct.

Thanks for spotting that!

**Comment by doxxx** [comment]
Fix deployed to beta site.

**Comment by Steven-Biro** [comment]
Thank you!
