### ISSUE TITLE
Recasting Steady Hand II before charges are used, and doing some attempts without the buff in same seed. [BUG]

### ISSUE THREAD

**Issue by GGJarose** [doxxx/ffxiv-craft-opt-web#211]
## Required Information

Class: CUL
Level: 69
Craftsmanship: 1117
Control: 930
CP: 354
Recipe Name: Miso soup with Tofu
Recipe Level: 64
Solver Seed: 1518459912362

## Expected Behaviour

Steady Hand skills are used after 5 Steps, (Also things like Hasty Touch 2 are rarely/never used compared to hasty touch 1 despite their drastically increased effectiveness.) 

## Actual Behaviour
Steady Hand buffs are used Before all 5 charges have been Used. Ending in turn waste/CP waste. In this specific seed situation it doesn't matter because it still gains all the uses and the one step isn't missed, but i've had previous strings where it will use 3 charges, then use steady hand again (rank 2 both time) then continue to use non 100% abilities directly after. Wondering why the CP waste?

## Steps To Reproduce

Literally make almost any seed with my current stats/all abilities selected and you'll see the reoccur consistently. Also any recommendations on the calculator itself would be appreciated. Thank you.

**Comment by GGJarose** [comment]
I'm posting another seed created just now where it again repeats this issue, to show it continues to happen. Steady hand II should not be used again until the stacks have been used up!

# Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   80   354        0        0     0     0   921     0     0     0     0     Normal     0
 1 Inner Quiet                       80   336        0        0     0     0   921     0     0     0     0     Normal     1
 2 Steady Hand II                    80   311        0        0     0     0   921     0     0     0     0       Good     1
 3 Patient Touch                     70   305        0        0     0     0   921     0     0   356     0     Normal     0
 4 Patient Touch                     60   299      356        0     2     0   921   356     0   356     0     Normal     1
 5 Steady Hand II                    60   274      356        0     2     0  1289     0     0     0     0     Normal     1
 6 Basic Synthesis                   50   274      356      337     2     0  1289     0   337     0     0     Normal     1
 7 Patient Touch                     40   268      356      337     1     0  1289     0     0   501     0     Normal     0
 8 Manipulation II                   40   172      356      337     1     0  1105     0     0     0     0     Normal     1
 9 Prudent Touch                     40   151      784      337     2     0  1105   428     0   428     0       Good     1
10 Observe                           45   144      784      337     2     0  1289     0     0     0     0     Normal     1
11 Focused Touch                     40   126     1536      337     3     0  1289   752     0   752     0     Normal     1
12 Observe                           45   119     1536      337     3     0  1474     0     0     0     0     Normal     1
13 Focused Touch                     40   101     2402      337     4     0  1474   866     0   866     0       Good     1
14 Observe                           45    94     2402      337     4     0  1658     0     0     0     0     Normal     1
15 Focused Synthesis                 40    89     2402     1011     4     0  1658     0   674     0     0     Normal     1
16 Observe                           45    82     2402     1011     4     0  1658     0     0     0     0     Normal     1
17 Focused Touch                     35    64     3384     1011     5     0  1658   982     0   982     0       Good     1
18 Observe                           35    57     3384     1011     5     0  1842     0     0     0     0     Normal     1
19 Focused Touch                     25    39     4487     1011     6     0  1842  1103     0  1103     0     Normal     1
20 Byregot's Brow                    15    21     6204     1011     0     0  2026  1717     0  1717     0     Normal     1
21 Careful Synthesis III              5    14     6204     1516     0     0   921     0   505     0     0     Normal     1
22 Observe                            5     7     6204     1516     0     0   921     0     0     0     0       Good     1
23 Focused Synthesis                  0     2     6204     2190     0     0   921     0   674     0     0     Normal     1

**Comment by doxxx** [comment]
The number of steps in that sequence which needed the success rate boost of Steady Hand II was greater than 5, so it had to use it twice. Replacing the buff early in these cases is functionally and CP equivalent to waiting for the first buff to wear off.

Remember the Solver tries to find a sequence that results in the best quality. Reducing CP usage is a secondary goal.

**Comment by GGJarose** [comment]
Ah... After looking at the second string I posted you're right, it used 100% Base methods anyways with or without touch. My mistake! Only other points I have then are the calculator not liking to use things like Hasty Touch II - and also your suggestions on settings for optimal calculator output. With the settings I have currently if I reset and start the calculator, i get different results almost every time.

**Comment by GGJarose** [comment]
Also, thank you for following up so quickly! Your tool in it's entirety made me love crafting in FF. Great work!

**Comment by doxxx** [comment]
The Solver is inherently random. That's simply the way genetic algorithms work. You can click the _Use Result in Simulator_ button on the Solver page to "save" the Solver's result and then click _Solve_ again to see if the Solver can improve on that sequence, rather than starting from scratch again.

Something else to consider is that if you have the _Use Conditions_ option turned on, that will affect where the Solver decides to place buffs, since the probability of a Good or Excellent is low at that point in the sequence. You may wish to experiment with turning off that option to see what it produces.

**Comment by GGJarose** [comment]
I'll try with quality off. Thank you!

**Comment by doxxx** [comment]
With regards to Hasty Touch II, I suspect that the Solver considers it weaksauce. ;)

**Comment by GGJarose** [comment]
(so much so that I have told the calc I don't have the ability, to reduce RNG)

**Comment by GGJarose** [comment]
When I have the ability active it will use it in almost every craft 6+~ Times

**Comment by doxxx** [comment]
Hasty Touch II is not free, as compared to Hasty Touch, which can make a big difference in tight CP situations. Since Hasty Touch is free (except for the cost of Steady Hand I/II to improve it's success rate) you can spam it to get significant quality gains vs the CP cost of other quality increasing actions. And, if you have Inner Quiet active, spamming Hasty Touch rapidly increases Control which increases quality gains even further. The only concern is burning through durability, which you'd have to deal with anyway when using other quality-increasing actions.
