### ISSUE TITLE
Error cross skill : Innovation 

### ISSUE THREAD

**Issue by DcVladimir** [doxxx/ffxiv-craft-opt-web#215]
Bugg : 
Innovation is not a skill of carpenter but skill of goldsmith.
The Macro display error message on cross skill execution.
![error_cross_skils](https://user-images.githubusercontent.com/4615328/36620366-eedcec70-18f2-11e8-9c62-3faac685d003.png)

**Comment by doxxx** [comment]
Yeah, the XIVDB tooltip is wrong, but we can't do anything about that. Please report it on the XIVDB website.

We do model it correctly as a Goldsmith ability. You can see the little Goldsmith symbol in the top right corner of the icon.

Could you explain more about the macro error?

**Comment by DcVladimir** [comment]
![image](https://user-images.githubusercontent.com/4615328/36630745-a8c2963a-196b-11e8-9736-4b04b0eb1c98.png)

You can not add Innovation to the list of talents / role actions.

**Comment by doxxx** [comment]
@empyreality @Ermad Is this due to the change I made recently to the way cross-class action setup macros are generated?

**Comment by DcVladimir** [comment]
I reported the bug on the XIVDB website and they solved the problem.
![img_20180226_142739](https://user-images.githubusercontent.com/4615328/36672914-5d9c07c6-1b01-11e8-9f95-bdfc55e1a8ab.png)
![img_20180226_142824](https://user-images.githubusercontent.com/4615328/36672922-6545e7ee-1b01-11e8-8bdc-0891df3cb19f.png)

**Comment by doxxx** [comment]
I've added an option to enable/disable the inclusion of cross-class skills from the current class in the setup macro.

**Comment by empyreality** [comment]
@doxxx Yes, That's an error cause you cannot add innovation as a cross-class skill when you are a goldsmith or byegots as a carpenter. However it does not affect the macro
