### ISSUE TITLE
Not able to calculate rotation for recipes over 60.

### ISSUE THREAD

**Issue by Riddlerat** [doxxx/ffxiv-craft-opt-web#220]
## Required Information

Class: Goldsmith
Level: 61
Craftsmanship: 800
Control: 699
CP:343

When trying to update my characters current abilities and lvl, the level field turns red for anything over 60, it also looks like all the GSM recipes are missing for anything over 60.

**Comment by Riddlerat** [comment]
Soo when I went back to the site it had different information on my GSM (the stats and skills from when I was lvl 59). But I was able to see abilities and and recipes over level 60. I don't know if you have multiple instances of the site running or not but if you do it seems that one might be still running on old code. Anyways it's working for me now.

**Comment by doxxx** [comment]
Your browser may be caching some of the website code. You can forever it to refresh by holding down the shift button (or ctrl + shift buttons on chrome) and click the reload button in the browser.

**Comment by doxxx** [comment]
We also have two websites: ffxiv.lokyst.net which is supposedly the "stable" version but is actually just really out of date, and ffxiv-beta.lokyst.net which is the site which I regularly deploy updates to for testing. Right now, ffxiv-beta is the only one that's actually usable for the current state of the game.
