### ISSUE TITLE
Different calculations between prod/site and github/dev

### ISSUE THREAD

**Issue by annabunches** [doxxx/ffxiv-craft-opt-web#222]
## Required Information

Class: Leatherworker
Level: 53
Craftsmanship: 379
Control: 351
CP: 341
Recipe Name: Wyvern Leather
Recipe Level: 52
Solver Seed: n/a

## Expected Behaviour

Basic Synthesis progress is 100.

## Actual Behaviour

On https://ffxiv.lokyst.net/#/simulator, the calculation is correct. (and matches what is seen in game) If I run the app locally from the `master` branch, the output is 95.

## Steps To Reproduce

1. Run app locally (I used Dockerfile.dev, although it required some changes to get working, look forward to a future pr)
2. Set stats correctly.
3. Go to 'edit' in the simulator, select 'basic synthesis'.
4. Compare with the same actions in prod.

## Notes

I'm working on a CLI-based tool using your code, for just doing basic 'how many CS2s do I need to leave room for'-type calculations. My calculations kept being off, so I decided to run a local version of your site and add logging output. However, it turns out my local version matches my manual calculations! Have you made un-submitted updates to the effective level table, possibly?

**Comment by doxxx** [comment]
The ffxiv.lokyst.net site is rather out of date. The ffxiv-beta.lokyst.net site is up-to-date with the contents of the master branch. However, it has a variety of changes for newer versions of the game that may have affected accuracy.

**Comment by doxxx** [comment]
@ermad FYI

**Comment by annabunches** [comment]
Thanks for the info. I just checked on http://ffxiv-beta.lokyst.net/, and I get the same (correct, matches actual observed values in-game) numbers there that I do at http://ffxiv.lokyst.net/

**Comment by doxxx** [comment]
Phew! :)

The beta site is definitely up to date with master, so I'd guess the source of the discrepancy lies in the way your CLI tool is integrating with our code. Is your project source published somewhere?

**Comment by annabunches** [comment]
I'm not actually *integrating* with your code, I did a fresh implementation based on it. The source isn't posted anywhere yet, no.

Again, though, the weird thing / the bug I'm trying to report is that if I run your site from master, *unmodified*, on my own box, I get different numbers. (and those numbers match the calculations my code is producing, but the two are not talking to each other at all!)

Screenshot attached for elucidation. Note the URL (my local network) and the incorrect progress value (same operation on the real site shows 100)
![bugged_local_instance](https://user-images.githubusercontent.com/238423/37424173-42e4f2f2-2796-11e8-89c8-4c8e1ff671f4.PNG)

**Comment by doxxx** [comment]
Interesting... I'll see if I can reproduce it.

**Comment by annabunches** [comment]
This fails for other recipes too: I tried it with my goldsmith, ffxiv-beta reports 182, locally running instance reports 173, *actual progress* in game is 183. (ffxiv-beta is still off-by-1, but I see another bug already open relating to that, so no big deal there)

**Comment by doxxx** [comment]
So, for your original setup I get 95 progress on both a local version of the site _and_ on ffxiv-beta.lokyst.net but 100 on ffxiv.lokyst.net. If you've used ffxiv-beta.lokyst.net in the past, could you try force-reloading the page? There might be a cached file which is causing it to use old calculations. I've just double-checked that there are no file differences between what's on master and what's on the beta site.

**Comment by doxxx** [comment]
For reference, the `production` branch is what's deployed on ffxiv.lokyst.net. It's about 9 months old at this point. There have been changes in the effect of level difference for crafters below a certain level.

**Comment by doxxx** [comment]
It boils down to the base progress formula for crafters above level 50.

The "production" site uses:

```
baseProgress = 1.834712812e-5 * craftsmanship * craftsmanship + 1.904074773e-1 * craftsmanship + 1.544103837;
```

The "beta" site uses:

```
baseProgress = 1.834712812e-5 * craftsmanship * craftsmanship + 1.904074773e-1 * craftsmanship + 1.544103837;
```

There are some minor differences in the level correction factor but that only results in a ~0.25 variance.

@Ermad Have you been able to get any further with your research into an updated formula?

**Comment by annabunches** [comment]
Yeah, I noticed the polynomial in use for > 50 crafters in the code.

And after force-refreshing I see 95 on `ffxiv-beta`, which lines up with what I *expect* the code to do. Whew.

FWIW, 100 is the "correct" answer in-game for that craft and those stats, so the beta site is wrong for this particular recipe/stat combo. (and several others that I've been inputting throughout the day, all for crafter levels between 53 and 55)

Thanks for explaining what's deployed where, that's helpful for making sense of all this!

**Comment by doxxx** [comment]
The main problem is a lack of data and free time. Neither myself nor lokyst have played FFXIV in years, so we can't collect data of our own. We have to rely on submissions to update the formulae. @Ermad has helped a lot in this regard but has focused mainly on >60. It's possible that we need to introduce another "tier" of formulas to separate 50-60 from 60-70. But without the ability to verify it, I can't really do anything about it.

**Comment by Ermad** [comment]
The main issue in cases like this, is that I only have level 70 crafters. So for issues that only affects lower level crafters I rely on user submitted reports and data.

In this particular case, it does seem like it should be using the original HW base progress formula. When I was doing to the initial implementaion of the Stormblood changes, it seemed like the new Stormblood progress matched for it. There was probably another bug at the time that masked it that has since been fixed.

**Comment by doxxx** [comment]
Ermad's changes have been deployed. You may have to clear your browser cache.
