### ISSUE TITLE
Data not prepopulating correctly

### ISSUE THREAD

**Issue by mechabird** [doxxx/ffxiv-craft-opt-web#224]
![image](https://user-images.githubusercontent.com/37937216/38145421-3048af5c-3417-11e8-8667-54922472511d.png)

If it helps, I noticed if I put a breakpoint on bonusstats.js line 27 it seemed to load the data just fine. After reloading the page a couple of times it loads fine as well.

**Comment by doxxx** [comment]
Could you describe the problem more fully? Does this happen when you first load the site? On reload?

**Comment by mechabird** [comment]
It was the initial load, and it happened for the next couple of refreshes.
Now it consistent ly loads the data.

I put a break point on the line in the picture and it worked as well. If I
had to guess, there is something wonky going on with the promises on the
initial load.

Hooray for asynchronous calls.

Let me know if you need any other info.

**Comment by doxxx** [comment]
Out webhost also does some pretty aggressive caching, which we unfortunately can't control, that sometimes results in some application files being loaded fresh from the site but others loaded from the browser cache.

If something like this happens again, try force reloading -- Ctrl-F5, Ctrl-click or Ctrl-Shift-click the Reload button.
