### ISSUE TITLE
Careful Synthesis II progress incorrect (GSM L56)

### ISSUE THREAD

**Issue by meindratheal** [doxxx/ffxiv-craft-opt-web#227]
# Required Information

Class: Goldsmith
Level: 56
Craftsmanship: 382
Control: 399
CP: 284
Recipe Name: Cloud Mica Whetstone
Recipe Level: 56
Solver Seed: 143056

## Expected Behaviour
Careful Synthesis II progress is 97 in-game. Using the i100 gear except apron (i90), secondary (i43) and jeweller (various). No buffs active

## Actual Behaviour
Simulator progress on http://ffxiv-beta.lokyst.net/#/simulator is 92. The plan generated uses five Careful Synthesis II, but only four are needed

## Steps To Reproduce
Import a macro with just Careful Synthesis II into the simulator and run. The value differs from in-game.

I have seen this happen before too, but can't remember which recipe (though I'm fairly sure that was also a Goldsmith one). Manfested as a "you can't use this action at this time" error in-game when the generated macro tried to Careful Synthesis II after the craft had completed.

Related to #222 maybe?

**Comment by meindratheal** [comment]
Similarly, while crafting a Carnelian (level 57 GSM recipe), Careful Synthesis II gives 89 in-game vs the 84 predicted in the simulator

**Comment by Cptbirdseye** [comment]
Similar issues are also found with Careful Synthesis and Careful Synthesis III.  For example a level 38 blacksmith simulation for cobalt ingots shows the final Careful Synthesis action doing twice the amount than it actually does.

```
Use Conditions: true

Probabilistic Result
====================
 # Action                           DUR    CP     EQUA     EPRG    IQ  WWYW
 0                                   40   268      0.0      0.0   0.0   0.0
 1 Inner Quiet                       40   250      0.0      0.0   0.0   0.0
 2 Waste Not                         40   194      0.0      0.0   0.0   0.0
 3 Careful Synthesis                 35   194      0.0     36.0   0.0   0.0
 4 Steady Hand                       35   172      0.0     36.0   0.0   0.0
 5 Standard Touch                    30   140    142.0     36.0   1.0   0.0
 6 Standard Touch                    25   108    303.0     36.0   2.0   0.0
 7 Standard Touch                    15    76    483.0     36.0   3.0   0.0
 8 Great Strides                     15    44    483.0     36.0   3.0   0.0
 9 Standard Touch                     5    12    883.0     36.0   4.0   0.0
10 Rumination                         5    51    883.0     36.0   0.0   0.0
11 Careful Synthesis                  0    51    883.0     72.0   0.0   0.0
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 3, Wasted Actions: 0
```

**Comment by Ermad** [comment]
This is related to #222, I made the change to fix this to my branch but it wasn't also applied to the main branch yet. For me I get 96, which is off by 1 which I consider acceptable accuracy.

**Comment by Ermad** [comment]
@Cptbirdseye do you have more information about that? Recipe level, crafter stats, etc.

**Comment by Cptbirdseye** [comment]
Recipe level is 42, character level is 38, craftsmanship 180, control 184, cp 268.

**Comment by Ermad** [comment]
What progress gain do you get in game with that recipe using Careful Synthesis?

**Comment by Cptbirdseye** [comment]
Refresh page Ermad, I just added that in the last post.

**Comment by Cptbirdseye** [comment]
Refresh page Ermad, I just added that in the last post.

**Comment by Ermad** [comment]
When I put those stats into the simulator, it does show Careful Syntesis giving 32pts. Are you sure you put in the correct stats and are looking at the right numbers?

**Comment by Cptbirdseye** [comment]
At level 39 Careful Synthesis increases progress by 33.  I'm guessing this increases by 1 for each level until 42 when only 2 Careful Synthesis is required and the above script would then work.

Yes Ermad, that is exactly what is happening.  Careful Synthesis is only doing 32 progress, 32 x 2 is 64, total progress for the synth is 72, therefore it still needs another Careful Synthesis to complete the craft until the crafter level matches that of the craft level.

**Comment by Cptbirdseye** [comment]
With the previous gearset the progress increase is 34 as I expected.

**Comment by Cptbirdseye** [comment]
I'll try and lay it out simple.

Careful Synthesis at level 38 only increases progress by 32.
Cobalt Ingots have 72 progress.
The above simulation shows only 2 Careful Synthesis stages.
32 x 2 = 64
On performing the final step ingame there is still 8 progress remaining, therefore the synthesis fails.

**Comment by Ermad** [comment]
Simulator just simulates the rotation you give it. It is giving accurate progress numbers, if the rotation isn’t giving enough progress then change the rotation

**Comment by Cptbirdseye** [comment]
Then what's the point if the simulator doesn't sim an accurate rotation?  Isn't that the whole point of a simulation?

**Comment by doxxx** [comment]
@Cptbirdseye The 72 you see in the EPRG column there is the _total_ progress so far. Both Careful Synthesis actions have added 36 progress in that sequence.

The simulator will show what a particular sequence will do, with exactly the actions that you give it. If you want to discover a sequence that will complete a synth, use the Solver. You can take the sequence that you have, hit the Solve button on the right and it will find a better sequence that will complete the synth.

**Comment by Cptbirdseye** [comment]
I wasn't talking of the EPRG, I was talking of this:

[http://www.geekgirl101.org/ffxivstuff/72.png](url)

**Comment by doxxx** [comment]
I'm confused. You said:

> For example a level 38 blacksmith simulation for cobalt ingots shows the final Careful Synthesis action doing twice the amount than it actually does.

And quoted a synth log which shows at the end:

    11 Careful Synthesis                  0    51    883.0     72.0   0.0   0.0

What I'm trying to tell you is that the 72 in that line is the TOTAL progress achieved so far in the simulated synth. The Careful Synthesis at step 11 added 36 progress, just like the first one, for a total of 72.

Now, are you saying that in-game, for this synth with the exact same stats as you had in the simulator, Careful Synthesis is NOT adding 36 progress?

**Comment by Cptbirdseye** [comment]
I'm not talking about that at all.  I was saying that the simulator on the final step looked like it was thinking Careful Synthesis was doing 64 instead of 32.  I thought that was the case, but after looking at what happened when I reached level 42 I'm seeing now it's assuming I was already level 42 where Careful Synthesis does 36 and doesn't take into account that it does less when you're lower than level 42.

**Comment by doxxx** [comment]
The simulator doesn't "assume" anything. It does exactly what you tell it to do. You're throwing around a lot of numbers that don't make sense in the context of the information that you've given so far. If the game and the simulator don't agree on the amount of progress provided by an action, please provide a complete example like the first post in this issue.

**Comment by Cptbirdseye** [comment]
-.-

Progress = 0/72 || Durability = 40

Careful Synthesis + Waste Not = +32 progress || -5 durability
Progress 32/72 || Durability = 35

Standard Touch #1 + Waste Not = -5 durability
Progress 32/72 || Durability = 30

Standard Touch #2 + Waste Not = -5 durability
Progress 32/72 || Durability = 25 (Waste Not wears off)

Standard Touch #3 = -10 durability
Progress 32/72 || Durability = 15

Standard Touch #4 = -10 durability
Progress 32/72 || Durability = 5

Careful Synthesis #2 = +32 progress || -10 durability
Progress = 64/72 || Durability = 0

Synth fails

If that's too difficult to understand then I have nothing more to say, I can't make it any more simpler.

**Comment by meindratheal** [comment]
Think @Cptbirdseye is saying that the simulator thinks CSII makes 36 progress, but actually running it makes 32? Which would relate to the original issue

**Comment by doxxx** [comment]
@Cptbirdseye Based on the information you have provided so far (character level 38, craftsmanship 180, control 184, cp 268, Cobalt Ingot), when I plug in your stats and sequence into the Simulator, I get the following:

```
Probabilistic Result
====================
 # Action                           DUR    CP     EQUA     EPRG    IQ  WWYW
 0                                   40   268      0.0      0.0   0.0   0.0
 1 Inner Quiet                       40   250      0.0      0.0   0.0   0.0
 2 Waste Not                         40   194      0.0      0.0   0.0   0.0
 3 Careful Synthesis                 35   194      0.0     32.0   0.0   0.0
 4 Steady Hand                       35   172      0.0     32.0   0.0   0.0
 5 Standard Touch                    30   140    113.0     32.0   1.0   0.0
 6 Standard Touch                    25   108    242.0     32.0   2.0   0.0
 7 Standard Touch                    15    76    386.0     32.0   3.0   0.0
 8 Great Strides                     15    44    386.0     32.0   3.0   0.0
 9 Standard Touch                     5    12    706.0     32.0   4.0   0.0
10 Rumination                         5    51    706.0     32.0   0.0   0.0
11 Careful Synthesis                 -5    51    706.0     64.0   0.0   0.0
```

This is the same Careful Synthesis progress (32 + 32) as the game output you have just provided. I don't see how you could have gotten 36 progress in your original Simulator output (https://github.com/doxxx/ffxiv-craft-opt-web/issues/227#issuecomment-386888662), unless your stats/buffs changed.

If you are still having a problem, please provide a complete example in the format below:

```
## Required Information

Class:
Level:
Craftsmanship:
Control:
CP:
Recipe Name:
Recipe Level:

## Expected Behaviour

(sequence and game output)

## Actual Behavior

(simulator output)
```

**Comment by meindratheal** [comment]
Some more data for you:
CUL, 240 Craftmanship, 272 Control, 295 CP.

At L50, Standard Synthesis was giving 57 progress. Simulator predicted 59
At L51, with no change in equipment, it gave 66. Simulator predicted 63

**Comment by doxxx** [comment]
@meindratheal Same recipe at both crafter levels?

**Comment by meindratheal** [comment]
Yep, thought I'd try my hand at collectible crafting, was making Baked Onion Soup. Didn't realise there'd be such a jump in progress values, but also weird that one was an overestimate and the other was an underestimate.

Brand of X must have similar accuracy issues. I don't have the full numbers to hand (it's 4am and I should probably sleep), but using the following rotation, after finishing Macro 1 my actual progress was 500, compared to the 478 projected by the solver.

```
/ac "Inner Quiet" <wait.2>
/ac "Hasty Touch" <wait.3>
/ac "Waste Not II" <wait.2>
/ac "Name of Lightning" <wait.2>
/ac "Ingenuity" <wait.2>
/ac "Steady Hand" <wait.2>
/ac "Brand of Lightning" <wait.3>
/ac "Brand of Lightning" <wait.3>
/ac "Brand of Lightning" <wait.3>
/ac "Hasty Touch" <wait.3>
/ac "Hasty Touch" <wait.3>
/ac "Ingenuity" <wait.2>
/ac "Steady Hand II" <wait.2>
/ac "Basic Touch" <wait.3>
/echo Macro #1 complete <se.1>

/ac "Hasty Touch" <wait.3>
/ac "Hasty Touch" <wait.3>
/ac "Byregot's Brow" <wait.3>
/ac "Standard Synthesis" <wait.3>
/echo Macro #2 complete <se.14>
```

```
Seed: 132510, Use Conditions: true

Monte Carlo Example
===================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   80   295        0        0     0     0   272     0     0     0     0     Normal     0
 1 Inner Quiet                       80   277        0        0     0     0   272     0     0     0     0       Good     1
 2 Hasty Touch                       70   277      143        0     1     0   272   143     0    95     0     Normal     1
 3 Waste Not II                      70   179      143        0     1     0   326     0     0     0     0     Normal     1
 4 Name of Lightning                 70   164      143        0     1     0   326     0     0     0     0       Good     1
 5 Ingenuity                         70   140      143        0     1     0   326     0     0     0     0     Normal     1
 6 Steady Hand                       70   118      143        0     1     0   326     0     0     0     0     Normal     1
 7 Brand of Lightning                65   112      143      214     1     0   326     0   214     0     0       Good     1
 8 Brand of Lightning                60   106      143      368     1     0   326     0   154     0     0     Normal     1
 9 Brand of Lightning                55   100      143      478     1     0   326     0   110     0     0     Normal     1
10 Hasty Touch                       50   100      290      478     2     0   326   147     0   147     0       Good     1
11 Hasty Touch                       45   100      477      478     3     0   381   187     0   125     0     Normal     1
12 Ingenuity                         45    76      477      478     3     0   435     0     0     0     0     Normal     1
13 Steady Hand II                    45    51      477      478     3     0   435     0     0     0     0     Normal     1
14 Basic Touch                       35    33      663      478     4     0   435   186     0   186     0     Normal     1
15 Hasty Touch                       25    33      870      478     5     0   490   207     0   207     0     Normal     1
16 Hasty Touch                       15    33     1097      478     6     0   544   227     0   227     0     Normal     1
17 Byregot's Brow                     5    15     1617      478     0     0   598   520     0   520     0     Normal     1
18 Standard Synthesis                 0     0     1617      541     0     0   272     0    63     0     0     Normal     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 4, Wasted Actions: 0

Monte Carlo Result of 1000 runs
===============================
                          DUR    CP      QUA   PRG   HQ%
##     Expected Value:      0     0   1291.2 541.0   6.6
##       Median Value:      0     0   1267.0 541.0   7.0
##          Min Value:      0     0    362.0 541.0   3.0

##       Success Rate:  100.0 %
```

**Comment by meindratheal** [comment]
I'll try and get some more numbers tomorrow. My CUL is now L52, so may be able to get the numbers on levels from there on (materials permitting)

**Comment by mihawk90** [comment]
Not sure if and how that helps you, but I just got one more case (using the solver).

```
Seed: 213272, Use Conditions: true
Recipe: L265 80D 1684/9752, Class: L60 Alchemist, Specialist: true, Craftsmanship: 660, Control: 570, CP: 329

Monte Carlo Example
===================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   80   329        0        0     0     0   570     0     0     0     0     Normal     0
 1 Comfort Zone                      80   263        0        0     0     0   570     0     0     0     0     Normal     1
 2 Inner Quiet                       80   253        0        0     0     0   570     0     0     0     0     Normal     1
 3 Steady Hand II                    80   236        0        0     0     0   570     0     0     0     0       Good     1
 4 Hasty Touch                       70   244      169        0     1     0   570   169     0   112     0     Normal     1
 5 Manipulation                      70   164      169        0     1     0   684     0     0     0     0     Normal     1
 6 Ingenuity II                      80   140      169        0     1     0   684     0     0     0     0     Normal     1
 7 Hasty Touch                       80   148      169        0     1     0   684     0     0   200     0     Normal     0
 8 Hasty Touch                       80   156      369        0     2     0   684   200     0   200     0  Excellent     1
 9 Careful Synthesis II              70   164      369      147     2     0   798     0   147     0     0       Poor     1
10 Careful Synthesis II              60   172      369      294     2     0   798     0   147     0     0     Normal     1
11 Byregot's Brow                    50   162      762      294     0     0   798   393     0   393     0     Normal     1
12 Careful Synthesis II              40   162      762      421     0     0   570     0   127     0     0       Good     1
13 Careful Synthesis II              30   162      762      548     0     0   570     0   127     0     0     Normal     1
14 Careful Synthesis II              20   162      762      675     0     0   570     0   127     0     0     Normal     1
15 Master's Mend II                  80     2      762      675     0     0   570     0     0     0     0     Normal     1
16 Careful Synthesis II              70     2      762      802     0     0   570     0   127     0     0     Normal     1
17 Careful Synthesis II              60     2      762      929     0     0   570     0   127     0     0     Normal     1
18 Careful Synthesis II              50     2      762     1056     0     0   570     0   127     0     0     Normal     1
19 Careful Synthesis II              40     2      762     1183     0     0   570     0   127     0     0     Normal     1
20 Careful Synthesis II              30     2      762     1310     0     0   570     0   127     0     0       Good     1
21 Careful Synthesis II              20     2      762     1437     0     0   570     0   127     0     0     Normal     1
22 Careful Synthesis II              10     2      762     1564     0     0   570     0   127     0     0     Normal     1
23 Careful Synthesis II               0     2      762     1691     0     0   570     0   127     0     0     Normal     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 5, Wasted Actions: 0
```

This is crafting Potent Spiritbond Potion. It finishes 3 Careful Synthesis II earlier.

I already double-checked the stats because that was my first idea:
![image](https://user-images.githubusercontent.com/556162/39817814-7acf7432-539f-11e8-8f75-b44029a34cc3.png)

Also according to combat log ingame:
```
You use Careful Synthesis II  Success!
   Progress increases by 163.
   Durability decreases by 10.
```

I think BPRG is the progress for that step(?), so that's off by quite a lot.

**Comment by meindratheal** [comment]
Done a little more testing today. Numbers for Brand of X were 229, 160 and 111 (compared to 217, 155 and 111 on the simulator). This was consistent between levels

Careful Synthesis II changes between levels still. Equipment unchanged
L53: 76 progress (72 on simulator)
L54: 80 progress (75 on simulator)
L55: 83 progress (79 on simulator)

**Comment by doxxx** [comment]
BPRG is the base progress for that class level, recipe level and craftsmanship, before any temporary effects are applied. I don't there is a column for the actual progress added, just the column that tracks the total so far.

**Comment by doxxx** [comment]
Hopefully this is fixed by Ermad's latest PR.

**Comment by doxxx** [comment]
Ermad's changes have been deployed. You may have to clear your browser cache.

**Comment by mihawk90** [comment]
Calculation still seems off:

```
Seed: 1526692745937, Use Conditions: true
Recipe: L115 40D 169/3951, Class: L50 Carpenter, Specialist: false, Craftsmanship: 276, Control: 304, CP: 306

Monte Carlo Result of 500 runs
==============================
                          DUR    CP      QUA   PRG   HQ%
##     Expected Value:      0     1   3019.4 171.0  57.8
##       Median Value:      0     1   3100.0 171.0  68.0
##          Min Value:      0     1   2195.0 171.0  17.0
##          Max Value:      0     1   4997.0 171.0 100.0

##       Success Rate:  100.0 %

Monte Carlo Random Example
==========================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   40   306     1975        0     0     0   304     0     0     0     0     Normal     0
 1 Inner Quiet                       40   288     1975        0     0     0   304     0     0     0     0       Good     1
 2 Careful Synthesis II              30   288     1975       54     0     0   304     0    54     0     0     Normal     1
 3 Comfort Zone                      30   222     1975       54     0     0   304     0     0     0     0     Normal     1
 4 Hasty Touch                       20   230     2044       54     1     0   304    69     0    69     0     Normal     1
 5 Steady Hand II                    20   213     2044       54     1     0   365     0     0     0     0     Normal     1
 6 Basic Touch                       10   203     2124       54     2     0   365    80     0    80     0     Normal     1
 7 Great Strides                     10   179     2124       54     2     0   426     0     0     0     0     Normal     1
 8 Manipulation                      10    99     2124       54     2     0   426     0     0     0     0     Normal     1
 9 Ingenuity II                      20    75     2124       54     2     0   426     0     0     0     0       Good     1
10 Standard Touch                    20    51     2640       54     3     0   426   516     0   344     0     Normal     1
11 Great Strides                     30    27     2640       54     3     0   486     0     0     0     0     Normal     1
12 Innovation                        30    17     2640       54     3     0   486     0     0     0     0       Good     1
13 Careful Synthesis II              20    25     2640      117     3     0   638     0    63     0     0     Normal     1
14 Byregot's Blessing                10     1     3272      117     0     0   638   632     0   632     0     Normal     1
15 Careful Synthesis II               0     1     3272      171     0     0   456     0    54     0     0       Good     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 7, Wasted Actions: 0
```

Ingame Chatlog:
```
You begin synthesizing a length of cedar lumber.
You remove the following from your bag:
3 wind crystals
5 cedar logs 
You use Inner Quiet.
   You gain the effect of Inner Quiet.
You use Careful Synthesis II  Success!
   Progress increases by 52.
   Durability decreases by 10.
You use Comfort Zone.
   You gain the effect of Comfort Zone.
You use Hasty Touch  Failure!
   Durability decreases by 10.
You use Steady Hand II.
   You gain the effect of Steady Hand II.
You gain the effect of Inner Quiet.
You use Basic Touch  Success!
   Quality increases by 67.
   Durability decreases by 10.
You use Great Strides.
   You gain the effect of Great Strides.
You use Manipulation.
   You gain the effect of Manipulation.
You use Ingenuity II.
   You gain the effect of Ingenuity II.
You gain the effect of Inner Quiet.
You use Standard Touch  Success!
   Quality increases by 309.
   Durability decreases by 10.
You lose the effect of Great Strides.
You lose the effect of Steady Hand II.
You use Great Strides.
   You gain the effect of Great Strides.
You lose the effect of Manipulation.
You use Innovation.
   You gain the effect of Innovation.
You use Careful Synthesis II  Success!
   Progress increases by 63.
   Durability decreases by 10.
You lose the effect of Comfort Zone.
You use Byregot's Blessing  Success!
   Quality increases by 772.
   Durability decreases by 10.
You lose the effect of Inner Quiet.
You lose the effect of Great Strides.
You lose the effect of Ingenuity II.
You use Careful Synthesis II  Success!
   Progress increases by 52.
   Durability decreases by 10.
Your synthesis fails!
```

Seems like while Ingenuity II was active the calculation was correct (both 63), but on the real recipe level (51) it is off by 2.
