### ISSUE TITLE
Problem with any execution

### ISSUE THREAD

**Issue by Karakuro** [doxxx/ffxiv-craft-opt-web#228]
## Required Information

Class: Leatherworker
Level: 56
Craftsmanship: 545
Control: 492
CP: 372
Recipe Name:   Dragonskin Wristbands
Recipe Level: 58
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
When adding an action in the "Edit..." mode, the bars should alter accordingly
(Example: Standard Synthesis progress is 42)

## Actual Behaviour
Nothing works and shows the following error: 

"undefined

Error: TypeError: this.logOutput.write is not a function"

(Example: Standard Synthesis progress is 38)

## Steps To Reproduce
Do literally anything in "Edit..." mode
(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)
![image](https://user-images.githubusercontent.com/18720159/39780458-a07412d0-530c-11e8-97f6-db7b3541363d.png)

**Comment by doxxx** [comment]
Please try clearing your browser cache.

**Comment by Karakuro** [comment]
I thought it was enough with ctrl+F5, but i've just tried it from another pc and the problem's gone, so i'll try to force browser cache clean before retrying on the first pc. 
Sorry for the false alert.

**Comment by doxxx** [comment]
No worries. I've made some adjustments to the caching configuration, which should hopefully improve this in the future.
