### ISSUE TITLE
Missing Recipes 4.3

### ISSUE THREAD

**Issue by MrFluffums** [doxxx/ffxiv-craft-opt-web#231]
## Required Information

Class: Any
Level: 58-70

In patch 4.3, new recipes have been added. Notably, there are Namazu and Custom Deliveries which are not currently in the database. I've logged Custom Deliveries below, but there are additional Masterbook 6 and possibly Specialist recipes added (recipe list unavailable in patch notes).

Recipe Name: Gyr Abanian Remedy Components
Recipe Level: 62

Recipe Name: Gyr Abanian Remedies
Recipe Level: 62

Recipe Name: Harpoon Components
Recipe Level: 62

Recipe Name: Anti-shark Harpoon
Recipe Level:  62

Recipe Name: Cold-weather Gear Components
Recipe Level:  63

Recipe Name: Coerthan Cold-weather Gear
Recipe Level: 63

Recipe Name: Sui-no-Sato Special Components
Recipe Level: 63

Recipe Name: Sui-no-Sato Special
Recipe Level: 63

Recipe Name: Cloud Pearl Components
Recipe Level: 64

Recipe Name: Cloud Pearl
Recipe Level: 64

**Comment by Ronivan2** [comment]
Any idea when they will implement the 4.3 new recipes in the simulator?

**Comment by MrFluffums** [comment]
No idea, that's why I opened this issue. I wasn't sure if they were aware there were new recipes or not.

**Comment by doxxx** [comment]
I'll scrape the Lodestone again to see if they've added them.

**Comment by doxxx** [comment]
Deployed to the beta site.
