### ISSUE TITLE
2.5 star crafting stats incorrect as of 4.3

### ISSUE THREAD

**Issue by TheNuclei** [doxxx/ffxiv-craft-opt-web#232]
These were what I could find in the Master Recipes (5) sections on all classes. There may be more, but I can't check yet.

## Equipment

**Ala Mhigan Turban of Crafting:**
In Sim - 6377 Diff, 28506 Quality
In Game - 3188 Diff, 22171 Quality

**Ala Mhigan Turban of Gathering:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Bottoms of Crafting:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Bottoms of Gathering:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Doublet of Crafting:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Doublet of Gathering:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Gloves of Crafting:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Gloves of Gathering:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Shoes of Crafting:**
Sim - 6377/28506
Game - 3188/22171

**Ala Mhigan Shoes of Gathering:**
Sim - 6377/28506
Game - 3188/22171

**All of the Ala Mhigan Main Hand Tools appear to follow this same pattern.**

## Sub-Materials

**Ala Mhigan Fiber**
Sim - 6377/28506
Game - 2125/17420

**Snailfish Oil**
Sim - 6388/28506
Game - 2125/17420

**Comment by MrFluffums** [comment]
These were reduced in the most recent patch (4.3) and the simulator is still missing 4.3 recipes, so I think it just hasn't been updated.

**Comment by doxxx** [comment]
Deployed to the beta site.
