### ISSUE TITLE
Lv 70 4* simulation estimate?

### ISSUE THREAD

**Issue by pkminer30** [doxxx/ffxiv-craft-opt-web#235]
## Required Information

Class: blacksmith
Level: 70
Craftsmanship: 1740
Control: 1738
CP: 493
Recipe Name: 4* test
Recipe Level: 70 4*
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
Lower Quality and Progress than required to complete
(Example: Standard Synthesis progress is 42)

## Actual Behaviour
Same Results as 3*
(Example: Standard Synthesis progress is 38)

## Steps To Reproduce
Make new item with 4 instead of 3 in the json.
(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

Is it possible to get a rough simulation for 4* crafts before 4* crafts are available?

**Comment by doxxx** [comment]
Without knowing what the effective level for 70 4* recipes is, it would only be a guess.

Level 70 was effectively 290, 70 1* -> 300, 70 2* -> 320, 70 3* -> 350. So if it follows the pattern, I would guess that 70 4* is 390...

**Comment by doxxx** [comment]
However, there's all the other level-related stuff like progress and quality penalities, Ing1/Ing2 effect, etc. that can only be determine once actual recipes are available for testing.

IMO it wouldn't produce useful information.

**Comment by pkminer30** [comment]
how could i make a false entry to alter this so that i can make a rough guess at this?
