### ISSUE TITLE
Constantly using more CP than given

### ISSUE THREAD

**Issue by Phyore** [doxxx/ffxiv-craft-opt-web#237]
## Required Information

Class: WVR
Level: 70 
Craftsmanship:1143
Control:1184
CP: 400
Food: Baked Onion Soup
Recipe Name: Twinsilk Apron
Recipe Level: 69
Solver Seed: 78934

## Expected Behaviour

Solver uses stats given to generate a macro

## Actual Behaviour

For some reason seems to increase the amount of CP I have over the maximum. It seems to calculate the CP used by Comfirt Zone incorrectly. 438 (start) - 66 + 8 = 372 and not 387

## Steps To Reproduce

Enter above stats, click solve.
![image](https://user-images.githubusercontent.com/2222368/41983589-7f9f5f88-7a26-11e8-8012-c68b9817fda9.png)

**Comment by doxxx** [comment]
Do you have Specialist checked?

**Comment by Phyore** [comment]
I do yep, forgot to add that into the starting post (Was thinking did I add that last night)

**Comment by doxxx** [comment]
That automatically adds 15 cp at the start.

**Comment by Phyore** [comment]
Why is that though? I ticked the specialist in the settings. But when you start the craft it doesn't give you any additional CP in game.

**Comment by doxxx** [comment]
Supposedly it’s a passive but it might be quest related. I think @ermad can
give a better explanation.

**Comment by Phyore** [comment]
Stroke of Genius - I see it, It looks like a LV. 70 trait (Which I think maybe a quest - I haven't done) Could we perhaps get a tobble for this in the settings?

**Comment by doxxx** [comment]
Right now the only toggle is the Specialist checkbox.

**Comment by doxxx** [comment]
I've added a description for the checkbox on the attributes page as suggested.
