### ISSUE TITLE
[REQ] Add option to slow down the solver to reduce CPU load

### ISSUE THREAD

**Issue by glek** [doxxx/ffxiv-craft-opt-web#238]
At present the web worker that runs the solver routines runs as fast as it can. This is great for most use cases. I can think of some use cases where this is not ideal, though. My particular use case is that it is presently 30+ degrees Celsius outside and my house lacks air conditioning, so having an option to slow down the web worker to thus reduce CPU load and operating temperatures would be nice.

**Comment by doxxx** [comment]
I'm surprised it has that much effect. It's single-threaded, albeit in the background, so I wouldn't have expected it to rev the CPU up that much.

That said, it would be pretty hard to slow it down without utterly crippling it. I don't have fine control over the timing.

Sorry :)

**Comment by glek** [comment]
Fair enough, though it raises my CPU temperature by 20 degrees Celsius over idle. I might fork the repo and see if I can do it myself for my own use.

**Comment by doxxx** [comment]
If you come up with a way to do it, I'll accept a PR.
