### ISSUE TITLE
[Suggestion] Add Recipe name display to solver page

### ISSUE THREAD

**Issue by ShammyLevva** [doxxx/ffxiv-craft-opt-web#241]
## Required Information

Class: Any
Level: Any
Craftsmanship: Any
Control: Any
CP: Any
Recipe Name: Any
Recipe Level: Any
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
See on Solver page what the recipe name is

## Actual Behaviour
No info on solver page what the recipe name is

## Steps To Reproduce
Solve any recipe.

A suggestion to add the recipe name display to solver page. When crafting loads of items and having to do intermediate steps. It can sometimes be a pain to recall what recipe you just asked it to solve. Switching away forgets the solution so a simple adding of the text name of the recipe to the solver page.

eg: 60 Leatherworker - Gagna Leather

**Comment by doxxx** [comment]
Switching away should not be forgetting the solution, but your suggestion makes sense nonetheless.

**Comment by doxxx** [comment]
I added the recipe selector to the top of the Solver page, and move the Solver action buttons down closer to the Solver result sequence.

Deployed to the beta site.

**Comment by ShammyLevva** [comment]
Thanks for the update looks great. By "switching away" I meant changing tabs WITHIN the app eg: clicking Simulator to go back to see the name of the thing I was creating.

**Comment by doxxx** [comment]
Yeah, I tried that myself and it was remembering the solution that the Solver found when I switched back and forth between the Simulator and Solver tabs. There must be some specific combination of circumstances that are making it forget. If you can figure it out, please let me know.

**Comment by ShammyLevva** [comment]
No problem will do. I'm a developer myself so will attempt to provide diagnostics if I can reproduce again. It's not happened since the update :) so maybe fixed.
