### ISSUE TITLE
Minor translation error(Korean)

### ISSUE THREAD

**Issue by P17seongbin** [doxxx/ffxiv-craft-opt-web#243]
while I use your tool, I found a minor translation error.
In macro, Brand / Name of ice is translated into '물의 인장 / 예술'
but in  'Brand / Name of ice' should be translated into '얼음의 인장 / 예술'

Brand / Name of water is translated correctly.

Thank you for reading this report :)

and also thank you for making such a wonderful tool! (Sorry for my bad English)

**Comment by doxxx** [comment]
@RyuaNerin

**Comment by doxxx** [comment]
Deployed to beta website.
