### ISSUE TITLE
Improve layout of sequence editor

### ISSUE THREAD

**Issue by doxxx** [doxxx/ffxiv-craft-opt-web#25]
The sequence editor takes up too much vertical space and since it cannot be scrolled, for some users the bottom of the dialog may not be visible.

Suggestions:

* Remove "Available Actions" and "Sequence" headings
* Move status display in between actions table and sequence?
* Compress other whitespace?
* Change sequence max height before scrolling to just two rows.

**Comment by lokyst** [comment]
Obsolete since implementing Multi-Page layout.
