### ISSUE TITLE
new 4* Recipes are level 380, not 390

### ISSUE THREAD

**Issue by Humseu** [doxxx/ffxiv-craft-opt-web#251]
All 4* recipes are currently incorrect. I am assuming this is because they are 380, not 390.

Quality amounts are shown to be much lower then they actually are in game.
Progress also has issues, however, in some cases its been shown to be higher then it actually is in game which doesn't make intuitive sense. If progress still has issues afterward I will look to give more specific examples.

**Comment by Humseu** [comment]
Someone else seems to have comment a confirmation of 380 at the bottom here: https://github.com/doxxx/ffxiv-craft-opt-web/issues/247

Also, it is likely related to: https://github.com/doxxx/ffxiv-craft-opt-web/issues/248
Presumably they were assuming ingenuity was the problem rather then the item data itself.

A friend of mine can also confirm he has the same issues (Actually trying to get get it fixed for his sake).

Completely understand the caution, and a big thanks for maintaining this.

**Comment by doxxx** [comment]
Okay, I'll update the recipe database.
