### ISSUE TITLE
Inner Quiet Only Uses 3CP During Sim

### ISSUE THREAD

**Issue by nhjansen** [doxxx/ffxiv-craft-opt-web#258]
## Required Information

Class: CRP
Level: 70
Craftsmanship: 1294
Control: 1168
CP: 442
Recipe Name: Coerthan Cold Weather Gear
Recipe Level: 63
Solver Seed: 194308

## Expected Behaviour

Inner Quiet should subtract 18 CP from stack

## Actual Behaviour

Inner Quiet subtracts 3 CP from stack, causing failure of synthesis when macro is used

<img width="619" alt="screenshot 2019-01-06 at 14 52 54" src="https://user-images.githubusercontent.com/17524303/50737608-6c03e400-11c3-11e9-90fd-02350777a127.png">

## Steps To Reproduce

(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

**Comment by doxxx** [comment]
You probably have the Specialist attribute checked.
