### ISSUE TITLE
Database update reminder. (4.5 hit a few days ago.)

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#259]
Essentially what's in the title, disregard if you are already in the process of doing so.

**Comment by doxxx** [comment]
I've updated with the latest recipes from the Lodestone.

@kongspark @RyuaNerin Some recipes' names changed -- you may want to check if the Chinese/Korean translations need to be updated:

* Alchemist: e8307b15435: Ala Mhigan Fiber -> Ala Mhigan Burdet
* Goldsmith: d9eb8bcbaa6: Hannya Mask -> Hanya Mask

**Comment by kongspark** [comment]
OK. As soon as Chinese server update to patch 4.4, I'll update the translations (including new recipe).
