### ISSUE TITLE
Total Success Percent Missing

### ISSUE THREAD

**Issue by Undene** [doxxx/ffxiv-craft-opt-web#264]
## Required Information

Class: Weaver
Level: 50
Craftsmanship: 242
Control: 229
CP: 287
Recipe Name: Moonfire Halter
Recipe Level: 50
Solver Seed: 1557551480496

## Expected Behaviour

Code for creating a macro is executing as it should, however, the "Total Success %" is missing when displaying completed macro statistics. Sometimes the percentage will display near the HQ% and Reliability % but most of the time it does not display.

Unable to trigger it at all on a spare home computer, even after trying different browsers (Chrome, Edge, and Fire Fox) and checking settings.

## Actual Behaviour

Only Progress, Quality, HQ%, and Relability % display after hitting the "solve" button.

## Steps To Reproduce

1) Open http://ffxiv.lokyst.net/index.html#/simulator in a new web browser for the first time. Plug in crafter details and skills under Crafter Attributes.
2) Choose your crafting class and recipe from the Simulator tab. Click solve.
3) Total Success % is missing after solver has completed Monte Carlo runs. Cannot get it to display after checking settings.

**Comment by doxxx** [comment]
As far as I recall, there has never been something called "Total Success %" displayed. The simulator status block at the top of the page displays "Reliability", which is another way of saying "the chance of a successful synth using this sequence". This is also shown as "Success Rate" in the Monte Carlo Sim tab at the bottom of the page.
