### ISSUE TITLE
Solver initial guess requires abilities not yet unlocked

### ISSUE THREAD

**Issue by Nosfvel** [doxxx/ffxiv-craft-opt-web#265]
## Required Information

Class: Blacksmith
Level: 60
Craftsmanship: 611
Control: 571
CP: 283
Recipe Name: Wolfram ingot
Recipe Level: 50 3-star
Solver Seed: 1557878469511 (if using all abilities)

## Expected Behaviour

Letting me run the solver

## Actual Behaviour

"Initial guess" includes abilities that are unlocked at later levels and thus not available (such as patient touch), and grays out the "start" button as a result. If I select the actions it wants in the initial guess it allows me to use the solver but, of course, a level 64 ability is not available to a level 60 blacksmith and so the solver result is useless.

## Steps To Reproduce

Options beyond available abilities do not matter. Simply try to run the solver as a level 60 blacksmith making wolfram ingots and the "start" button will be greyed out until you select abilities you can't use.

**Comment by doxxx** [comment]
The initial guess is entirely under your control. You can edit it to remove the unusable abilities in the Simulator and then start the Solver from that edited sequence.

**Comment by Nosfvel** [comment]
> The initial guess is entirely under your control. You can edit it to remove the unusable abilities in the Simulator and then start the Solver from that edited sequence.

Huh, wow - so I can. That's on me indeed, I got so focused on the "initial guess" part that when I tried editing it I didn't notice that the "solver result" included more actions than the guess did.
