### ISSUE TITLE
Macro failure due to french translation error for the Weaver's skill "Careful Synthesis"

### ISSUE THREAD

**Issue by jdubus** [doxxx/ffxiv-craft-opt-web#266]
## Required Information

Class: ALL
Level: At least 15 in Weaver

## Expected Behaviour

Macros using the french translation of the weaver skill "Careful Synthesis" should work

## Actual Behaviour

All those macro fails because the french translation is incorrect, it curently is "Synthèse Prudente" but should actually be "Travail Prudent", thus when executing those macros it doesn't find this skill and pass over it while executing the following actions and end up messing the crafting process resulting in failure.

## Steps To Reproduce

Trying any macro in french that use this skill.

**Comment by doxxx** [comment]
Ah, sorry, the main site (ffxiv.lokyst.net) is out of date. The beta site has up to date translations.

**Comment by jdubus** [comment]
Thanks, i tried the beta version and indeed i don't have to fix the macros before using thems, at least for now since i'm still leveling and thus don't know all actions yet, though i'm hopeful that they all are properly translated.
