### ISSUE TITLE
I can find only recipes for one class

### ISSUE THREAD

**Issue by Hotaru-Isayma** [doxxx/ffxiv-craft-opt-web#269]
## Required Information

Class: Alchemist
Level: 60
Craftsmanship: 349
Control: 436
CP: 321
Recipe Name: -
Recipe Level: -
Solver Seed: none

## Expected Behaviour

I can solve craftings for class other than culinarian on the computer

## Actual Behaviour

I cannot solve craftings for class other than culinarian on the computer

**Comment by Drakonas** [comment]
Have you tried changing the class from the dropdown on the top left?

**Comment by Hotaru-Isayma** [comment]
Yeah. Seemed I had to clear cookies to get this working but it seems to miss the point for me when I have to clear cookeis and insert everything over again just to add a class.

**Comment by doxxx** [comment]
Which browser are you using?

**Comment by Hotaru-Isayma** [comment]
Google Chrome

**Comment by doxxx** [comment]
I don't know what to suggest. It works for me and a lot of other people in Google Chrome. Could you maybe post screenshots that illustrate the problem?

**Comment by Hotaru-Isayma** [comment]
![2019-08-05](https://user-images.githubusercontent.com/51059890/62488114-ca2d8f80-b7c3-11e9-9dc9-9036ba81b19b.png)
![2019-08-05 (1)](https://user-images.githubusercontent.com/51059890/62488115-ca2d8f80-b7c3-11e9-8010-4f916e8160c9.png)
Please note that on culinarian I have "active" START button, and on armorer it is not active.

**Comment by doxxx** [comment]
Switch back to the Simulator page. Are any of the actions in the sequence greyed out? Those actions are not selected for your current class, so the Solver can't start with that sequence.

It really should show that in the Solve page as well.

**Comment by Hotaru-Isayma** [comment]
Yeah, some are greyed out. When I remove them from Simulator, it seems to work both on Armorer and Culinarian. But does it not have an influence on the results on the other classes?

**Comment by doxxx** [comment]
Please make sure that you have all the actions available to you for each
class selected in the crafter attributes page. The solver will not start
when the initial sequence contains actions that are not available for the
current class.
