### ISSUE TITLE
Progress to low

### ISSUE THREAD

**Issue by MaikC76** [doxxx/ffxiv-craft-opt-web#284]
## Required Information

Class: Leatherworker
Level: 71
Craftsmanship: 1744
Control:1557
CP: 468
Recipe Name: Smilodon leather
Recipe Level: 71 
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
carefull snythesis III should be 573
(Example: Standard Synthesis progress is 42)

## Actual Behaviour
Progress is just 426
(Example: Standard Synthesis progress is 38)

## Steps To Reproduce

(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

**Comment by MrFluffums** [comment]
It looks like this might be a calculation issue, as I'm having a similar miscalculation of progress by a significant margin:

Manasilver Nugget
GSM 70

Craftsmanship sim uses: 1695 (lower to adjust for slight miscalculations)
Simmed Careful Synthesis II progress: 368

Actual craftsmanship: 1698 (higher)
Actual Careful Synthesis II progress: 327

```
Seed: 100196

Crafter:
  Class: Weaver
  Level: 74
  Craftsmanship: 1695
  Control: 1636
  CP: 400
  Specialist: false

Recipe:
  Level: 403
  Difficulty: 3407
  Durability: 80
  Start Quality: 0
  Max Quality: 16091
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: true
  Algorithm: eaComplex
  Population: 500
  Generations: 1000
  Penalty Weight: 1000000
```

**Comment by MrFluffums** [comment]
It looks like the progress estimates might be off by quite a bit. I'm not looking to hijack, but it looks like the issue I encountered is directly related.

For a different craft, the sim is expecting 368 prog from a Careful Synthesis II, but the actual result in practice is 502 prog. I use a slightly adjusted value for the sim, but I actually use -3 craftsmanship (<1%) to account for miscalculations, but shouldn't result in a difference of 368 v 502.

![image](https://user-images.githubusercontent.com/39612534/61182118-a4620000-a5f4-11e9-8134-d984906858bd.png)
![image](https://user-images.githubusercontent.com/39612534/61182126-b80d6680-a5f4-11e9-9dce-5d98e81ca0d9.png)


`Seed: 68948

Crafter:
  Class: Weaver
  Level: 74
  Craftsmanship: 1695
  Control: 1636
  CP: 400
  Specialist: false

Recipe:
  Level: 403
  Difficulty: 3407
  Durability: 80
  Start Quality: 0
  Max Quality: 16091
  Aspect: none

Settings:
  Max Tricks Uses: 0
  Reliability: 100%
  Use Conditions: true
  Algorithm: eaComplex
  Population: 500
  Generations: 1000
  Penalty Weight: 1000000`

**Comment by ShammyLevva** [comment]
Post 71 level numbers aren't properly implemented yet so progress will be significantly off. Testers needed to list the following:

Crafter Level:
Recipe Level:
Craftmanship;
Control:
Progress 100% figure in game:
Quality 100% figure in game:

by building up a database of such figures the formulas can be tweaked to give accurate figures. At present it's a catch 22, no figures so not accurate, not accurate without figures.

**Comment by MrFluffums** [comment]
@ShammyLevva 

![image](https://user-images.githubusercontent.com/39612534/61182154-10dcff00-a5f5-11e9-96fd-e7e9fb97fca6.png)
![image](https://user-images.githubusercontent.com/39612534/61182158-189ca380-a5f5-11e9-9907-5e2ac10a0075.png)

**Comment by ShammyLevva** [comment]
Ideally a spreadsheet of values. Lots of screenshots would require lots of retyping numbers.

**Comment by MrFluffums** [comment]
I may take the time to build a sheet as I level to help apply this. Would the recipe level obtained from the Execution Log in the Optimizer under "Level:" be a viable model for recipe level for such a sheet?

**Comment by ShammyLevva** [comment]
The figures entered into the spreadsheet should all be the figures from the game. That way we can double check the simulator matches the game. If they are a hybrid it makes checking trickier.

It is possible for instance that there are mistakes or typos in the sim.

**Comment by Edrem** [comment]
Hi, I've created a quick spreadsheet of all the recipe levels I can currently see ingame (weaver 71-75) and their 100% progress and quality increments vs what is reported on the website.

https://docs.google.com/spreadsheets/d/1skFLa7JcW-VPHyLZzql0qwLBlO6AS0ZRCI-8nfd894Y/edit?usp=sharing

**Comment by vickyorlo** [comment]
Would it be possible to add the "at 100% efficiency..." info to the simulator screen? If I could see the numbers right there after picking the recipe, preferably where the progress/quality/cp bars are, it would be very quick to whip up a spreadsheet. I'd probably get some numbers for the <70 recipes too, considering the massive amount of people reporting off-by-one progress issues.

**Comment by ShammyLevva** [comment]
@vickyorlo that's the plan.

**Comment by MrFluffums** [comment]
Hello,

I started a spreadsheet and used values for 70 GSM, 74 LTW, 75 CUL, and 76 WVR at gear, 2 pieces unequipped, and food buffed values. I'll add more as I have more variable levels and gear.

https://docs.google.com/spreadsheets/d/1ismpPPi8tinT88kcVbok1JZ1UfUIxuz5wz61M8dEtR4/edit?usp=sharing

**Comment by ShammyLevva** [comment]
https://docs.google.com/spreadsheets/d/1nxRIA15udQ2cPne9g-bdvp6WPB4peQtj0lyw80G42Wg/edit?usp=sharing

I've taken a slightly different approach and listed for a single crafter for now all the variances between recipes at each level. Thus we can see that for pre 70 levels the sim is pretty much spot on most times for quality but can be considerably out for progress. It is wildly out for post 71 recipes.

**Comment by Meanelle** [comment]
Crafter Level: 71 Weaver
Recipe Level: 68
Craftmanship; 1645
Control: 1529
Progress 100% figure in game: 548
Quality 100% figure in game: 595
Optimizer 100% = 266 progress, 297 quality.

**Comment by doxxx** [comment]
We have a new set of formulas for progress and quality increase. These changes are available on the beta site (ffxiv-beta.lokyst.net). Please let me know if these discrepancies are resolved.

**Comment by noshlag** [comment]
The numbers are correct now, I think.  I believe this bug can be closed.

**Comment by doxxx** [comment]
Thanks for confirming.
