### ISSUE TITLE
Regarding progress/quality formulas

### ISSUE THREAD

**Issue by Igie** [doxxx/ffxiv-craft-opt-web#286]
I thought of an idea if you haven't already tried it. What if we use genetic algorithm to find actual 
increase  values. It would input character level, recipe level craftsmanship/control and would output progress/quality increase at 100%. To train it we would need bunch of data values of different levels though but we wouldn't need actual formula. 
Also it feels like there isn't a formula for that, the values increase at different rates and depends on something more than the variables mentioned above.

I'm really into cracking this though, if possible share your knowledge about formulas

**Comment by ShammyLevva** [comment]
It is a fairly linear polynomial formula so existing formulae aren't bad. Just needs a little tweak.

**Comment by ShammyLevva** [comment]
![image](https://user-images.githubusercontent.com/29687786/61318629-6552cb00-a7fd-11e9-930f-5df8f6104252.png)

**Comment by ShammyLevva** [comment]
What we really need is LOTS more data points here. If people can do the following:

For your crafter level select a recipe that is exactly the same level eg: lvl 73 weaver select a lvl 73 weaver recipe. Note the crafter level and recipe name for checking.

Now note your craftsmanship and what the progress is for that recipe that's the same level as you.
Now remove an item of clothing so that that the craftsmanship changes. Note the new craftsmanship and new progress figures. 
Repeat this for multiple different items of clothing. The idea is if we get a hundred odd data points we can more accurately interpolate the level 71+ formula. 

So we need:
Crafter level - recipe name, craftsmanship value, progress 100% value

**Comment by gr3ger** [comment]
Do we know how many data points earlier calculations are based off of?
Right off the bat I know some 60 calculations aren't precise etc, I'm trying to plot 63 right now as we speak.

**Comment by gr3ger** [comment]
![image](https://user-images.githubusercontent.com/456624/61533980-a2ea6a80-aa2e-11e9-91cc-e858d10fa124.png)

n = 97

**Comment by ShammyLevva** [comment]
There's a website that takes a set of points and gives you the polynomial instantly. So what we need is a large set of data points covering all levels of gear from 71-80.

https://mycurvefit.com/

Choose fit method of Polynomial and quadratic regression. Copy and paste data points into table to fit curve.

**Comment by ShammyLevva** [comment]
Note that we effectively need to end up for formulas for 1-50, 51-60, 61-70 and 71-80. As it is clear they change slightly each time.

**Comment by gr3ger** [comment]
To use more than 20 data points on that site you need to pay money, which unfortunately I cannot.
however, these are the settings I'm using in google sheets, is that not enough?
![image](https://user-images.githubusercontent.com/456624/61541291-ac300300-aa3f-11e9-94fd-a16732b0d6c3.png)

**Comment by gr3ger** [comment]
Degree is supposed to be quadratic, so this should work, correct?

**Comment by ShammyLevva** [comment]
Yes that google sheets formula should be fine it's doing the same thing. The core feature is we need the formula at the top aR2 + bR + C

Yes it is valid to have different level X no stars vs a level X recipe as long as the various X values stay within the ranges 1-50, 51-60, 61-70, 71-80. ie: 63 weaver 63 recipe and 69 goldsmith 69 recipe is entirely comparable. A 63 weaver 63 recipe and a 71 carpenter 71 carpenter recipe is not comparable as they are from different expansion packs.

**Comment by gr3ger** [comment]
Ok, I'll try populating 61-70 as best I can and give you the end equation, along with the sample size.

**Comment by gr3ger** [comment]
![image](https://user-images.githubusercontent.com/456624/61547924-b0165200-aa4c-11e9-8c22-30d2313ce863.png)
N = 187

I tried to get as broad a spectrum as possible, and try to cover all gaps.

**Comment by Igie** [comment]
If people could post google sheets or another way of sharing excel-like data, I need: Character level, recipe level, craftsmanship, control, progress increase, quality increase. I have made a neural network which trains on this data and can be used to predict value increase. Currently I don't have enough data as my crafters' levels are 65 - 68. But results aren't far off already

**Comment by gr3ger** [comment]
It doesn't have all the parameters you want, but here's what I have right now (read only)
https://docs.google.com/spreadsheets/d/1n0hUTaDZizMzAc2a6ZJVY3eJukDjGl4kq7kspN2Qh08/edit?usp=sharing

**Comment by Igie** [comment]
Could you perhaps add levels if you do more data gathering? Even if it's the same level it's okay

**Comment by gr3ger** [comment]
Level in this case doesn't matter since they're all gathered in the 61-70
range. For your ML purposes you can just put an arbitrary level in that
range for now.

**Comment by SilicaAnimusNormanni** [comment]
https://docs.google.com/spreadsheets/d/1ABEpFR46q9dUNOxrJxGfXn9Vo4BvPvmWZD1bVQTsjD4/edit?usp=sharing only have info for 72 and 73 mostly, with one at 75.
All are wearing the 70 scrip gear. I took off everything but the main tool, going down the left side, then right side, with an equivalent level craft. Wrote Craft/progress and Control/Quality down per class. (though as gear is identical, most were similar)

**Comment by ShammyLevva** [comment]
Thanks Silica. I've removed the duplicates and focused on progress as that's the one that if wrong can lead to failed craft.

Your data gives rise to an interesting factor that isn't catered for. As the level rises there is a slight penalty to progress. That penalty appears to vary in size depending on craftsmanship. 

The revised spreadsheet is https://docs.google.com/spreadsheets/d/1xvF6tERvT_4-qJZJZK3zu2_AncUg-hUxwn9uhmxbmTU

It's unique values that are of interest I'm going to try to create more by not just removing gear piece by piece but also by switching out different pieces, Note for the purpose of tying down progress formula it's not worth switching out gear with no craftsmanship at this stage. Once the progress formula is fairly accurate switching out control gear will be useful.

As an aside I noted that they've updated the Mission Allowance handins so you can now get massive amounts of XP from daily handins of individual crafted items. That with the new story quests that were giving several million XP for handing in 18 high quality items it should be possible to get a higher level crafter for testing soon.

**Comment by gr3ger** [comment]
"Your data gives rise to an interesting factor that isn't catered for. As the level rises there is a slight penalty to progress. That penalty appears to vary in size depending on craftsmanship"
If this is correct, that would explain why there are still some inconsistencies in my calculations despite my rather huge data set.
It's a bummer that if this is true, my efforts are pretty much pointless right now.

But it's good we're getting closer to the actual calculations in game.

**Comment by ShammyLevva** [comment]
Not pointless. If you look at the format of the spreadsheet I linked https://docs.google.com/spreadsheets/d/1xvF6tERvT_4-qJZJZK3zu2_AncUg-hUxwn9uhmxbmTU
You can add to it. Just need your crafting level 71-80, your craftsmanship value, and what the progress shows when you choose a recipe of the same level as yourself. 

Swap around some gear to get a range of values for your current level. Ideally we want around 100 values per crafting level and by sharing the load between us we can manage that.  

Note for your data 61-70. There is possibly a similar small level based tweak. If we can identify what level each of your values were at as you'd been doing then it's possible to establish a base formula and a tweak for level difference.

**Comment by gr3ger** [comment]
Can't see your spreadsheet, says I need to be granted access (I requested it).
And seeing as my sheet is a mishmash between crafters of different levels in the 61-70 range, it's impossible at this stage to fix it.
The algorithm I have now is better than the current one though, so that's something.

**Comment by ShammyLevva** [comment]
Apologies I'd set permissions wrongly.

**Comment by SilicaAnimusNormanni** [comment]
I am currently reworking mine. doing extensive swapping of gear.

**Comment by ShammyLevva** [comment]
New formulas deployed to beta site.

**Comment by DSHeavyWeaponSystem** [comment]
Hey! Was playing around with it today on my Lv71 CRP with Lv71 recipe (White Oak Lumber). The 100% Progress/Quality displays in the simulator were wrong, and after browsing the issues figured I'd get some data for you guys. It's in this spreadsheet:

https://docs.google.com/spreadsheets/d/11QTwz8EG7Qz27cyZd8iaAZE6YyQK4AnMoAfHV13sHfA/edit#gid=0

Formulas still appear off, somewhat significantly in this case. If you need more values I'd be happy to provide them!

**Comment by Igie** [comment]
I wandered to some other site with crafting simulator. Their formulas include recommended craftsmanship and control and their level tables for recipes and characters are a bit different.
So far it's really accurate. Formulas:

Progress = (Craftsmanship + 10000) / (SuggestedCraftsmanship + 10000) * ((Craftsmanship * 21) / 100 + 2) * factor

Quality = (Control + 10000) / (SuggestedControl + 10000) * ((Control * 35) / 100 + 35) * factor

where factor is how much recipe and character levels are different

**Comment by doxxx** [comment]
Where do they get the suggested crafstmanship/control values from?

**Comment by Igie** [comment]
Datamined recipes have them, I looked into it before leaving to work

**Comment by doxxx** [comment]
We have a new set of formulas for progress and quality increase. These changes are available on the beta site (ffxiv-beta.lokyst.net). Please let me know if these discrepancies are resolved.
