### ISSUE TITLE
Titanium nugget is listed at 40/40 durability when it is actually 35/35 in game.

### ISSUE THREAD

**Issue by Jengines** [doxxx/ffxiv-craft-opt-web#288]
Didn't want to start a new thread but the titanium nugget is listed at 40/40 durability when it is actually 35/35 in game. Of course any macro makes the synth go boom. Thanks.

_Originally posted by @Paperweight01 in https://github.com/doxxx/ffxiv-craft-opt-web/issues/287#issuecomment-512230719_

**Comment by Jengines** [comment]
I was looking in game and Titanium Nugget is listed at 40/40 durability, can you provide me more informations about this issue ?

![image](https://user-images.githubusercontent.com/26380350/61399234-fc875380-a8cd-11e9-9259-dfb9c6805791.png)

**Comment by Paperweight01** [comment]
Weirdest damn thing. It sorted itself out several hours later. Synth worked, stopped working then worked all over again.

**Comment by doxxx** [comment]
Glad it's working again!
