### ISSUE TITLE
Missing the "Blood Bouillabaisse" in Food menu

### ISSUE THREAD

**Issue by Kanisame** [doxxx/ffxiv-craft-opt-web#289]
**Food buff name:** Blood Bouillabaisse
**Class:** Any
**Level:** Any
**Craftsmanship:** +0%
**Control:** +4% (Max 51) [HQ: +5% (Max 64)]
**CP:** +21% (Max 53) [HQ: +26% (Max 66)]
**Recipe Name:** n/a
**Recipe Level:** n/a

**Workaround for time being:** Do not use any food buff on site, just add the differentce on solver page and match your stats in-game.

**Comment by doxxx** [comment]
Fix pushed to beta site.
