### ISSUE TITLE
Rapid Synthesis III conditions not handled correctly

### ISSUE THREAD

**Issue by Sanaki** [doxxx/ffxiv-craft-opt-web#291]
Rapid Synthesis III includes a caveat that it hits for less progress at low durability. That doesn't seem to be handled correctly by the calculator.

As an ALC 75 specialist with 1681 craftsmanship testing against Cordials, 100% = 598 progress. At 20+ durability it progressed 3588. At 15, 10, and 5 durability it progressed 1184. No buffs or special effects (other than inner quiet and steady hand II, which shouldn't have any effect) were used.

**Comment by doxxx** [comment]
Thanks for the info!

**Comment by ShammyLevva** [comment]
Yes no account of that has been added as yet. Obviously would need more test data for now adding a quick drop to 33% would work. 

Pull request with fix added.

**Comment by doxxx** [comment]
Fix deployed to beta site.

**Comment by doxxx** [comment]
I'm leaving this open for further discussion if the 33% drop is not correct.

**Comment by Sanaki** [comment]
From what I can tell it's actually a 198% potency synthesis below 20 durability, but I can't help but think that's modified by something else I'm just not noticing, because 198% is a rather odd number. Either way, 200% is good enough to prevent almost all issues for now.

**Comment by ShammyLevva** [comment]
@Sanaki yeah which would be consistent with 33% ie: 33% of 600% is 198%. whereas 33.333333...% is 200%.

**Comment by ShammyLevva** [comment]
I've tested this a few times now with different gear and it does always seem to be 198%. So I think we can close this one out.

**Comment by doxxx** [comment]
Thanks for verifying!
