### ISSUE TITLE
Solver attempts to stack Steady Hand and Steady hand II

### ISSUE THREAD

**Issue by bloop428** [doxxx/ffxiv-craft-opt-web#296]
## Required Information

Class: Weaver (Specialist)
Level: 64
Craftsmanship: 861
Control: 765
CP: 383 + 17 (from stone soup)
Recipe Name: Bloodhempen Yarn
Recipe Level: 61
Solver Seed: 132979

## Expected Behaviour

As Steady Hand and Steady Hand II can not be combined for +50% success rate, the solver should never attempt to do this.

## Actual Behaviour

The solver attempts to cast Steady Hand II directly followed by Steady Hand for a waste of 25 CP

## Steps To Reproduce

Solver options:
![image](https://user-images.githubusercontent.com/6138413/62077045-08dcac00-b1fe-11e9-9dab-bba3ccf7ef5d.png)

**Comment by bloop428** [comment]
As an extra addition to this, the simulator also allows you to stack the buffs which in game you can not do

![image](https://user-images.githubusercontent.com/6138413/62077122-345f9680-b1fe-11e9-85b1-8faf86c0e305.png)

**Comment by doxxx** [comment]
In game does the one buff replace the other?

**Comment by bloop428** [comment]
Yes, when you cast one it removes the other if it is active, I tested after seeing the solver try stacking them.

**Comment by doxxx** [comment]
Fix deployed to beta site.
