### ISSUE TITLE
Reuse does not appear in available actions WVR

### ISSUE THREAD

**Issue by illumix3** [doxxx/ffxiv-craft-opt-web#297]
## Required Information

Class: WVR
Level: 74
Craftsmanship: 1702
Control: 1521
CP: 398
Recipe Name: Brightlinen Yarn
Recipe Level: 70
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour

Reuse should be available in available actions

## Actual Behaviour

Reuse action not in available actions

## Steps To Reproduce

(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

**Comment by ShammyLevva** [comment]
Reuse has no practical value for the simulator it doesn't affect progress or quality. Thus would get ignored as it doesn't add anything to improve the progress or quality values. 

That and it's a random chance of a proc so needs to be manually dealt with regardless.

**Comment by doxxx** [comment]
Yup, not much point in including it.

**Comment by haasn** [comment]
Would it be worth including at the end of macros just to use in the case that it *does* proc? At the very least, this would be a worthwhile addition to the simulator, so you can design your own macros that include it. (And for the solver, well, you could add a checkbox to force reuse to be used at the end, before the last progress step)

**Comment by ShammyLevva** [comment]
No as that's not how reuse works. How it works is that it randomly procs when quality is at 100%. The Macro has absolutely no way at all of knowing when it will proc. So it could proc 6 steps before the end and then disappear and not reappear at the last step. So despite including it at the last step in the macro it wouldn't we usable you'd just get an error that the skill couldn't be used. 

So putting it in a macro is utterly pointless sorry.
