### ISSUE TITLE
Level 80 star recipes data needed.

### ISSUE THREAD

**Issue by ShammyLevva** [doxxx/ffxiv-craft-opt-web#301]
Level 80 star recipes are not all currently implemented. Data mining needed. The patch 5.0.5 went live on Tuesday so the scripts that imported the lvl 71-80 scripts could probably be used again to extract the level 80 star recipes.

**Comment by pstatonvt** [comment]
Yes please, would greatly appreciate the new master recipes!

**Comment by doxxx** [comment]
This should be updated on the beta site. Please let me know if there's still a problem.
