### ISSUE TITLE
Simulator grants more than 25 stacks of Maker's Mark

### ISSUE THREAD

**Issue by bloop428** [doxxx/ffxiv-craft-opt-web#303]
## Required Information

Class: Weaver
Level: 70
Craftsmanship: 1665
Control: 1549
CP: 400
Recipe Name: Pixie Cotton Sash
Recipe Level: 75
~~Solver Seed:~~

## Expected Behaviour

Maker's Mark can never grant more than 25 stacks as stated in the ability's tooltip
![image](https://user-images.githubusercontent.com/6138413/62404746-da3b3a00-b54b-11e9-9719-6165802ac693.png)

## Actual Behaviour

For this recipe, the simulator grants 35 stacks of Maker's Mark
![image](https://user-images.githubusercontent.com/6138413/62404759-fa6af900-b54b-11e9-8ebd-4ca9b6f11a3a.png)

## Steps To Reproduce

Cast Maker's Mark on first step

**Comment by doxxx** [comment]
Fix deployed to beta site.
