### ISSUE TITLE
Maximize "chance of receiving HQ" over "expected quality"

### ISSUE THREAD

**Issue by haasn** [doxxx/ffxiv-craft-opt-web#307]
It feels like the way the solver operates is that it tries to maximize the "expected quality" of the craft, even at the cost of sometimes coming up with sequences that can fail to make the item HQ if bad RNG arises.

Like, it will happily spit out a sequence that generates 10k quality 90% of the time but only 3k quality 10% of the time (by, say, using Byregot's Blessing without Steady Hand), which gives you an expected quality of 9300. However, say the item needs 9000 quality of be HQ; This only has like a 90% chance of actually making the item HQ - even though the solver will just flat out claim that it has a 100% HQ chance based on the quality numbers.

An actual user, though, probably prefers the sequence that has a 100% chance of generating exactly 9000 quality, since this comes out to a 100% HQ chance overall; even though the "expected quality" is lower.

The tl;dr, I think, is that we need a way to make the solver consider only **the overall chance that the craft result will be HQ**. It should prioritize a sequence that guarantees 100% HQ over a sequence that only does 99% HQ. This even goes further, to where I sometimes don't actually care about craft reliability if it can help increase the overall HQ chance. Like, I'd often rather have a sequence that has a 95% chance of making it HQ and a 5% chance of failing the synthesis, rather than a sequence that has a 90% chance of making it HQ and a 10% chance of making it NQ. (Although we can already get that to some extent by reducing the "reliability" setting)

---
~~As a side-note, the "monte carlo trials" screen should probably also have a number reflecting the total percentage of crafts that actually ended up HQ at the end of it all, because this number is more valuable to me than the misleading "100% HQ" number at the top of the screen.~~

**Edit:** Looked into the source code a bit, seems that the "Expected Value:" line already shows the true overall HQ rate. I was fearing it would just calculate the expected quality and then turn that into a percentage based on the formula, but that's not how it works. I'm fine with that, then.

**Comment by doxxx** [comment]
There's a setting for "reliability" in the solver options, that allows the solver to accept riskier solutions to attain higher quality results.

**Comment by doxxx** [comment]
The way to do this is to reduce the reliability % in the solver options. The solver will try to maximize quality while meeting the reliability %, so reducing that will allow it to reach higher quality values with a riskier sequence.
