### ISSUE TITLE
Food not available

### ISSUE THREAD

**Issue by LordQ42** [doxxx/ffxiv-craft-opt-web#310]
## Required Information

Class:all
Level:any
Craftsmanship:
Control:
CP:
Recipe Name:
Recipe Level:
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
dropdown selecting food populated
(Example: Standard Synthesis progress is 42)

## Actual Behaviour
Dropdown to select food has no available food in it, seems to have applied the last food I used but can't clear
(Example: Standard Synthesis progress is 38)

## Steps To Reproduce
Tried everything to remove the error, happens every time. 
(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

**Comment by Khaoila** [comment]
Found something to add to this while inspecting the page to see if I could figure anything it it looks like the Meals.json file has 404'd for some reason unfortunately don't know enough to figure out how to fix this but that looks to be the primary issue it's referencing a file that it can't access currently

**Comment by doxxx** [comment]
Please try clearing your browser cache and reloading the page.

**Comment by pisss** [comment]
Hi! I've tried your recommendations - and also opened in new browsers (which I haven't used before) and the food menu is still empty. This problem only started today.

**Comment by Khaoila** [comment]
As previous commentor stated after clearing browser cache the issue still occured and looking again it's still trying to reference Meal.json which doesn't exist as I mentioned finding in my first comment on this thread

**Comment by doxxx** [comment]
Sorry, it looks like I messed up the file sync'ing on the last website update. It should be fixed now.
