### ISSUE TITLE
Translation Failure

### ISSUE THREAD

**Issue by Liqq85** [doxxx/ffxiv-craft-opt-web#313]
Alchemist skills in German

the 37 Skill  "Brand of Elements"  is in German "Zeichen der Elemente"
the 37 Skill "Name of Elements" is in German "Name der Elemente"
the 72 Skill "Rapid Synthesis III" is in German "Schnelle Bearbeitung III"
the 76 Skill "Delicate Synthesis" is in German "Akribische Bearbeitung"
the 78 Skill "Intensive Synthesis" is in German "Fokussierte Bearbeitung"

thx for your great Work

## Required Information

Class:
Level:
Craftsmanship:
Control:
CP:
Recipe Name:
Recipe Level:
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour

(Example: Standard Synthesis progress is 42)

## Actual Behaviour

(Example: Standard Synthesis progress is 38)

## Steps To Reproduce

(Example: Buffs, Food, Synthesis Condition, Simulator/Solver Options if different from default)

**Comment by doxxx** [comment]
Should be fixed with the latest update.
