### ISSUE TITLE
Rounding differs between game and simulation

### ISSUE THREAD

**Issue by garrickp** [doxxx/ffxiv-craft-opt-web#314]
## Required Information

Class: Weaver
Level: 46
Craftsmanship: 201
Control: 203
CP: 265
Recipe Name: Undyed Felt
Recipe Level:43
Solver Seed: 170519

## Expected Behaviour

Standard Synthesis is 76

## Actual Behaviour

Standard Synthesis is 77

## Steps To Reproduce

Have a non-even progress increase value, and use Standard Synthesis. The game rounds down (i.e.  76.5 becomes 76), whereas the solve rounds up (76.5 becomes 77).

## Solver Sample vs. in-game log
```
Monte Carlo Random Example
==========================
 # Action                           DUR    CP      QUA      PRG    IQ  WWYW   CTL  QINC  BPRG  BQUA   WAC       Cond   S/F
 0                                   40   265        0        0     0     0   203     0     0     0     0     Normal     0
 1 Inner Quiet                       40   247        0        0     0     0   203     0     0     0     0     Normal     1
 2 Advanced Touch                    30   199      160        0     1     0   203   160     0   160     0     Normal     1
 3 Steady Hand                       30   177      160        0     1     0   244     0     0     0     0     Normal     1
 4 Great Strides                     30   145      160        0     1     0   244     0     0     0     0     Normal     1
 5 Advanced Touch                    20    97      526        0     2     0   244   366     0   366     0     Normal     1
 6 Great Strides                     20    65      526        0     2     0   284     0     0     0     0       Good     1
 7 Advanced Touch                    10    17     1143        0     3     0   284   617     0   411     0     Normal     1
 8 Standard Synthesis                 0     2     1143       77     3     0   325     0    77     0     0       Good     1
Progress Check: true, Durability Check: true, CP Check: true, Tricks Check: true, Reliability Check: true, Cross Class Skills: 0, Wasted Actions: 0
```
![ffxiv_08092019_120941_317](https://user-images.githubusercontent.com/833918/62799760-e3be2800-ba9e-11e9-8e5e-2bce57485841.png)

**Comment by doxxx** [comment]
Our model does round down, but the accuracy of the number before rounding is not perfect. It's a known problem. You can try tweak your craftsmanship values in the simulator buffs panel until it gets the right value.

**Comment by sharpobject** [comment]
Is there an open issue to track this?

**Comment by doxxx** [comment]
No, it's basically an unsolvable problem. The game developers choose to round the values at one or more points in the calculations and it's very hard if not impossible for us to determine where those points are.
