### ISSUE TITLE
Not calculating CP properly

### ISSUE THREAD

**Issue by vvvatlas** [doxxx/ffxiv-craft-opt-web#315]
## Required Information

Class: ALC
Level: 32
Craftsmanship: 169
Control: 164
CP: 258 +Tempura Platter buff (30)
Recipe Name: Blackfire Sand
Recipe Level: 32
Solver Seed: 152028

## Expected Behaviour

Calculate CP properly. You run out of CP before finishing the macro.

## Actual Behaviour

You run out of CP from step 8/13.

**Comment by doxxx** [comment]
Could you export your settings and attach the zip here?

**Comment by noshlag** [comment]
I was unable to repro this bug.  Unless we get more details from vvvatlas, I request that we close this bug.

**Comment by doxxx** [comment]
Agreed, the model has been changed since this was reported.
