### ISSUE TITLE
Add ability to determine optimal cross-class skills

### ISSUE THREAD

**Issue by zjturner** [doxxx/ffxiv-craft-opt-web#317]
This might be too taxing computationally, but it would be neat if you could enter all of your crafter levels and stats, and the system could recommend the best set of cross-class skills you should take.  Probably the way it would do this is to brute force every combination of cross-class skills that you have access to, and craft 10 high level items, 10 medium level items, and 10 low level items, and pick whichever combination had the best results.

As mentioned though, this may be too demanding computationally.  Another option would be to do this calculation offline assuming all crafts 80 for every subset of crafts the user has (there's only 256 combinations of at most elements, and the smaller ones would be very quick to brute force) and hardcode the tables into the app.  This way it can just do a quick lookup based on available crafts.

There could be other approaches too that I haven't thought of.

**Comment by doxxx** [comment]
I guess this is obsolete now?
