### ISSUE TITLE
ajax.googleapis.com blocked in China

### ISSUE THREAD

**Issue by lhfy1990** [doxxx/ffxiv-craft-opt-web#319]
Recently discovered that angularjs cdn is provided by googleapis.com, which is blocked in China (at least some areas).
So I would like to change it to cdn provided by angularjs.org directly, which works.
Not sure if this cdn will work fine or not in other countries. If not, maybe we can put it static in app/libs. The file size is only about 100KB.
I'll submit a pull request from my forks shortly.
Thank you.

**Comment by doxxx** [comment]
I believe this is resolved. Please let me know if it is not.
