### ISSUE TITLE
Focused Touch miss chance.

### ISSUE THREAD

**Issue by Tempestwolf79** [doxxx/ffxiv-craft-opt-web#321]
## Required Information

Class: all
Level: n/a
Craftsmanship:n/a
Control:n/a
CP:n/a
Recipe Name:n/a
Recipe Level:n/a
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour

The "Focused Touch" ability now requires the combo action of "Observe" to eliminate the 50% miss chance on Focused Touch.  The macro should calculate these abilities as a pair, as it now skews the results of the macro being successful.

## Actual Behaviour

Macros are generated without pairing "Observe" before hand causing the macro to fail about 50% of the time when Focused Touch, is used in the macro.

## Steps To Reproduce

Generate any macro using "Focused Touch"

**Comment by doxxx** [comment]
The model correctly implements the effect of Observe on Focused Synthesis and Focused Touch. If you're constructing a macro in the Simulator, it's up to you to include the Observe action.
