### ISSUE TITLE
[Feature Request] Option to make macro where all abilities have 100% chance of success

### ISSUE THREAD

**Issue by bloop428** [doxxx/ffxiv-craft-opt-web#323]
Example: Solver will never use Hasty Touch because it can never have a 100% chance even with steady hand. Solver would never use any Touch abilities without using Steady Hand or anything else to make it have a 100% chance of success

Pretty much just a minimum reliability setting for quality like there is for progress

**Comment by doxxx** [comment]
Have you tried reducing the reliability setting?

**Comment by doxxx** [comment]
When I reduce the reliability setting, the solver uses Hasty Touch as expected.

**Comment by bloop428** [comment]
Solver uses Hasty touch very often for me, even when at 100%.
