### ISSUE TITLE
5.0 lvl80 master recipes gone?

### ISSUE THREAD

**Issue by fryfryfryfryfry** [doxxx/ffxiv-craft-opt-web#324]
Hi, I apologize in advance for not knowing how to use github but I've been using (and loving) the crafting simulator for a while now. I found a link to the beta site at http://ffxiv-beta.lokyst.net/ here in the discussion and have been using it to make macros for level 80 master recipes.

Now this evening they're suddenly gone. I've refreshed and tried everything I can think of. Am I missing something simple, I hope?

Thanks for any answers, and thanks so much for the tool! It's invaluable.

**Comment by doxxx** [comment]
Can you give me an example of which recipes are missing?

**Comment by fryfryfryfryfry** [comment]
> Can you give me an example of which recipes are missing?

Yes, of course. I think it's all of the lvl80 master recipes. But for example, Robe Lettuce Salad. Either searching for it or manually scrolling down brings up nothing. 

It's so strange. It was fine for me up until yesterday or the day before. I even tried it in a different browser thinking I must be crazy or dumb. I'm still sure I must be but it's just not there.

I have a feeling it'll be something simple I missed and I'll be humbled by the answer. :)

**Comment by doxxx** [comment]
The recipe lists were last updated in July, so if this was something added in a patch since then, that's why it's missing. I'm pulling the latest recipes from the Lodestone and will update the website once it's done (it takes a while).

**Comment by doxxx** [comment]
I've updated the recipe lists on the beta website. Level 80 two-star recipes are now included.

**Comment by fryfryfryfryfry** [comment]
> I've updated the recipe lists on the beta website. Level 80 two-star recipes are now included.

Thank you so much, I see it!
