### ISSUE TITLE
Low Recipe Level Quality Miscalculations

### ISSUE THREAD

**Issue by IcySlurpee** [doxxx/ffxiv-craft-opt-web#327]
## Required Information

Class: WVR
Level: 29
Craftsmanship: 115
Control: 134
CP: 224
Recipe Name: Initiate's Slops
Recipe Level: 20
Solver Seed: Many. Known examples: 161586, 156525, 180244, 113917, 157415.

## Expected Behaviour
Great Strides + Basic Touch, solver says quality should increase by 2959 (or another very large amount, depending on condition).

## Actual Behaviour
Great Strides + Basic Touch, quality actually increases by 164 (100% efficiency = 82 * 2).

## Steps To Reproduce
No food or buffs.
Attempt to solve Initiate's Slops with no starting guess.
Solver immediately miscalculates.

**Comment by IcySlurpee** [comment]
[settings.zip](https://github.com/doxxx/ffxiv-craft-opt-web/files/3726341/settings.zip)

**Comment by doxxx** [comment]
Thanks, looks like it's the new model code. I'll take a look.

**Comment by doxxx** [comment]
Sorry about that, dumbass moment on my part. Should be fixed on the beta site if you force reload.

**Comment by IcySlurpee** [comment]
LOL, `min` vs `max` will do it. Looks good now. Thanks!
