### ISSUE TITLE
Preparatory Touch CP Values Differ on Website

### ISSUE THREAD

**Issue by Mof10** [doxxx/ffxiv-craft-opt-web#336]
## Required Information

Class: WVR
Level: 77
Craftsmanship: 1675
Control: 1619
CP: 446
Recipe Name: N/A
Recipe Level: N/A
Solver Seed: (Look at the top of the Execution Log on the Solver page)

## Expected Behaviour
CP Calculation uses 40 CP for Preparatory touch alongside 100% success rate.

## Actual Behaviour
CP Calculation uses 36 CP on website, alongside 70% success rate.

**Comment by tanpro260196** [comment]
The website is not updated to 5.1 yet. Check the PR if you want to report bugs

**Comment by Mof10** [comment]
I see. I'll update the values in actions.js on my personal setup, then.
