### ISSUE TITLE
Crafter levels above 70 are no longer supported

### ISSUE THREAD

**Issue by Flavescent** [doxxx/ffxiv-craft-opt-web#339]
## Expected Behaviour

When setting crafter attributes, levels up to 80 are supported.

## Actual Behaviour

Level values of over 70 cannot be entered.

## Steps To Reproduce

Enter "80" in the level field of the Alchemist crafter attributes.

**Comment by doxxx** [comment]
The main site is still on patch 4.x. Please use the beta site.
