### ISSUE TITLE
Solver miscalculating progress

### ISSUE THREAD

**Issue by Idran** [doxxx/ffxiv-craft-opt-web#350]
## Required Information

Class: Culinarian
Level: 60
Craftsmanship: 558
Control: 537
CP: 325
Recipe Name: Morel Salad
Recipe Level: 60
Solver Seed: 87495

## Expected Behaviour

The simulator is returning a progress increase with my current stats on this level of 118, which matches what's reported by FFXIV. Thus, Muscle Memory (which has an efficiency of 300%) should result in a progress increase of 354, which it does in game.

## Actual Behaviour

Muscle Memory is calculated as giving a progress increase of 356.

![](https://i.imgur.com/xcCljwJ.png)

There are similar miscalculations elsewhere in progress counts in the solver, but this one's the easiest to confirm as incorrect by hand. For example:

![](https://i.imgur.com/dqi0R9T.png)

Following the exact steps 1-6 here in game results in a total progress of 781, not 823.

## Steps To Reproduce

Setting up the raw stats above and creating a simulator action list that reproduces the above steps should do it.

**Comment by noshlag** [comment]
I'm almost certain that the game is doing a floor on the result of the efficiency _before_ multiplying it by three for Muscle Memory, but this app is doing that floor _after_ multiplying it by three.  I'll see if I can find the place in the code that the calculation is being done.

**Comment by noshlag** [comment]
That was the issue.  I am now trying to figure out how to get the change published.  It turned out to just be a pair of parenthesis on lines 73 and 77 of ffxivcraftmodel.js

![image](https://user-images.githubusercontent.com/4202005/71700865-1f71cb00-2d7b-11ea-91a7-bf7f0d14b689.png)

**Comment by noshlag** [comment]
Change is in this Pull Request:  https://github.com/doxxx/ffxiv-craft-opt-web/pull/351

Should be fixed once the PR goes through.

**Comment by doxxx** [comment]
Deployed to https://ffxiv-beta.lokyst.net
