### ISSUE TITLE
Math formula is wrong for synthesis

### ISSUE THREAD

**Issue by WaffleKnight** [doxxx/ffxiv-craft-opt-web#361]
Class:ALC
Level:61
Craftsmanship:424
Control:638
CP:299
Recipe Name:Skybuilders' Charcoal
Recipe Level:60
Solver Seed: 102451

/ac "Muscle Memory" <wait.3>
/ac "Inner Quiet" <wait.2>
/ac "Waste Not" <wait.2>
/ac "Innovation" <wait.2>
/ac "Basic Touch" <wait.3>
/ac "Basic Synthesis" <wait.3>
/ac "Standard Touch" <wait.3>
/ac "Standard Touch" <wait.3>
/ac "Innovation" <wait.2>
/ac "Standard Touch" <wait.3>
/ac "Great Strides" <wait.2>
/ac "Byregot's Blessing" <wait.3>
/ac "Basic Synthesis" <wait.3>
/echo Macro #1 complete

formula symbols:
X= base efficency number
Y= synthesis action
Z= Muscle Memory Buff (1)
Q= Innovation Buff (0.2)
W= Name of the Elements ( if using brand )

**Expected Behaviour**

Step #6: Basic Synthesis increase progress by 384

this is the simulator formula:
( X * Y ) * (1 + Q ) * ( ( Z * 2 ) * W )

**Actual Behaviour**

Step #6: Basic Synthesis increase progress by 353

this the the in-game formula:
( X * Y ) * ( 1 + Z + Q + W )

**Steps To Reproduce**

muscle memory buff + innovation + synth action

the wrong order of operation occurs between row 294-349 in master/app/js/ffxivcraftmodel.js

**Comment by doxxx** [comment]
In this example, synthesis 100% efficiency progress is 134. Basic Synthesis (L31) efficiency is 1.2.

```
134 * 1.2 * (1 + 1 + 0.2) = 353.76
```

How do you get 384?

**Comment by ryan-dyer-sp** [comment]
i believe 384 is what the simulator gives in this case.

From my own observation, in the case of muscle memory + innovation + careful synth the PIM from synth (1.5) is being multiplied by mm (2) and then innovation is multiplied (1.2) for a progressmultiplier of . 3.6 (1.5*2*1.2) .  The actual in game formula for this is 1.5 * (2+.2) = 3.3.

**Comment by WaffleKnight** [comment]
> i believe 384 is what the simulator gives in this case.
> 
> From my own observation (and looking at the sim code), in the case of muscle memory + innovation + careful synth the PIM from synth (1.5) is being multiplied by mm (2) and then innovation is multiplied (1.2) for a progressmultiplier of . 3.6 (1.5 * 2 * 1.2) . The actual in game formula for this is 1.5 * (2+.2) = 3.3.

This is exactly what is happening, instead of each of the buff multipliers being additive to each other (1(base) + 1(Muscle Memory) + 0.2(Innovative)) they multiply.

**Comment by doxxx** [comment]
Ah, sorry, math hard. :)

@ryan-der-sp: If I were to create a branch with the changes, could you verify it with a wider variety of synths and settings?

**Comment by doxxx** [comment]
Also, do you think the same applies to quality? Additive rather than multiplicative?

**Comment by doxxx** [comment]
See https://github.com/doxxx/ffxiv-craft-opt-web/tree/issue-361

**Comment by doxxx** [comment]
Fix deployed to beta site.
