### ISSUE TITLE
Progress wrong with Ingenuity+Careful Synthesis

### ISSUE THREAD

**Issue by Idran** [doxxx/ffxiv-craft-opt-web#365]
## Required Information

Class: Carpenter
Level: 62
Craftsmanship: 597
Control: 643
CP: 396
Recipe Name: Pine Lumber
Recipe Level: 64
Solver Seed: 63834

## Expected Behaviour

With Ingenuity, the simulator calculates progress of 210 from Careful Synthesis.

## Actual Behaviour

You get 274 progress from Careful Synthesis with Ingenuity.

**Comment by 27Steven34** [comment]
As Ingenuity has been removed in 5.2, this may no longer be applicable. Some verification should be done to verify there is not an issue here.

**Comment by doxxx** [comment]
Closing since Ingenuity has been removed.
