### ISSUE TITLE
Byregot stack efficency is calculated as a buff, not base efficency (quality error)

### ISSUE THREAD

**Issue by WaffleKnight** [doxxx/ffxiv-craft-opt-web#370]
It appears that the byregot stack efficency has been accidently added as an additive buff during the last change of the simulator.

it currently calculates in the simulator this way:
(1 (base eff.) * 1 (byregot no stack base)) * ( 1 (base) + ? (other buffs) + (0.2 * ? (stack count))

it should be this:
(1 (base eff.) * (1 (byregot base) + (0.2 * ? (stack count))) * ( 1 (base) + ? (other buffs))

Line 324-334 in file master/app/js/ffxivcraftmodel.js is where the issue occurs, qualityIncreaseMultiplier is being used for both the stack count and buffs like innovative and great strides.

example:
in game the final increase is 2530, where as it's 1840 in the simulator.

![Capture](https://user-images.githubusercontent.com/59671952/73863032-b977d800-483f-11ea-883f-ad22f53adba6.PNG)

ALC lvl: 63
Craftsmanship: 622
Control: 645
CP: 342
item: Skybuilders' Charcoal

**Comment by WaffleKnight** [comment]
update:
brand of the elements seem to have the same issue with progress calculation.
in simulator:
(1 (base eff.) * 1 (brand base)) * ( 1 (base) + ? (other buffs) +  X ( X = 1 (brand base)(X = 2 IF Name of the Elements is active))

in game:
(1 (base eff.) * (1 (brand base) + (2 IF Name of the Elements is active)) * ( 1 (base) + ? (other buffs))

Line 303-310 in file master/app/js/ffxivcraftmodel.js is where the issue occurs, it adds variable nameOfMultiplier to variable progressIncreaseMultiplier which is used by buffs like innovation and Muscle Memory.

**Comment by 27Steven34** [comment]
> brand of the elements seem to have a similar issue with progress calculation.

There is an open pull request for the BotE issue. I will look into creating a PR for the Byregot's issue as well. After that, the PRs will have to be accepted and the updates deployed before the site has the fixes.

If you would like to have the fixes without waiting for the PRs to be merged, I believe the README contains instructions for how to build and deploy a local version of the application (I have not done it myself).

**Comment by doxxx** [comment]
Deployed to beta site.
