### ISSUE TITLE
Changes in 5.2

### ISSUE THREAD

**Issue by tanpro260196** [doxxx/ffxiv-craft-opt-web#385]
### New Action:

**Veneration (Level 15):** Increases efficiency of Synthesis actions by 50% for the next four steps. Cost 18CP.

**Groundwork (Level 72):** Increases progress (300%) at greater cost to durability (20 durability instead of 10). Efficiency decreases by half when durability is below durability cost. Cost 18CP.

### Adjustment:

**Inner Quiet:** Control bonus can now exceed 3,000.

**Innovation:** Effect changed from _"Increases efficiency of Synthesis and Touch actions by 20% for the next four steps"_ to _"Increases efficiency of Touch actions by 50% for the next four steps."_

**Comment by doxxx** [comment]
#376 #377

**Comment by doxxx** [comment]
Partially deployed. Still need support for Groundwork.

**Comment by doxxx** [comment]
This should be complete now. Changes have been deployed to the beta site.
