### ISSUE TITLE
Missing Recipe's from 5.2.1 / Ishgardian Restoration (2)

### ISSUE THREAD

**Issue by SkyChotik** [doxxx/ffxiv-craft-opt-web#388]
Not sure if you've got a program to scrape the db for new recipes or not, but if you need I can write up all the recipes in the correct format.
Not sure about the new modifiers for the "Expert Recipe" or how that would affect the simulator.

**Comment by Scrxtchy** [comment]
skimmed over a handful of recepies, the difficulty, durability and max quality are all the same when counting into Grade 2

**Comment by doxxx** [comment]
I do have a program to scrape the Lodestone for recipes: https://github.com/doxxx/lodestone-recipe-db-scraper

I'll re-run it tonight.

**Comment by doxxx** [comment]
Recipes updated on beta site.
