### ISSUE TITLE
Update for patch 5.3?

### ISSUE THREAD

**Issue by wunaidage** [doxxx/ffxiv-craft-opt-web#405]
It has been two weeks, any updates? or how can I contribute?

**Comment by Montep00** [comment]
I have noticed there are still some missing recipes since 5.3 launch. From the pull requests it appears that someone ran the scraper tool to get some of the 5.3 items but the site still seems to be missing many recipes like the Aesthete's gear. Any update to when these will be added to the site?

**Comment by dten** [comment]
i'm hosting my version with #399 #406 and #407 merged here

https://dten.github.io/ffxiv-craft-opt-web

**Comment by Montep00** [comment]
Awesome, Thanks David!

**Comment by Cptnobvious** [comment]
Better believe I signed in just to say thanks.

**Comment by wunaidage** [comment]
thanks @dten 
I just sync from your fork and then made my own modification: **custom recipe function**
please see：
https://wunaidage.github.io/ffxiv-craft-opt-web/#/solver
now, if there were new recipe and the website hadn't included it yet, you can use the **custom recipe** function in solver page.
All inputs are required and you can find them in game.

**Comment by pxqt** [comment]
Hello @dten! First, thank you for hosting an updated version. In the event @doxxx does not or is unable to return to the project, do you intend to become the new maintainer? I'm asking as I'd like to have some idea of future support of this project. Thanks!

**Comment by StarkITA** [comment]
> thanks @dten
> I just sync from your fork and then made my own modification: **custom recipe function**
> please see：
> https://wunaidage.github.io/ffxiv-craft-opt-web/#/solver
> now, if there were new recipe and the website hadn't included it yet, you can use the **custom recipe** function in solver page.
> All inputs are required and you can find them in game.

Hi @wunaidage,

did you do a PR with this feature? It's very useful.

**Comment by wunaidage** [comment]
> > thanks @dten
> > I just sync from your fork and then made my own modification: **custom recipe function**
> > please see：
> > https://wunaidage.github.io/ffxiv-craft-opt-web/#/solver
> > now, if there were new recipe and the website hadn't included it yet, you can use the **custom recipe** function in solver page.
> > All inputs are required and you can find them in game.
> 
> Hi @wunaidage,
> 
> did you do a PR with this feature? It's very useful.

I can, but I dont think anyone can merge it

**Comment by StarkITA** [comment]
@dten could merge it to his fork
