### ISSUE TITLE
5.3 Update

### ISSUE THREAD

**Issue by ShatteredGod** [doxxx/ffxiv-craft-opt-web#411]
Can you please update this for 5.3? QwQ
Thank you guys for making this tho! it been real helpful, but kinda bummer that it doesnt have the new recipes

**Comment by pxqt** [comment]
@doxxx Hello Doxxx and sorry to bother you! Will you be continuing to maintain and update this project in the near term or should someone else do so until you can/will return?

**Comment by Amadeus-** [comment]
You should check for previous issues asking the same question before posting something new.   See [https://github.com/doxxx/ffxiv-craft-opt-web/issues/405](https://github.com/doxxx/ffxiv-craft-opt-web/issues/405)
