### ISSUE TITLE
Simulator indicates failure when synthing at 5 dur

### ISSUE THREAD

**Issue by lokyst** [doxxx/ffxiv-craft-opt-web#46]
Email from DrewIt:

"Thank you / Thank you / Thank you for this site
 
I noticed when I have 5 Durability left I can still do a basic synthesis (-10 dur) and it will succeed, but the site goes red and says it will fail.
 
- Thank you"

**Comment by doxxx** [comment]
Since no further information has surfaced for this, I'm closing it.
