### ISSUE TITLE
Careful Synthesis II returning bad progress

### ISSUE THREAD

**Issue by drewlt** [doxxx/ffxiv-craft-opt-web#49]
Careful Synthesis is only increasing by 44 – web app calculates it should do 45.
Rounding error?  (6) images attached here.

Thanks
-Andrew

![screenshot 1](https://cloud.githubusercontent.com/assets/6806783/5254731/a7d04ee6-7970-11e4-8497-089a11289af1.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/6806783/5254714/767ba5ca-7970-11e4-9a3d-b55f2f9fc5e5.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/6806783/5254712/767a6cf0-7970-11e4-8e40-023d6a085e36.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/6806783/5254716/767eacca-7970-11e4-86d1-4d4aa16c816e.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/6806783/5254713/767b2e9c-7970-11e4-907d-e90581171d82.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/6806783/5254711/76769526-7970-11e4-978d-3473823e54ba.png)

**Comment by doxxx** [comment]
Same as #53, this is as accurate as we can get.
