### ISSUE TITLE
Functionality/Ease of use improvement

### ISSUE THREAD

**Issue by Taurolyon** [doxxx/ffxiv-craft-opt-web#51]
From a user's standpoint, I suggest the following:
* A single class selection bar.
* Automatic clearing of solver results when changing recipes/class.

**Comment by doxxx** [comment]
I'm (slowly) working on a redesign of the site layout which should help
with these issues.

**Comment by Drakonas** [comment]
I would really love to see FFXIV-Lodestone-API integration, like Crafting-As-A-Service, so I can easily import my character level data. Saves a lot of time, and it would allow using code to automatically fill out cross-class abilities based on levels selected. There you go: the time required just got cut in half.

**Comment by doxxx** [comment]
Thanks, good idea.
