### ISSUE TITLE
Another reminder to regen recipedb.js / Missing recipes.

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#54]
The following recipes are currently missing from the culinarian list which are a mere regenerate away of the recipedb.

All ten of the Chocobo feed recipes and the Green Tea Set, which were added since last the file was generated (as of Apr 1st libra db update.)

**Comment by Diskmaster** [comment]
```
--- C:/Users/Diskmaster/Desktop/svngithg/ffxiv-craft-opt-web/scripts/recipedb-25.json	Fri Apr 03 18:42:51 2015
+++ C:/Users/Diskmaster/Desktop/svngithg/ffxiv-craft-opt-web/scripts/recipedb-255.json	Fri Apr 03 18:44:13 2015
@@ -3287,6 +3287,41 @@
     },
     {
       "maxQuality": 1584,
+      "name": "Grade 1 Feed - Speed Blend",
+      "level": 30,
+      "durability": 70,
+      "difficulty": 51
+    },
+    {
+      "maxQuality": 1584,
+      "name": "Grade 1 Feed - Acceleration Blend",
+      "level": 30,
+      "durability": 70,
+      "difficulty": 51
+    },
+    {
+      "maxQuality": 1584,
+      "name": "Grade 1 Feed - Balance Blend",
+      "level": 30,
+      "durability": 70,
+      "difficulty": 51
+    },
+    {
+      "maxQuality": 1584,
+      "name": "Grade 1 Feed - Endurance Blend",
+      "level": 30,
+      "durability": 70,
+      "difficulty": 51
+    },
+    {
+      "maxQuality": 1584,
+      "name": "Grade 1 Feed - Stamina Blend",
+      "level": 30,
+      "durability": 70,
+      "difficulty": 51
+    },
+    {
+      "maxQuality": 1584,
       "name": "Dalamud Red Dye",
       "level": 30,
       "durability": 70,
@@ -3804,6 +3839,13 @@
       "difficulty": 624
     },
     {
+      "maxQuality": 1323,
+      "name": "Green Tea Set",
+      "level": 55,
+      "durability": 80,
+      "difficulty": 624
+    },
+    {
       "maxQuality": 2646,
       "name": "Red Drop",
       "level": 55,
@@ -3935,6 +3977,41 @@
       "level": 70,
       "durability": 80,
       "difficulty": 745
+    },
+    {
+      "maxQuality": 2921,
+      "name": "Grade 2 Feed - Speed Blend",
+      "level": 70,
+      "durability": 80,
+      "difficulty": 116
+    },
+    {
+      "maxQuality": 2921,
+      "name": "Grade 2 Feed - Acceleration Blend",
+      "level": 70,
+      "durability": 80,
+      "difficulty": 116
+    },
+    {
+      "maxQuality": 2921,
+      "name": "Grade 2 Feed - Balance Blend",
+      "level": 70,
+      "durability": 80,
+      "difficulty": 116
+    },
+    {
+      "maxQuality": 2921,
+      "name": "Grade 2 Feed - Endurance Blend",
+      "level": 70,
+      "durability": 80,
+      "difficulty": 116
+    },
+    {
+      "maxQuality": 2921,
+      "name": "Grade 2 Feed - Stamina Blend",
+      "level": 70,
+      "durability": 80,
+      "difficulty": 116
     },
     {
       "maxQuality": 5257,
```

**Comment by doxxx** [comment]
The FFXIV Libra app has not been updated since 8 March, which is when I last regenerated the database and updated the site.

**Comment by doxxx** [comment]
In the meantime, you can type in the new recipe stats yourself and save the synth.

**Comment by Diskmaster** [comment]
App Version: 1.5.0
Database Version: 2015033101 (Droid)

**Comment by doxxx** [comment]
I've just updated all the apps in iTunes on my PC and the timestamp on the FFXIV Libra.app bundle is still 8 March. That's where I get the database from. If the database is being updated in the app, I have no access to that.

**Comment by Diskmaster** [comment]
Do you mind if I start attaching the relevant sqlite file in future bug reports then?

**Comment by doxxx** [comment]
I think it's a bit big for that. I'm going to investigate downloading the android app and running it in an emulator to update the database and then extract it.

**Comment by Diskmaster** [comment]
Have you tried to update from within the app, by chance? Database updates aren't fetched the same as app updates from my experience.

**Comment by doxxx** [comment]
Well, that's kinda my point. The only way the database could be updated without there being a new version of the app released on the store is if the app downloads the new database while running on your device. The problem is that I use the iOS version of the database and I can't access the filesystem of the app in the device, so I can't get the updated database that way.

That's why I'm going to try the Android app in an emulator. I'm hoping that will allow me to access the filesystem of the app in the emulator and get the new database file.

**Comment by doxxx** [comment]
The site has been updated with the latest recipe database.
