### ISSUE TITLE
translation of skills

### ISSUE THREAD

**Issue by CKing** [doxxx/ffxiv-craft-opt-web#55]
Hey, I use your generator for a while now, pretty accurate results. Good job on that :)

My question tho: I play the game in German and sadly need to translate the skill names everytime. Nothing serious, but it would be nice to have the option to translate the skill names. I tried to add that functionality on my own, but I never worked with angular and this (little) project was overwhelming to me...

**Comment by doxxx** [comment]
Do you just need the generated macro to be translated or is it more than
that?

**Comment by CKing** [comment]
The macro should be enough. Skills are clear thanks to the icons (also I know the english translation).

**Comment by doxxx** [comment]
I haven't been able to find a machine readable form of the crafting skills and their translations, which means I will have to construct my own. When I have the structure in place, I would appreciate your help putting in the German translation.

**Comment by CKing** [comment]
Sorry for my late response.
I created JSON files with translations for the english, german and french translations.
You can find them here: https://gist.github.com/CKing/908a348d846ae29bd81b

**Comment by doxxx** [comment]
You rock! I'm working on this right now.

**Comment by doxxx** [comment]
The site has been updated with the new version. I also included German and French xivdb tooltips. :)
