### ISSUE TITLE
Hotfix related name changes.

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#61]
From [http://forum.square-enix.com/ffxiv/threads/71744-NA-FINAL-FANTASY-XIV-Hotfixes-%28Jul.-14-2015%29?p=3191016&viewfull=1#post3191016] if you aren't already aware:
・The following item names have been changed:
　- Titanium Armor of Fending → Adamantite Armor of Fending
　- Titanium Armor of Maiming → Adamantite Armor of Maiming
　- Holy Rainbow Cap of Casting → Rainbow Cap of Casting
　- Holy Ramie Cloth → Hallowed Ramie Cloth

**Comment by doxxx** [comment]
Thanks for letting us know. I'll update the beta site as soon as I can.
