### ISSUE TITLE
[Beta Site] JS Errors

### ISSUE THREAD

**Issue by Diskmaster** [doxxx/ffxiv-craft-opt-web#70]
Browser: Firefox ESR 38.2

Simulator page gives the following on the dev console:
TypeError: settings.crafter is undefined 
simulationworker.js:16:0

Solver page also gives after hitting Start:
"ReferenceError: LogOutput is not defined" 
worker.js:34:4

Edit: I should probably actually add useful information. Attempted general use like trying to use the solver and simulator like normal, there was an existing set of steps with a grayed out edit button already filled in on the simulator section.

**Comment by doxxx** [comment]
Had you used the beta site before?

Please execute `localStorage` in the console, click the "Storage" object that should show in the console log and then copy the values of the crafterStats, pageState_v2 and synths properties that appear in the object listing on the right, and paste them here.

**Comment by doxxx** [comment]
Although, now that I look at the line numbers in those errors, they don't match up to the code, which makes me suspect that the browser has not properly refreshed some of the js files. Could you also try a force-reload on the page?

**Comment by doxxx** [comment]
I've tried to reproduce the problem in FireFox 39.0.3 but couldn't. So it's either the refresh problem or something about your existing saved settings.

**Comment by Diskmaster** [comment]
01:48:07.238 Storage { pageStage_v2: "{"sections":{"crafter":true,"synth"…", NG_TRANSLATE_LANG_KEY: "en", crafterStats: "{"Alchemist":{"level":52,"craftsman…", synths: "{}", userRecipes: "{"Alchemist":{},"Armorer":{},"Black…", length: 5 }

That's what it currently spits out, and a bit of research, I found a way to clear my localStorage, so I'm going to try that.

Okay, it cleared out the stale data, but-

**Comment by Diskmaster** [comment]
Shortly after pushing that reply, I switched to the release channel in firefox and results are ... working fine. ... huh. Guess some sort of regression in the ESR release?

**Comment by doxxx** [comment]
It's far more likely to have been bad data in localStorage or stale cached js files. But regardless, glad it's sorted out. :)
