### ISSUE TITLE
Name of the Wind

### ISSUE THREAD

**Issue by drewlt** [doxxx/ffxiv-craft-opt-web#85]
Macro spits out "Name of Wind" which fails
should be "Name of the Wind"

:)

**Comment by doxxx** [comment]
Should be fixed on the beta site now. You may need to do a force-reload (Shift-Click the Refresh button in your browser) to get it.

**Comment by drewlt** [comment]
Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  (picture this goes on for a while, your site is invaluable :) )

-Andrew
