### ISSUE TITLE
Synthesis Fails

### ISSUE THREAD

**Issue by Thortok** [doxxx/ffxiv-craft-opt-web#91]
Alright, I've double-checked that I had the right stats loaded this time.

Alchemist, level 25, Craftsmanship 157, recipe is Natron, ingenuity buff, basic synthesis, Optimizer says 44 but correct value is 43.

**Comment by Thortok** [comment]
Goldsmith, level 25, Craftsmanship 148, recipe is Flawless Band, no buff, careful synthesis, Optimizer says 30 but correct value is 29.

**Comment by doxxx** [comment]
By "synthesis fails" I'm guessing you mean that it completed early before you could perform quality increasing actions?

**Comment by Thortok** [comment]
The opposite.  It didn't complete at all.  The optimizer thought it would get more progress than it actually did, so not enough progress occurred in game.

**Comment by doxxx** [comment]
There is unfortunately no quick and easy fix for this.

**Comment by Thortok** [comment]
Here's a Synth too quickly one:
Level 26 Goldsmith, recipe is Sunstone Ring, craftsmanship 152, basic synthesis progress in-game is 31, in optimizer is 30.

**Comment by Thortok** [comment]
Another fail.  Level 28 Blacksmith, recipe is steel cross-pein hammer, with ingenuity buff, basic synth progress is 36, optimizer thinks it's 37.

**Comment by Thortok** [comment]
Another fail.  Level 30 Carpenter, craftsmanship 161, recipe is vintage square shield, with ingenuity buff, basic synth progress is 17, optimizer thinks it's 36.  This one is really, really far off.

**Comment by Thortok** [comment]
Another fail.  Level 30 Leatherworker, craftsmanship 153, recipe is boarskin crakows, with ingenuity buff, careful synth progress is 30, optimizer thinks it's 31.

**Comment by doxxx** [comment]
We should be handling items which require a specific elemental aspect, like the Vintage items, so if you could give more information I'd appreciate it. How much progress do you get for the appropriate Brand of X action vs a Basic Synthesis on a Vintage item?

**Comment by Thortok** [comment]
I'm not actually high enough level to have those abilities yet but I'll let you know when I am =D

**Comment by doxxx** [comment]
Any more examples of Vintage items (or other items with an elemental aspect) would be useful.

**Comment by Thortok** [comment]
It does appear to be an issue with elemental aspect recipes.  Level 30 Alchemist, craftsmanship is 168, recipe is Maddening Daggers, with ingenuity buff, basic synth progress is 18, optimizer has it as 37.  Also, careful synth progress is 16, optimizer has it as 33.

It's going to be several levels before my crafters get from level 30/31 to 37 and get the brand actions available.  Hope you can fix it sooner.  =(

**Comment by Thortok** [comment]
Level 30 Alchemist, craftsmanship is 168, recipe is Vintage Picatrix, with ingenuity buff, basic synth progress is 18, optimizer has it as 37.  Without ingenuity buff, basic synth progress is 11, optimizer has it as 18.

**Comment by Thortok** [comment]
Level 31 Leatherworker, craftsmanship is 182, recipe is Vintage Shepherd's Belt, with ingenuity buff, careful synth progress is 19, optimizer has it as 38.  Also with ingenuity buff, standard synth progress is 31, optimizer has it as 64.

**Comment by Thortok** [comment]
Level 31 Blacksmith, craftsmanship is 164, recipe is steel ingot, with ingenuity buff, careful synth progress is 45, optimizer has it as 45.

**Comment by doxxx** [comment]
Typo in last one?

**Comment by Thortok** [comment]
Yup, fixed.

Level 31 Blacksmith, craftsmanship is 164, recipe is Vintage Bastard Sword, with ingenuity buff, careful synth progress is 17, optimizer has it as 34.  Without ingenuity buff, standard synth is 18, optimizer has it as 33.  Without ingenuity buff, basic synth is 12, optimizer has it as 22.

**Comment by Thortok** [comment]
Here's a synth too quickly one.

Level 32 Goldsmith, craftsmanship is 163, recipe is Mythril Wristlets of Crafting, without ingenuity buff, careful synth progress is 24, optimizer thinks it's 23.  Also basic synth progress is 27, optimizer thinks it's 25.

**Comment by Thortok** [comment]
Level 32 Goldsmith, craftsmanship is 163, recipe is Vintage Cudgel, without ingenuity buff, standard synth progress is 20, optimizer thinks it's 38, also basic synth progress is 13, optimizer thinks it's 25.

**Comment by Thortok** [comment]
Level 33 Carpenter, craftsmanship is 184, recipe is Vintage Cane, with ingenuity buff, standard synth progress is 30, optimizer thinks it's 61.  With ingenuity buff, basic synth progress is 20, optimizer thinks it's 41.  Without ingenuity buff, standard synth progress is 18, optimizer thinks it's 30.

**Comment by Thortok** [comment]
Synth too quickly:

Level 33 Armorer, craftsmanship is 192, recipe is Steel-plated Caligae, without ingenuity buff, basic synth progress is 35, optimizer thinks it's 34.  Without ingenuity buff, standard synth progress is 53, optimizer thinks it's 51.

**Comment by Thortok** [comment]
Level 33 Armorer, craftsmanship is 192, recipe is Vintage Hoplon, without ingenuity buff, careful synth progress is 16, optimizer thinks it's 30.  Without ingenuity buff, standard synth progress is 26, optimizer thinks it's 51.

**Comment by Thortok** [comment]
Synth too quickly:

Level 33 Goldsmith, craftsmanship is 175, recipe is 36 - Mythril Ring of Crafting, without ingenuity buff, careful synth progress is 26, optimizer thinks it's 24.

**Comment by Thortok** [comment]
Level 34 Leatherworker, craftsmanship is 188, recipe is 37 - Vintage Chef's Belt, without ingenuity buff, careful synth progress is 14, optimizer thinks it's 26.  With ingenuity buff, careful synth is 20, optimizer thinks it's 41.  With ingenuity buff, standard synth is 34, optimizer thinks it's 69.

**Comment by Thortok** [comment]
Level 34 Leatherworker, craftsmanship is 188, recipe is 39 - Vintage Smithy's Gloves, without ingenuity buff, careful synth progress is 11, optimizer thinks it's 18.  With ingenuity buff, standard synth is 31, optimizer thinks it's 63.

**Comment by Thortok** [comment]
Level 34 Blacksmith, craftsmanship is 190, recipe is 38 - Vintage Viking Sword, without ingenuity buff, careful synth progress is 12, optimizer thinks it's 22.  Without ingenuity buff, basic synth progress is 14, optimizer thinks it's 25.  With ingenuity buff, basic synth progress is 22, optimizer thinks it's 44.

**Comment by Thortok** [comment]
Level 34 Armorer, craftsmanship is 199, recipe is 38 - Vintage Celata, without ingenuity buff, careful synth progress is 13, optimizer thinks it's 23, basic synth progress is 14, optimizer thinks it's 26.

**Comment by Thortok** [comment]
Synth too quickly:

Level 34 Goldsmith, craftsmanship is 182, recipe is 37 - Heliodor Choker, without ingenuity buff, standard synth progress is 46, optimizer thinks it's 42.  Without ingenuity buff, basic synth progress is 30, optimizer thinks it's 28.

**Comment by Thortok** [comment]
Level 34 Alchemist, craftsmanship is 188, recipe is 39 - Wand of Tides, with ingenuity, standard synth is 62, optimizer says 63.

**Comment by Thortok** [comment]
Synth too quickly:

Level 35 Blacksmith, craftsmanship is 190, recipe is 40 - Mythril Claw Hammer, without ingenuity, standard synth is 37, optimizer thinks it's 31.  With ingenuity buff, basic synth is 42, optimizer thinks it's 38.  With ingenuity buff, careful synth is 37, optimizer thinks it's 34.

**Comment by Thortok** [comment]
Synth too quickly:
Level 35 Blacksmith, craftsmanship is 190, recipe is 40 - Mythril File, with ingenuity buff, careful synth progress is 37, optimizer thinks it's 34.

**Comment by Thortok** [comment]
Synth too quickly:
Level 35 Blacksmith, craftsmanship is 190, recipe is 40 - Mythril Awl, without ingenuity buff, careful synth progress is 22, optimizer thinks it's 19.  Without ingenuity buff, standard synth progress is 37, optimizer thinks 31.

**Comment by Thortok** [comment]
Synth too quickly:
Level 35 Culinarian, craftsmanship is 198, recipe is 38 - Mugwort Carp, without ingenuity buff, basic synth progress is 33, optimizer has it as 30.

**Comment by Thortok** [comment]
Synth Fail:
Level 35 Alchemist, craftsmanship is 194, recipe is 39 - Clinker Bricks, with ingenuity buff, standard synth progress is 67, optimizer thinks it's 68.

**Comment by Thortok** [comment]
Synth Fail:
Level 36 Armorer, craftsmanship is 199, recipe is 40 - Vintage Scutum, without ingenuity buff, careful synth progress is 13, optimizer thinks it's 23.  Without ingenuity buff, brand of earth progress is 29, optimizer thinks it's 53.

**Comment by Thortok** [comment]
Level 36 Weaver, craftsmanship is 188, recipe is 35 - Vintage Half Apron, without ingenuity buff, brand of wind progress is 21, optimizer thinks it's 44.

**Comment by Thortok** [comment]
Synth too quickly:
Level 37 Goldsmith, craftsmanship is 182, recipe is 40 - Jadeite, without ingenuity buff, standard synth progress is 46, optimizer thinks it's 42.  Without ingenuity buff, careful synth progress is 27, optimizer thinks it's 25.

**Comment by Thortok** [comment]
Synth too quickly:
Level 37 Goldsmith, craftsmanship is 182, recipe is 40 - Peridot Earrings, without ingenuity buff, standard synth progress is 46, optimizer thinks it's 42.  Without ingenuity buff, careful synth progress is 27, optimizer thinks it's 25.  Without ingenuity buff, basic synth progress is 30, optimizer thinks it's 28.

**Comment by Thortok** [comment]
Synth too quickly:
Level 37 Alchemist, craftsmanship is 194, recipe is 38 - Embossed Book of Silver, without ingenuity buff, basic synth progress is 39, optimizer thinks 38.  No buff, standard synth is 59, optimizer thinks 58.

**Comment by Thortok** [comment]
Synth too quickly:
Level 38 Carpenter, craftsmanship is 194, recipe is 41 - Plumed Oak Macuahuitl, without ingenuity buff, standard synth is 49, optimizer thinks 45.

**Comment by Thortok** [comment]
Synth too quickly:
Level 38 Carpenter, craftsmanship is 194, recipe is 43 - Garnet Grinding Wheel, without ingenuity buff, basic synth is 25, optimizer thinks 21.

**Comment by Thortok** [comment]
Synth Fail:
Level 38 Carpenter, craftsmanship is 194, recipe is 43 - Vintage Round Shield, without ingenuity buff, Brand of Wind is 25, optimizer thinks 43.

**Comment by Thortok** [comment]
Synth Fail:
Level 38 Weaver, craftsmanship is 192, recipe is 38 - Woolen Yarn, without ingenuity buff, standard synth is 63, optimizer thinks 64.

**Comment by Thortok** [comment]
Synth too quickly:
Level 38 Carpenter, craftsmanship is 194, recipe is 39 - Oak Pattens, without ingenuity buff, standard synth is 59 not 58, basic synth is 39 not 38.

**Comment by Thortok** [comment]
Synth too quickly:
Level 38 Leatherworker, craftsmanship 199, (41) Boarskin Moccasins, no buff, standard synth is 50 not 46.

**Comment by Thortok** [comment]
Synth Fails:
38 LTW, Craft 199, (41) Vintage Thighboots, no buff, Brand of Earth is 33 not 62.

**Comment by Thortok** [comment]
Synth too quickly:
38 GSM, Craft 187, (41) Pearl Earrings, no buff Careful Synth is 28 not 26, no buff standard synth is 47 not 43, ingenuity basic synth is correct at 45.

**Comment by Thortok** [comment]
Synth Fail:
38 WVR, Craft 192, (37) Vintage Coatee, no buff standard synth is 33 not 67.

**Comment by Thortok** [comment]
Synth too quickly:
39 BSM, Craft 203, (42) Mythril Round Knife, no buff careful synth is 30 not 28, no buff basic synth is 34 not 31.

**Comment by Thortok** [comment]
Synth Fail:
39 GSM, Craft 191 (30) Siltstone Whetstone, no buff careful synth is 50 not 51.

**Comment by Thortok** [comment]
Synth Fail:
39 BSM, Craft 203, (42) Goblin Scimitar, no buff brand of fire is 34 not 63, no buff careful synth is 15 not 28, no buff basic synth is 17 not 31.

**Comment by Thortok** [comment]
Synth Fail:
39 ARM, Craft 209, (41) Vintage Scale Mail, no buff brand of ice is 38 not 74.

**Comment by Thortok** [comment]
Synth Fail:
39 LTW, Craft 203, (43) Silver Tricorne, no buff brand of wind is 30 not 54.

**Comment by Thortok** [comment]
Synth Fail
39 WVR, Craft 196, (38) Vintage Doublet Vest, no buff brand of wind is 45 not 91.

**Comment by Thortok** [comment]
Synth Fail:
40 CRP, Craft 213, (40) Vintage Guisarme, no buff brand of ice is 28 not 47, ingenuity brand of ice is 47 not 94.

**Comment by Thortok** [comment]
Synth too quickly:
40 LTW, Craft 203, (40) Boarskin Smithy's Gloves, ingenuity buff standard synth is 84 not 81, ingenuity basic synth is 56 not 54

**Comment by Thortok** [comment]
Synth too quickly:
41 ALC, Craft 217, (45) Mega-Potion of Intelligence, no buff careful synth is 29 not 26.

**Comment by Thortok** [comment]
Synth Fail:
41 CUL, Craft 217, (41) Jerked Beef, no buff standard synth is 71 not 72.

**Comment by Thortok** [comment]
Synth Fail:
42 ARM, Craft 213, (43) Vintage Buckler, no buff brand of earth is 43 not 85.

**Comment by Thortok** [comment]
Synth Fail:
42 ARM, Craft 213, (45) Vintage Kite Shield, no buff brand of ice is 35 not 66, ingenuity brand of ice is 51 not 104.

**Comment by Thortok** [comment]
Synth too quickly:
42 GSM, Craft 203, (45) Black Pearl, no buff standard synth is 51 not 47, no buff basic synth is 34 not 31.

**Comment by Thortok** [comment]
Synth Fail:
42 GSM, Craft 203, (41) Rubellite, no buff standard synth is 70 not 71.

**Comment by Thortok** [comment]
CUL 42, Craft 217, (42) Salt Cod Puffs, no buff standard synth is 71, not 72.

**Comment by Thortok** [comment]
43 ARM, Craft 227, (46) Vintage Haubergeon, ingenuity brand of earth is 55 not 110, ingenuity basic synth is 27 not 55.

**Comment by Thortok** [comment]
43 ARM, Craft 227, (47) Mosshorn Scale Mail, no buff brand of ice is 52 not 105.

**Comment by Thortok** [comment]
43 LTW, Craft 214, (47) Dodore Doublet, no buff standard synth is 24 not 42, no buff brand of earth is 32 not 57, no buff careful synth is 14 not 25.

**Comment by Thortok** [comment]
43 WVR, Craft 206, (45) Vintage Chef's Apron, no buff basic synth is 26 not 52.

**Comment by Thortok** [comment]
44 GSM, Craft 230, (45) Vintage Hora, no buff careful synth is 20 not 41, no buff brand of fire is 46 not 91.

**Comment by Thortok** [comment]
44 WVR, Craft 212, (41) Vintage Chef's Hat, no buff careful synth is 24 not 48, no buff basic synth is 26 not 54.

**Comment by Thortok** [comment]
45 CUL, Craft 224, (44) Dzemael Gratin, no buff standard synth is 77 not 78.

**Comment by Thortok** [comment]
47 CRP, Craft 234, (47) Vintage Bow, no buff brand of wind is 51 not 103.

**Comment by Thortok** [comment]
46 WVR, Craft 233, (43) Vintage Hose, no buff standard synth is 44 not 89.

**Comment by Thortok** [comment]
47 BSM, Craft 246, (45) Goblin Longsword, no buf careful synth is 26 not 53, no buff brand of fire is 59 not 119.

**Comment by Thortok** [comment]
48 CRP, Craft 250, (50***) Blank Grade 2 Orchestrion Roll, no buff standard synth is 44 not 45.

**Comment by Thortok** [comment]
48 BSM, Craft 256, (47) Vintage Bill, no buff standard synth is 44 not 89.

**Comment by Thortok** [comment]
48 WVR, Craft 242, (45) Vintage Seneschal Coatee, no buff basic synth is 31 not 64.

**Comment by Thortok** [comment]
48 WVR, Craft 245, (45) Vintage Jester's Cap, no buff basic synth is 31 not 62, no buff careful synth is 27 not 56.

**Comment by Thortok** [comment]
48 CUL, Craft 259, (50*) Rolanberry Cheesecake, no buff standard synth is 46 not 55, ingenuity buff standard synth is 70 not 68, no buff basic synth is 30 not 37.

**Comment by Thortok** [comment]
49 WVR, Craft 256, (46) Vintage Coif, no buff brand of lightning is 64 not 130, no buff careful synth is 29 not 58.

**Comment by Thortok** [comment]
49 LTW, Craft 259, (50*) Uraeus Breeches, no buff careful synth is 27 not 36, ingenuity 2 buff brand of lightning/earth is 61 not 62.

**Comment by Thortok** [comment]
49 WVR, Craft 256, (47) Vintage Robe, no buff brand of ice/fire is 30 not 62, no buff careful synth is 27 not 56.

**Comment by Thortok** [comment]
49 ALC, Craft 259, (50*) Vamper's Knives, no buff brand of water is 30 not 40, ingenuity 2 careful synth is 55 not 56, no buff careful synth 2 is 36 not 48, no buff careful synth is 27 not 36.

**Comment by Thortok** [comment]
49 CUL, Craft 259, (51) Sour Cream, no buff standard synth is 45 not 47.

**Comment by KaitlinMS** [comment]
Just wanted to chime in and say that I'd love to see recipes with elemental aspects fixed!

**Comment by Thortok** [comment]
Synth too quickly: 50 BSM, Craft 281, (50*) Militia Pliers, ingenuity careful synth 2 = 72 not 74, ingenuity careful synth = 54 not 55, no buff careful synth 2 = 43 not 37, no buff careful synth = 32 not 27.

**Comment by Thortok** [comment]
50 LTW, Craft 298, (50*) Glacial Boots, ingenuity basic synth = 64 not 65.

**Comment by Thortok** [comment]
50 WVR, Craft 282, (50) Patrician's Bottoms, no buff standard synth = 92 not 93.

**Comment by Thortok** [comment]
50 ALC, Craft 309, (50*) Erudite's Picatrix of Casting, ingenuity 2 basic synth = 76 not 78.

**Comment by danj2k** [comment]
I found a bug with higher level recipe penalty calculation for crafter levels<120 resulting in wrong progress value, which may be related to this issue - details in #140.

**Comment by doxxx** [comment]
All the progress and quality formulas have been updated for patch 4.0.
