### ISSUE TITLE
Macros are now 20 lines

### ISSUE THREAD

**Issue by Taurolyon** [doxxx/ffxiv-craft-opt-web#93]
I happened to notice the game client accepts 20-line macros.

This is up from the previous 15 lines. The optimizer is geared to only produce 15-line segments.

**Comment by doxxx** [comment]
Thanks for the notice. :)

**Comment by Thortok** [comment]
Are you sure?  I've noticed that you can name a macro up to 20 characters but the window is still showing 15 lines for the actual macro itself.

**Comment by Taurolyon** [comment]
It must have been a temporary thing or a game client bug. It's back to 15 lines. Boo.

**Comment by doxxx** [comment]
Thanks for double-checking. I've reverted the change.
